### ISSUE TITLE
build broken on Windows

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#2362] opened 2018-08-16 18:20 UTC
Windows 10 64 bit
Visual Studio 2017 15.8
CMake 3.12.1

Tested with master (8edb8ac2cf8ae0bf12524fe98f19561e0de884b7) and few older commits.

I'm getting the following error:
```
27>AngelScript.lib(as_callfunc_arm.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_mips.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_ppc.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_ppc_64.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_sh4.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_x64_gcc.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_x64_mingw.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_x64_msvc.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>AngelScript.lib(as_callfunc_xenon.obj) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
27>IOAPI.obj : fatal error LNK1179: invalid or corrupt file: duplicate COMDAT '??_9File@Urho3D@@$B7AE'
27>Done building project "Urho3D.vcxproj" -- FAILED.
```

I think it might be related to the recently released VS 15.8

**Comment by weitjong** [comment] 2018-08-17 02:33
In order to isolate the problem, could you temporarily disable AS and see how far it gets you?

**Comment by Stinkfist0** [comment] 2018-08-17 06:12
FWIW, I think I had this error in some other project(s) a while back, maybe when updating some of the earliest VS 2017 versions. IIRC, complete cleanup/rebuild of the project helped.

**Comment by Enhex** [comment] 2018-08-17 10:33
I tried disabling AS and Urho3D compiles successfully.

@Stinkfist0 I tried complete rebuild several times with different commits.
BTW I also confirmed this issue on another person's machine with newly installed VS/CMake/Urho.

**Comment by Enhex** [comment] 2018-08-17 20:51
tried it and still getting the same error

**Comment by weitjong** [comment] 2018-08-18 03:59
It's worth a try. If you have not done it, I can help to setup a test branch for this.

**Comment by weitjong** [comment] 2018-08-18 06:11
I managed to setup appveyor to use VS2017 preview VM  image that I believe reproducing your build issue. Hopefully it is useful when testing the new AS version later.

**Comment by SuperWangKai** [comment] 2018-08-19 13:48
I confirm this issue.  Exact the same issue and I'm using VS2017 (ver. 15.8.1)

**Comment by weitjong** [comment] 2018-08-20 00:56
Thanks for your confirmation. I have updated our AS fork to pull in all the new commits from upstream. After I have satisfied with the test result against the new AS (version 2.33.0 WIP), I will merge the changes into the test branch I mentioned earlier. I hope we are not barking up a wrong tree.

**Comment by weitjong** [comment] 2018-08-20 14:59
I have a bad news. Merged the latest AS library into this test branch `VS2017-CI` and the CI build still failed with the same error.

**Comment by Enhex** [comment] 2018-08-20 19:58
Might be relevant?:
https://www.gamedev.net/forums/topic/696776-msvc-optimization-bug/

**Comment by weitjong** [comment] 2018-08-21 01:54
We have a couple of reported issues with newer releases of VS2017 also. The last one was handled by Eugene, turns out to be compiler bug generating wrong optimized code but is fixed by MS later. Could you try to build using Debug build config? If it built fine then we could safely assume it is yet another compiler optimization bug.

**Comment by SuperWangKai** [comment] 2018-08-21 14:14
Debug is also broken.

**Comment by CG-SS** [comment] 2018-08-21 15:06
Having the same problem here, VS2017 complains about missing Urho3D_d.lib when I try to compile in Debug mode.

**Comment by weitjong** [comment] 2018-08-22 03:01
Might be related to this. https://developercommunity.visualstudio.com/content/problem/296073/lnk1179-duplicate-comdat-in-visual-studio-158-prev.html

**Comment by SuperWangKai** [comment] 2018-09-09 02:38
It seem that it still doesn't work for new VS update 15.8.3

**Comment by orefkov** [comment] 2018-09-10 21:40
As workaround on VS2017 you can write somewhere in AngelScript\APITemplates.h:

```
template<typename T>
inline static unsigned _seek(T* t, unsigned s) {
	return t->Seek(s);
}
```
And in
`template <class T> void RegisterDeserializer(asIScriptEngine* engine, const char* className)`
change line
`engine->RegisterObjectMethod(className, "uint Seek(uint)"...........`
by
`engine->RegisterObjectMethod(className, "uint Seek(uint)", asFUNCTION(_seek<T>), asCALL_CDECL_OBJFIRST);`

**Comment by Inoc4** [comment] 2018-09-11 18:57
@orefkov 
Thanks, man!
Finally, I now have an editor and a player.

**Comment by black6816** [comment] 2018-09-17 09:54
when disable anglescript, we can build Urho3D with vc2017, but the Urho3D only build 22 project . is this ok?

**Comment by codec-abc** [comment] 2018-10-31 15:58
Got hit by this error when trying to build too. Can the fix by @orefkov be merged?

**Comment by weitjong** [comment] 2018-11-04 04:51
Isn't the 15.9 preview version that includes a fix for this issue already out? Has anyone tried it yet?

I don't think I would merge this "workaround" as fix as it is, unless the workaround is guarded specifically for VS 15.8 only.

**Comment by codec-abc** [comment] 2018-11-05 14:35
Thanks for the answer. I missed the fact that it should be fixed on the newer Visual Studio. Is it possible to use the AppVeyor CI to make sure of that? If it's confirmed that the bug is fixed by the newer version, maybe closing the issue is acceptable since it would happen in a very edge case (People compiling Urho from source on Windows with a specific version of Visual while enabling AngelScript).

**Comment by ArnisLielturks** [comment] 2018-11-14 19:02
I can confirm that this is fixed VS 15.9.0. Glad to get the AS back on Windows builds! 👍

**Comment by Pchovidze** [comment] 2019-01-10 15:55
VS 15.9.5 gives me

`2>Temporary workaround for MASM`
`2>System could not find specified path.`
`2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe"exited with code 3.`

Win10 x64 Debug/Release

**Comment by LeithKetchell** [comment] 2019-01-17 04:48
With regard to error MSB6006 and exit code 3... From what I can gather, this error code indicates that a Custom Build Step is attempting to reference a file that doesn't exist. I suggest you start there - have a look at the custom build step(s), and which files they reference, then verify that those files indeed exist, and that the filepaths are correct.

**Closed** 2019-01-17 15:45 UTC
Labels: wontfix
