### ISSUE TITLE
Make latest emsdk work again.

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [urho3d/Urho3D#2447] opened 2019-05-14 15:09 UTC
old issue
https://github.com/urho3d/Urho3D/issues/2446

Opening new ticket to dump infos.
Might fix it myself when I have time, idk.

---

So somebody apparently implemented in-html preprocessor, which uses symbol '#' since 1.38.7 onwards.
https://github.com/emscripten-core/emscripten/pull/6510
Which leads to similar issue like this https://github.com/emscripten-core/emscripten/issues/7700

This time the processor chokes on this line
```
#!/usr/bin/env 
```
![image](https://user-images.githubusercontent.com/8407331/57708963-2db48f00-76a5-11e9-8ce5-c0e749e439c0.png)

Which were probably generated from here 
https://github.com/urho3d/Urho3D/blob/f1ca13db22e79d94003a11665ec27918220872b2/CMake/Modules/UrhoCommon.cmake#L1138

Ii might also be possible to simply disable the html macro processor.
https://github.com/emscripten-core/emscripten/blob/4b5662d3a322c514aaac1e87af377696e47de901/tools/preprocessor.js#L135

**Comment by weitjong** [comment] 2019-05-14 15:42
Thanks for info. This will definitely help.

**Comment by UNDEFINED-BEHAVIOR** [comment] 2019-05-14 15:46
![image](https://user-images.githubusercontent.com/8407331/57711991-c6014280-76aa-11e9-9804-3c4ce8e6a4ea.png)

https://github.com/godotengine/godot/issues/25100
https://github.com/godotengine/godot/commit/35728e41ba21da931cac5a1c15b52f06b28af353

**Comment by weitjong** [comment] 2019-05-14 16:55
Someone suggested before that we need to upgrade SDL version to resolve the second problem.

**Comment by Dugy** [comment] 2019-05-18 21:55
I was able to get it running on the most recent Emscripten by updating the SDL's copy's handling of joysticks (changed API) and Pointer_stringify (function renamed, the old one throws exceptions). Here's my diff:

<details><summary>Long diff inside</summary>
<p>

```diff
diff --git a/Source/ThirdParty/SDL/src/SDL_assert.c b/Source/ThirdParty/SDL/src/SDL_assert.c
index 1eca9232d..205c51632 100644
--- a/Source/ThirdParty/SDL/src/SDL_assert.c
+++ b/Source/ThirdParty/SDL/src/SDL_assert.c
@@ -239,7 +239,7 @@ SDL_PromptAssertion(const SDL_assert_data *data, void *userdata)
             SDL_bool okay = SDL_TRUE;
             char *buf = (char *) EM_ASM_INT({
                 var str =
-                    Pointer_stringify($0) + '\n\n' +
+                    UTF8ToString($0) + '\n\n' +
                     'Abort/Retry/Ignore/AlwaysIgnore? [ariA] :';
                 var reply = window.prompt(str, "i");
                 if (reply === null) {
diff --git a/Source/ThirdParty/SDL/src/joystick/emscripten/SDL_sysjoystick.c b/Source/ThirdParty/SDL/src/joystick/emscripten/SDL_sysjoystick.c
index cd2fd56a4..b8e3ad4e4 100644
--- a/Source/ThirdParty/SDL/src/joystick/emscripten/SDL_sysjoystick.c
+++ b/Source/ThirdParty/SDL/src/joystick/emscripten/SDL_sysjoystick.c
@@ -1,6 +1,6 @@
 /*
   Simple DirectMedia Layer
-  Copyright (C) 1997-2017 Sam Lantinga <slouken@libsdl.org>
+  Copyright (C) 1997-2016 Sam Lantinga <slouken@libsdl.org>
 
   This software is provided 'as-is', without any express or implied
   warranty.  In no event will the authors be held liable for any damages
@@ -28,6 +28,7 @@
 #include "SDL_events.h"
 
 #include "SDL_joystick.h"
+#include "SDL_hints.h"
 #include "SDL_assert.h"
 #include "SDL_timer.h"
 #include "SDL_log.h"
@@ -41,7 +42,7 @@ static SDL_joylist_item *SDL_joylist_tail = NULL;
 static int numjoysticks = 0;
 static int instance_counter = 0;
 
-static EM_BOOL
+EM_BOOL
 Emscripten_JoyStickConnected(int eventType, const EmscriptenGamepadEvent *gamepadEvent, void *userData)
 {
     int i;
@@ -110,7 +111,7 @@ Emscripten_JoyStickConnected(int eventType, const EmscriptenGamepadEvent *gamepa
     return 1;
 }
 
-static EM_BOOL
+EM_BOOL
 Emscripten_JoyStickDisconnected(int eventType, const EmscriptenGamepadEvent *gamepadEvent, void *userData)
 {
     SDL_joylist_item *item = SDL_joylist;
@@ -145,7 +146,7 @@ Emscripten_JoyStickDisconnected(int eventType, const EmscriptenGamepadEvent *gam
     /* Need to decrement the joystick count before we post the event */
     --numjoysticks;
 
-    SDL_PrivateJoystickRemoved(item->device_instance);
+       SDL_PrivateJoystickRemoved(item->device_instance);
 
 #ifdef DEBUG_JOYSTICK
     SDL_Log("Removed joystick with id %d", item->device_instance);
@@ -166,12 +167,13 @@ SDL_SYS_JoystickInit(void)
     EmscriptenGamepadEvent gamepadState;
 
     numjoysticks = 0;
-    numjs = emscripten_get_num_gamepads();
+    retval = emscripten_sample_gamepad_data();
 
     /* Check if gamepad is supported by browser */
-    if (numjs == EMSCRIPTEN_RESULT_NOT_SUPPORTED) {
+    if (retval == EMSCRIPTEN_RESULT_NOT_SUPPORTED) {
         return SDL_SetError("Gamepads not supported");
     }
+    numjs = emscripten_get_num_gamepads();
 
     /* handle already connected gamepads */
     if (numjs > 0) {
@@ -239,14 +241,12 @@ JoystickByIndex(int index)
     return item;
 }
 
-int
-SDL_SYS_NumJoysticks(void)
+int SDL_SYS_NumJoysticks()
 {
     return numjoysticks;
 }
 
-void
-SDL_SYS_JoystickDetect(void)
+void SDL_SYS_JoystickDetect()
 {
 }
 
@@ -313,6 +313,8 @@ SDL_SYS_JoystickUpdate(SDL_Joystick * joystick)
     SDL_joylist_item *item = (SDL_joylist_item *) joystick->hwdata;
     int i, result, buttonState;
 
+    emscripten_sample_gamepad_data();
+
     if (item) {
         result = emscripten_get_gamepad_status(item->index, &gamepadState);
         if( result == EMSCRIPTEN_RESULT_SUCCESS) {
@@ -330,7 +332,7 @@ SDL_SYS_JoystickUpdate(SDL_Joystick * joystick)
 
                 for(i = 0; i < item->naxes; i++) {
                     if(item->axis[i] != gamepadState.axis[i]) {
-                        /* do we need to do conversion? */
+                        // do we need to do conversion?
                         SDL_PrivateJoystickAxis(item->joystick, i,
                                                   (Sint16) (32767.*gamepadState.axis[i]));
                     }
diff --git a/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenmouse.c b/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenmouse.c
index 8232dac32..e81b322ea 100644
--- a/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenmouse.c
+++ b/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenmouse.c
@@ -205,7 +205,7 @@ Emscripten_ShowCursor(SDL_Cursor* cursor)
             if(curdata->system_cursor) {
                 EM_ASM_INT({
                     if (Module['canvas']) {
-                        Module['canvas'].style['cursor'] = Module['Pointer_stringify']($0);
+                        Module['canvas'].style['cursor'] = UTF8ToString($0);
                     }
                     return 0;
                 }, curdata->system_cursor);
diff --git a/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c b/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c
index 897d47096..1003f97a5 100644
--- a/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c
+++ b/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c
@@ -343,7 +343,7 @@ static void
 Emscripten_SetWindowTitle(_THIS, SDL_Window * window) {
     EM_ASM_INT({
       if (typeof Module['setWindowTitle'] !== 'undefined') {
-        Module['setWindowTitle'](Module['Pointer_stringify']($0));
+        Module['setWindowTitle'](UTF8ToString($0));
       }
       return 0;
     }, window->title);

```
</p>
</details>

**Comment by weitjong** [comment] 2019-05-19 00:52
Thanks for the info. So it appears upgrading SDL would help indeed.

**Comment by UNDEFINED-BEHAVIOR** [comment] 2019-05-19 12:06
Got impatient and bumped SDL all the way to master.
https://github.com/UNDEFINED-BEHAVIOR/SDL-mirror/tree/urho3d/deploy-patched/86819b8

Future upstream change and hot fixes should be tracked and more easily merged down the line now.
Didn't confirm that sample does builds for any other platform than desktop and web tho.

**Comment by weitjong** [comment] 2019-05-19 12:46
We have an SDL fork repo in our Github "urho3d" org exactly for this tracking upstream already.

**Comment by UNDEFINED-BEHAVIOR** [comment] 2019-05-19 14:23
Oh, didn't know that..
will clear it up later.

**Comment by weitjong** [comment] 2019-05-19 14:46
I have fetched from the upstream and synced those new commits into our own fork earlier in preparation for the upgrade. You are welcome to contribute and send the PR but you have to do it in the proper way by applying those of our local changes on top of the new commits from upstream in order for your PR to get accepted. Due to my eyes problem I have to take frequent breaks (even my old DELL monitor needs to take a few minutes break every half an hour due to its internal circuit got overheated, it's a blessing in disguise as it "works" better than my timer :-), so if you are up to it then there is a good chance you can get it done ahead of me.

**Comment by UNDEFINED-BEHAVIOR** [comment] 2019-05-19 18:28
@weitjong 
https://github.com/UNDEFINED-BEHAVIOR/SDL-mirror/tree/rolling/master-modified-for-urho3d
It's almost ready. 
Its a merge of master -> to urho 2.0.7 so you can keep the old 2.0.7 for tagging.
Would you mind branching this 
https://github.com/urho3d/SDL-mirror/tree/release-2.0.7-modified-for-urho3d
off in to a new "rolling version" branch to receive it?

**Comment by weitjong** [comment] 2019-05-20 04:36
Thanks for that. However, our common branching/merging strategy is to “rebase” our own local changes “onto” the target master/release branch, and that push the result as “*master/release*-modified-for-urho3d” branch. This makes our own local changes always float  to the top of the HEAD, as if we have just applying those changes after newly upgraded. This gives us the chance to decide whether to either keep/adapt/remove our local changes accordingly.

**Comment by UNDEFINED-BEHAVIOR** [comment] 2019-05-21 06:48
Though I broke the water sample(23_Water) sample but turns out web gallery ones are broken too.
https://urho3d.github.io/samples/23_Water.html Move around a bit and it crashes.
Crashing can be suppressed by adding ```-s "BINARYEN_TRAP_MODE='clamp'"``` linker flag but its still rendered wrong.
https://emscripten.org/docs/compiling/WebAssembly.html#binaryen-codegen-options

@weitjong 
Just to confirm, I'm supposed to:
1.  Checkout release-2.0.7-modified-for-urho3d, master (urho/sdl's)
2.  Rebase release-2.0.7-modified-for-urho3d on top of master
3.  Clear out the conflicts on my fork
4.  PR back as urho3d/SDL-mirror: master-modified-for-urho3d?

**Comment by weitjong** [comment] 2019-05-21 16:17
I have read that options page before and at the time decided to keep it defaulted to "allow", thinking in general our engine code and most the samples work fine with it. The other rationale is that the engine in general also does not catch/handle the exceptions in other platforms too (there is only one or two `try` block as far as I know).  Anyway the developer can always override the default in their own build and project. But perhaps, we should at least demonstrate how that option can be overridden by using this offending "Water" sample.

Re. PR, I think in this case you can make it against the "master" branch of the fork repo. Once the PR is made, we can easily pull it to any dev branch that we choose for review and testing. Of course, I cannot promise you at this moment that your PR will be merged in its entirety but rest assure if any of your commits are being used (cherry-picked) then your credit will be preserved.

**Comment by UNDEFINED-BEHAVIOR** [comment] 2019-05-22 12:05
There, ↑

Some more notes:
Urho3D itself needs these 2 modification to compile under this PR

1, 
``` diff --git a/Source/Urho3D/Input/Input.cpp b/Source/Urho3D/Input/Input.cpp
index 2ef0b9aaf..9935c21f5 100644
--- a/Source/Urho3D/Input/Input.cpp
+++ b/Source/Urho3D/Input/Input.cpp
@@ -51,7 +51,7 @@

 #include "../DebugNew.h"

-extern "C" int SDL_AddTouch(SDL_TouchID touchID, const char* name);
+extern "C" int SDL_AddTouch(SDL_TouchID touchID,SDL_TouchDeviceType touchDeviceType, const char* name);^M

 // Use a "click inside window to focus" mechanism on desktop platforms when the mouse cursor is hidden
 #if defined(_WIN32) || (defined(__APPLE__) && !defined(IOS) && !defined(TVOS)) || (defined(__linux__) && !defined(__ANDROID__))
@@ -1199,7 +1199,7 @@ void Input::SetTouchEmulation(bool enable)

             // Add a virtual touch device the first time we are enabling emulated touch
             if (!SDL_GetNumTouchDevices())
-                SDL_AddTouch(0, "Emulated Touch");
+                SDL_AddTouch(0, SDL_TouchDeviceType::SDL_TOUCH_DEVICE_DIRECT, "Emulated Touch");^M
         }
         else
             ResetTouches();
```
2, Remove shebang # character mentioned earlier. (or disable emscripten html preprocessor)
https://github.com/urho3d/Urho3D/blob/f1ca13db22e79d94003a11665ec27918220872b2/CMake/Modules/UrhoCommon.cmake#L1138

Some issue I can't find a way around yet.
- Emscripten debug build with ```-O0``` will fail in runtime due to assertion error during js module  loading. Temporarily solved by setting at least ```-O1```
- wasm streaming compile failing
- new SDL_SIMD* alloc/free function got called on emscripten platform.
- android, IOS merge was pretty dodgy..

**Comment by weitjong** [comment] 2019-05-22 16:22
Nice! Will review at the soonest.

**Comment by weitjong** [comment] 2019-05-26 04:04
I have started to work on this, albeit rather slowly. I have decided to do it the "hard way" so I know what are those changes from the upstream and resolve the conflict accordingly. Dropping old commits that I think not necessary anymore, merging some old commits together (two of them actually annihilate each other), correcting my past mistake, and so on. Basically rewriting the commit history of our own local changes. Do not confuse the commit history in the SDL fork repo with the commit history of the SDL subtree in the master branch, the latter won't be rewritten in anyway.

**Comment by weitjong** [comment] 2019-06-05 06:07
Sorry for the delay. The progress is slow on my side due to personal reasons but I hope to wrap this one up by end of the week and to push out the dev branch for CI build tests across all our officially supported platforms the week after.

**Comment by weitjong** [comment] 2019-06-10 15:46
I think we are almost there, still have to make a few commits to adapt Urho to the new SDL library. I am also preparing a new docker container with the latest EMCC. Also bought myself a new PS4 controller to test the HIDAPI integration later. 😄

**Comment by weitjong** [comment] 2019-06-16 14:06
I have force pushed the dev branch for CI build tests again. Currently tvOS and Android still broken. The former was probably due to tvOS simulator build failure caused by Metal. I have not started any integration work with Android platform yet, running out of my free time. The Web build, iOS and others seem to build OK. However, there may still be other issues lurking during runtime. The branch is still not ready for public testing, but having said that, any test reports are welcome.

**Comment by weitjong** [comment] 2019-06-19 16:04
As the latest EMSDK (emcc 1.38.34) now works with the `upgrade-sdl` dev branch, I am closing this issue for now. Further update on the SDL upgrade will be tracked on #2324 instead.

**Closed by weitjong** 2019-06-19 16:04 UTC
Labels: build system
