### ISSUE TITLE
Urho3DPlayer Web Sample fails on Firefox 50.1.0

### ISSUE THREAD

**Issue by KonstantinTomashevich** [urho3d/Urho3D#1747] opened 2017-01-04 17:13 UTC
Urho3DPlayer Web Sample fails on Firefox 50.1.0.
[See web sample page.](https://urho3d.github.io/samples/Urho3DPlayer.html)
Log from JS console:
```
loading /home/travis/build/urho3d/Build/bin/Urho3D.js.data from remote  Urho3DPlayer.js:1:7313
[Wed Jan  4 20:01:30 2017] INFO: Opened log file Urho3D.log  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:30 2017] INFO: Added resource package Data.pak  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:30 2017] INFO: Added resource package CoreData.pak  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Set screen mode 1024x768 windowed  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Initialized input  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Initialized user interface  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Initialized renderer  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] WARNING: Could not get application preferences directory  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Set audio mode 48000 Hz stereo interpolated  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Initialized engine  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:292,16 Identifier 'Connection' is not a data type in global namespace  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:320,18 Identifier 'Connection' is not a data type in global namespace  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar/Player.as:6,5 Identifier 'Connection' is not a data type in global namespace  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:62,1 Compiling void Start()  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:90,9 No matching signatures to 'StartGame(<null handle>)'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:90,9 Candidates are:  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:90,9 void StartGame(int connection)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:168,1 Compiling void InitNetworking()  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:170,5 'network' is not declared  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:172,12 Illegal operation on 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:173,12 Illegal operation on 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:174,12 Illegal operation on 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:175,12 Illegal operation on 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:179,16 Illegal operation on 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:192,16 'updateFps' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:193,16 Illegal operation on 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:320,1 Compiling void SpawnPlayer(int)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:330,15 'owner' is not a member of 'Node'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:338,20 Both operands must be handles when comparing identity  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:341,69 'controls' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:347,35 Both operands must be handles when comparing identity  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:361,24 Both operands must be handles when comparing identity  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:363,51 'identity' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:381,20 Both operands must be handles when comparing identity  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:388,19 Illegal operation on 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:568,1 Compiling void HandleClientIdentity(StringHash, VariantMap&inout)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:570,5 Identifier 'Connection' is not a data type  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:578,1 Compiling void HandleClientSceneLoaded(StringHash, VariantMap&inout)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:581,5 Identifier 'Connection' is not a data type  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:588,1 Compiling void HandleClientDisconnected(StringHash, VariantMap&inout)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:590,5 Identifier 'Connection' is not a data type  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:652,1 Compiling void HandleNetworkUpdateSent()  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:655,9 'network' is not declared  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:656,16 'serverConnection' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:726,1 Compiling void SendScore(int)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:733,36 Illegal operation on 'int&'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:736,1 Compiling void SendHiscores(int)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:753,40 Illegal operation on 'int&'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:755,9 'network' is not declared  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:860,1 Compiling void CheckEndAndRestart()  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:877,9 No matching signatures to 'StartGame(<null handle>)'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:877,9 Candidates are:  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:877,9 void StartGame(int connection)  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] INFO: Scripts/NinjaSnowWar.as:880,1 Compiling void UpdateControls()  Urho3DPlayer.html:1242:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:993,18 'network' is not declared  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:996,20 'serverConnection' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:997,20 'serverConnection' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:998,20 'serverConnection' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:1001,20 'serverConnection' is not a member of 'int'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:1014,61 'controls' is not a member of 'int&'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:1019,42 'controls' is not a member of 'int&'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Scripts/NinjaSnowWar.as:1022,60 'controls' is not a member of 'int&'  Urho3DPlayer.html:1254:13
[Wed Jan  4 20:01:39 2017] ERROR: Failed to compile script module Scripts/NinjaSnowWar.as
```
It seems that NinjaShowWar can't be compiled because network classes isn't supported on web build. Maybe remove this sample from web samples page?

**Comment by weitjong** [comment] 2017-01-05 01:33
That may be so. However, there is nothing wrong with Urho3DPlayer itself. It can be invoked with other scripts (AS and Lua) as parameter, defaulted to NinjaSnowWar when none provided. Perhaps, instead, we should enhance the web sample page to allow it to choose the script to run, similar to Android sample launcher, and hide the NinjaSnowWar.as from the list.

**Comment by cadaver** [comment] 2017-01-05 07:36
@weitjong That sounds good. Even simpler and uglier alternative would be to just choose another example if URHO3D_NETWORK is not defined, overriding the default CommandLine.txt, but a chooser is certainly better.

**Comment by KonstantinTomashevich** [comment] 2017-01-05 18:48
Yes, special chooser script will be very good.

**Comment by weitjong** [comment] 2017-01-06 01:14
Probably I can come up with a rudimentary chooser using HTML5 + Javascript/Typescript when I have time. No promise.

**Comment by weitjong** [comment] 2017-01-07 18:33
There is a slight complication, see #1287. Our web samples are hosted in GitHub Pages and by that it means we are using static web site which does not able to parse request query parameter. So, the solution won't be as easy as passing the script name as query parameter back to the server. I will see whether I can hack my way in from the client side.

**Comment by weitjong** [comment] 2017-01-08 16:34
Something is weird. In my test when the link on the web site contains request parameter then upon clicking on the link, the browser URL will also have that request parameter. So, it really does not matter if our website is static or not. Also, we bundle all the scripts inside a single data pak anyway, so the player should be to access the required script on the client side without the help from the server side.

It seems that the Urho3DPlayer.js + Urho3DPlayer.html.mem that I generated locally works as expected in my locally deployed Jekyll server. I am using EMCC 1.36.0 (the same as version as Travis CI). Still not sure why the player generated by Travis does not work.

Will attempt to upload my version to gh-pages for quick test shortly.

**Comment by cadaver** [comment] 2017-01-09 08:39
Urho3DPlayer samples at https://urho3d.github.io/web-samples.html work fine for me. Thanks for the work!

**Comment by KonstantinTomashevich** [comment] 2017-01-12 13:04
Unfortunately, It doesn't work on my Firefox.

**Comment by cadaver** [comment] 2017-01-12 14:29
Hmm, did I break something when I refactored support for optional late opening of CommandLine.txt from resources on all platforms? At which point are the query parameters stuffed into Emscripten's Module.arguments?

(now it isn't working for me locally either)

**Comment by weitjong** [comment] 2017-01-12 16:04
For me, the latest master branch is working for me locally. The code is fine. However, if you read carefully my past comment, you see that there is totally another separate issue that causing the artifacts generated by Travis CI to be defective. While my locally generated artifacts appear to be OK. I haven't got time though to investigate that further. Tight schedule at my day job.

Make sure you clear your browser cache before testing. The cache could be the reason why you seeing thing.

**Comment by cadaver** [comment] 2017-01-12 16:11
Thanks for the answer. Will check cache.

**Comment by weitjong** [comment] 2017-01-14 04:59
I tried to reproduce the Travis-CI build environment locally including resetting up the Emscripten SDK using the instruction found in .travis.yml, although I have the SDK already. However, the GitHub cloning speed is so slow today. It seems it may take the whole day just to pull all the bits down despite I have a fiber-optic connection. :smiley:

**Comment by weitjong** [comment] 2017-01-14 09:23
I am very close to closing this issue now. I was not able to reproduce the issue using my local Travic-CI-alike build environment. I have a new theory why this is happening. Pushing a few more commits to prove my theory.

**Comment by KonstantinTomashevich** [comment] 2017-01-14 09:40
At the moment, all both lua and angelscript web samples work fine for. Thanks for the work!

**Comment by weitjong** [comment] 2017-01-14 09:44
Thanks for testing them. Those are new artifacts from latest commit. Having said that, I will leave this issue as open because we haven't fixed the root cause of the issue, i.e. the artifacts in the binary package tarball remains to be damaged at this moment.

**Comment by weitjong** [comment] 2017-01-14 13:46
I just tested the binary package newly generated by my local build environment using script from the latest HEAD and I also couldn't reproduce the issue anymore. Whatever it was that causing the original issue seems to be gone. Don't ask me how, I just changed the rake task execution order. :smiley:. Closing this issue now.

**Comment by weitjong** [comment] 2017-03-04 16:59
The issue reappears again.

**Comment by ipud2** [comment] 2017-03-04 17:01
Support C# binding???

**Comment by cadaver** [comment] 2017-03-04 17:07
C# is out of scope for the Urho3D core project (and offtopic to this issue). Look for UrhoSharp.

**Comment by weitjong** [comment] 2017-03-04 17:09
And again, it is not reproducible locally. Whatever it is, it only happened when the artifacts were generated from Travis CI.

**Comment by weitjong** [comment] 2017-03-04 18:15
It is fixed again mysteriously. The last commit (license clarification) should not, in theory, produced so many object changes, but yet it did and some how it is the "working" version being uploaded this time. I will leave this issue as open.

**Comment by weitjong** [comment] 2017-03-19 13:00
Finally I am able to reproduced this locally and understand what it is the root cause.

**Closed** 2017-03-19 13:03 UTC
Labels: bug, build system
