### ISSUE TITLE
Multithreaded compilation for Visual Studio

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1407] opened 2016-06-06 19:50 UTC
Visual Studio is able to compile code in several threads.
Unfortunately, VS by default uses only one thread.
Unfortunately x2, it is needed to manually enable this flag for each project.
To enable this feature it is needed to add compiler option '/MP' for each source file.
Can you enable multithreaded compilation for Visual Studio?
Or can you at least tell me where should I add this option to set it globally?

**Comment by weitjong** [comment] 2016-06-07 03:16
Looks like a duplicate of #1304 discussion.

**Comment by eugeneko** [comment] 2016-10-16 17:00
I reopened this issue because I still think that /MP flag shall be enabled by default.
> As for the /MP compiler flag, I have no idea how it differs from msbuild /maxcpucount option.
MSBuild option is for parallel project build, /MP is for parallel file compilation.
I have just compared rebuild only Urho excluding samples and dependencies:
2:22 vs 1:01

**Closed** 2017-07-23 10:49 UTC
Labels: duplicate
