### ISSUE TITLE
Windows7+codeblocks+(mingw64 or tdm gcc 5.1) failed.

### ISSUE THREAD

**Issue by guijun** [urho3d/Urho3D#789] opened 2015-07-20 02:50 UTC
..\cmake_codeblocks.bat  .\  -DMINGW_PREFIX=c:\msys64\mingw64\bin\x86_64-w64-mingw32- -DWIN32=1 -DURHO3D_OPENGL=1 -DURHO3D_LUAJIT=1

error:
||=== Build: Urho3DPlayer in Urho3D (compiler: GNU GCC Compiler) ===|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|69|error: 'sockaddr_in' does not name a type|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|89|error: 'sockaddr_in' does not name a type|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|78|error: request for member 'sin_addr' in 'addr', which is of non-class type 'const int'|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|79|error: request for member 'sin_addr' in 'addr', which is of non-class type 'const int'|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|80|error: request for member 'sin_addr' in 'addr', which is of non-class type 'const int'|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|81|error: request for member 'sin_addr' in 'addr', which is of non-class type 'const int'|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|83|error: request for member 'sin_port' in 'addr', which is of non-class type 'const int'|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\EndPoint.h|83|error: 'ntohs' was not declared in this scope|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\Socket.h|123|error: 'sockaddr_in' does not name a type|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\Socket.h|124|error: 'socklen_t' does not name a type|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\Socket.h|133|error: expected ')' before 'connection'|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\Socket.h|283|error: 'SOCKET' does not name a type|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\Socket.h|294|error: 'SOCKET' does not name a type|
D:\MyWork\ude4\kmc\Source\ThirdParty\kNet\include\kNet\Socket.h|312|error: 'sockaddr_in' does not name a type|
Source\ThirdParty\kNet\CMakeFiles\kNet.dir\build.make|150|recipe for target 'Source/ThirdParty/kNet/CMakeFiles/kNet.dir/src/FragmentedTransferManager.cpp.obj' failed|
CMakeFiles\Makefile2|1062|recipe for target 'Source/ThirdParty/kNet/CMakeFiles/kNet.dir/all' failed|
CMakeFiles\Makefile2|2042|recipe for target 'Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/rule' failed|
D:\MyWork\ude4\kmc\build_windows\Source\Tools\Urho3DPlayer\Makefile|166|recipe for target 'Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/rule' failed|
||=== Build failed: 18 error(s), 0 warning(s) (0 minute(s), 8 second(s)) ===|

I noticed following code didn't work:
#ifdef WIN32
 there should be an error here. 
#endif

**Comment by guijun** [comment] 2015-07-20 03:13
following modification seems to work:
#if defined ( __MINGW32__ ) || defined ( __MINGW64__ )
    #define WIN32
#endif // defined

I'm wondering if this is the correct fix.

**Comment by guijun** [comment] 2015-07-20 06:10
I had updated to tdm gcc 5.1 
g++ (tdm64-1) 5.1.0.

WIN32 isn't defined either if I try to compile it in codeblocks.

I confirmed that g++ has WIN32 defined from ci or codeblocks. please checkout source below
:
#include <iostream>

using namespace std;

int main()
{
    #ifdef WIN32
        cout<<"WIN32"<<endl;
    #endif // WIN32
    #ifdef WIN64
        cout<<"WIN64"<<endl;
    #endif // WIN64
    cout << "Hello world!" << endl;
    return 0;
}

**Comment by weitjong** [comment] 2015-07-20 09:38
This is interesting. The "WIN32" should be defined by the MinGW compiler toolchain. If it is not then it is a bug on the compiler itself. I have recently upgraded to Fedora 22 which comes with GCC 5.1 and this is what I got.

```
$ /usr/lib64/ccache/x86_64-w64-mingw32-g++ --version
x86_64-w64-mingw32-g++ (GCC) 5.1.0 20150422 (Fedora MinGW 5.1.0-2.fc22)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ echo |/usr/lib64/ccache/x86_64-w64-mingw32-g++ -dM -E - |grep WIN32
#define _WIN32 1
#define __WIN32 1
#define __WIN32__ 1
#define WIN32 1
```

No problem here.

On my Win7 VM, I have an older MinGW-W64.

```
C:\Users\weitjong>"C:/Program Files/mingw-w64/x86_64-4.9.1-posix-seh-rt_v3-rev0/mingw64/bin/g++.exe" --version
g++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
C:\Users\weitjong>echo |"C:/Program Files/mingw-w64/x86_64-4.9.1-posix-seh-rt_v3-rev0/mingw64/bin/g++.exe" -dM -E - >macro.out
C:\Users\weitjong>for /F "tokens=1-2" %i in (macro.out) do @echo WIN32 |findstr %j >nul && @echo %i %j
#define WIN32
```

There is no problem there too.

I do not have  TDM or C::B on my Win7 VM, so I could not reproduce your issue myself. But I understand C::B installation on Windows ships with its own compiler toolchain (TDM-GCC). We have received reports from our users having problem with TDM-GCC before. So, make sure you have configured your C::B to use the other standalone toolchain you have installed on your host system.

Alternatively, you can perform the similar test that I have showed you above to see whether your MinGW toolchain defines the WIN32 as expected or not. If not then file a bug to them.

**Comment by weitjong** [comment] 2015-07-28 06:59
Closing this for now. Feel free to reopen this issue again if you have more information to update.

**Closed by weitjong** 2015-07-28 06:59 UTC
