### ISSUE TITLE
cAmbientColor.a not taken in account on DX11

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1490] opened 2016-07-25 19:19 UTC
While testing new PBR implementation i found that changing zone ambient alpha color has not effect in IBL.hlsl shader (where cAmbientColor.a) is used so it seem that there is something wrong cAmbientColor uniform  on DX11.

**Comment by dragonCASTjosh** [comment] 2016-07-25 23:15
Hmmm, I'm not getting the issue my end is anyone else affected by the issue

**Comment by dragonCASTjosh** [comment] 2016-07-25 23:19
If it wasn't working you would likely see shader compile errors. What values are you trying to set it to, I believe it was clamped to a max of 5 I'll have to check when i have a moment

**Comment by cadaver** [comment] 2016-07-27 11:57
Can't reproduce in master branch. For me, changing PBR example scene's zone ambient color alpha (in the editor) has a similar effect on the scene IBL lighting, both OpenGL & D3D11.

**Comment by cadaver** [comment] 2016-07-29 13:50
If you were using Zone::SetAmbientColor() it would force the a component to 1, forcing you to use generic attribute access to actually be able to set the alpha. This is fixed now.

**Closed by cadaver** 2016-07-29 13:50 UTC
