### ISSUE TITLE
html help compiler runs, but gives error saying it failed

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#910] opened 2015-09-28 20:22 UTC
Docs build otherwise, but I get the following error:
69>CUSTOMBUILD : error : failed to run html help compiler on index.hhp

build\Urho3D\Docs\Doxyfile contains:
HHC_LOCATION           = "C:/Program Files (x86)/HTML Help Workshop/hhc.exe"

This is correct, it actually exists on my machine.  It was substituted from CMake HTML_HELP_COMPILER variable.  I notice however that I have HTML_HELP_INCLUDE_PATH-NOTFOUND and HTML_HELP_LIBRARY-NOTFOUND.

System is Windows 10 64-bit, Visual Studio 2015 Community Edition, Windows 10 SDK.  CMake version 3.2.3, generator is VS 2015 64-bit.

**Comment by weitjong** [comment] 2015-09-29 11:52
I did not have hhc.exe installed on my Win7 VM before because I could not find a legitimate download source for this tool previously. Today I got lucky and found this link, so I install it. https://msdn.microsoft.com/en-us/library/windows/desktop/ms669985(v=vs.85).aspx

I got the version 1.3 installed and run the 'rake make target=doc' on a terminal and I got lucky again. All the three variables you mentioned above are properly initialized by CMake. The *.chm is generated. After double-clicking it, I can see most of the content are in there but with notably a few links being disabled. I have no idea why though but I don't have time to investigate it further.

**Comment by bvanevery** [comment] 2015-09-29 19:30
"C:\Program Files (x86)\HTML Help Workshop" exists on 2 of my Windows 10 machines that have Visual Studio 2015 installed.  I'm not sure if Windows 10 or Visual Studio 2015 was responsible for that.  On those 2 machines, include and lib directories do not exist.  Only a hhc.exe binary has been installed.

On a Windows 8.1 machine without any development environment, no HTML Help Workshop directory existed.

On a Windows 7 machine I had found and installed the same HTML Help Workshop that you did.  The installer binary was still sitting in my download directory and it is the same as the one from the link you gave. File version 4.71.1015.0, Product version 4.74.8703.  The installation provides include, lib, java, and redist subdirectories, as well as a lot of .dlls in the top level directory.  The include merely contains htmlhelp.h, the lib merely htmlhelp.lib.  CMake picks up the binary, include and lib directories no problem.  However the build still fails in the same way as before.

Identifying the version of hhc.exe hasn't been easy.  I can't find any command line documentation and it doesn't spit out anything sane adding a /? option for instance.  The internet is surprisingly quiet on the subject, and the MS documentation similarly useless.  Right clicking on the file's Properties is the only method I've come up with.  For the Windows 7 installation, under Details I see File version 4.74.8702.0, Product version 4.74.8702.  Under Windows 10 exactly the same version is given.

Since we are using exactly the same tool, the mystery is why does it work for you and not for me?

**Comment by weitjong** [comment] 2015-09-30 10:15
> Since we are using exactly the same tool, the mystery is why does it work for you and not for me?

You did not specifically said what did not work for you this time. If you are using the latest master branch with latest patch then I think I can safely assume it is not caused by HHC.exe but further up in the doc build processes. In one of my comments in another issue raised by you, I already mentioned and asked you about the MKLINK setup. This could be one of the thing that threw you off. Another possible reason could be you were building a shared Urho3D lib type and the Urho3D.dll or Urho3D_d.dll is not copied/symlinked correctly to your bin/tool directory. There are the two things I can think of right now. Incidentally I am working on yet another patch to fix how the DLL should be copied/installed for the tools. After this patch is in then you can rule this one out.

**Comment by bvanevery** [comment] 2015-09-30 15:03
The error behavior as given in my 1st comment is unchanged.  It is true regardless of whether hhc.exe was installed by Visual Studio 2015 or by a standalone HTML Help installer.  It doesn't matter whether CMake include or lib directory variables are set.  This is from full builds of the entire Urho3D.sln and all docs, not any subproject in isolation.  I only test the isolation case in the comments for that specific issue #908. URHO3D_LIB_TYPE=STATIC, it's the default, I've never changed it.   

Will build clean and look for bin\tools\Urho3d.dll presence in a few minutes.

**Comment by weitjong** [comment] 2015-09-30 15:25
If you use STATIC then the Urho3D.dll will not be generated and so it also will not be copied to bin/tool directory. You should still get one DLL copied there, however. It is the Direct3D DLL. So check if this DLL is there and it got the right version.

**Comment by bvanevery** [comment] 2015-09-30 15:35
Noticed a message in CMake configuration I hadn't before.
`Could NOT find HTMLHelp (missing:  HTML_HELP_INCLUDE_PATH HTML_HELP_LIBRARY) `
Urho3D\Docs\CMakeLists.txt controls this:
`        if (MSVC_HELP)
            find_package (HTMLHelp)
            find_package_handle_standard_args (HTMLHelp REQUIRED_VARS HTML_HELP_COMPILER HTML_HELP_INCLUDE_PATH HTML_HELP_LIBRARY)
            if (NOT HTMLHelp_FOUND)     # Only consider it as found when all the required variables are found
                unset (HTML_HELP_COMPILER)
            endif ()
        endif ()`
Are htmlhelp.h and htmlhelp.lib strictly required to compile HTML Help?  If yes, then this should be an error when URHO3D_DOCS is set.  Also, MSVC_HELP should be set to 0, as it is substituted into Doxyfile.in.  If no, then the unneeded stuff should be removed from the list of required variables.

**Comment by weitjong** [comment] 2015-09-30 15:46
I added exactly because after reading your issue. In my case I have all the three vars initialized and Doxygen triggers hhc.exe correctly. In your case since it has failed, I figure they are all required. As such, I switch the hhc off when not all the vars are found. As for the MSVC_HELP, I still leave it on as I think it instructs Doxygen to still generate the index.hhp. Just in case user can find other way to double-click it to launch the newer version of the help compiler or something like that.

**Comment by bvanevery** [comment] 2015-09-30 16:11
I checked the Windows 7 machine that already had htmlhelp.h and htmlhelp.lib installed.  Do you mean D3DCompiler_47.dll ?  One of those is copied to bin\tools.  I say "one of those" because it's from the 8.1 SDK per issue #911, not the 10.0 SDK that Visual Studio 2015 is using on that Windows 7 system.  They are not the same file, their sizes are different.  The one put in bin\tools from the 8.1 SDK is Product version 6.3.9600.16384.  The Windows 10 one has Product version 10.0.10240.16384.  So the question is, is that needed to build compiled help, and can a mismatch screw it up?

**Comment by weitjong** [comment] 2015-09-30 16:19
I mentioned D3DCompiler_47.dll earlier because I thought you had problem in the build process further up like problem in executing ScriptCompiler.exe. If the DLL get mixed up then ScriptCompiler won't run properly I suppose, but it should have no baring on failure of Doxygen executing hhc.exe.

**Comment by bvanevery** [comment] 2015-09-30 16:25
Per 1st comment, "docs build otherwise, but I get the following error".  Just this one hhc.exe problem.  I've got html files galore.

**Comment by bvanevery** [comment] 2015-09-30 16:32
Since I've sanity checked my tools versions pretty thoroughly, I need to reexamine the assumption, "we are using the same hhc.exe tool."  weitjong you seem to be in possession of a setup that works.  Can you please tell me what your value for HTML_HELP_COMPILER is?  And then, right clicking on that file, under Details what is its Product version?

**Comment by weitjong** [comment] 2015-09-30 16:48
HHC_LOCATION = "C:/Program Files (x86)/HTML Help Workshop/hhc.exe"
Production version: 4.74.8702

**Comment by bvanevery** [comment] 2015-09-30 17:02
I've got 4.74.8702 as well on 3 machines.  So it isn't hhc.exe.  Checked itc.dll and hha.dll also, versions match on all 3 machines.  Feels like barking up the wrong tree.

**Comment by weitjong** [comment] 2015-09-30 17:34
It's 64 bit. Try run the tool manually and see if it works.

**Comment by bvanevery** [comment] 2015-09-30 18:52
Ok now I'm really baffled.  Urho3D_Documentation_1.4.580.chm exists.  Nevertheless, here are the errors given by Visual Studio 2015:

72>  C:/Users/bvanevery/devel/Urho3D/Docs/Reference.dox:3053: warning: multiple use of section label 'FileFormats_Shader' while adding section, (first occurrence: C:/Users/bvanevery/devel/Urho3D/Docs/Reference.dox, line 3028)
72>CUSTOMBUILD : warning : Call graph for 'Urho3D::Connection::ProcessExistingNode' not generated, too many nodes. Consider increasing DOT_GRAPH_MAX_NODES.
72>CUSTOMBUILD : error : failed to run html help compiler on index.hhp
77>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
77>  Building Custom Rule C:/Users/bvanevery/devel/Urho3D/CMakeLists.txt
77>  CMake does not need to re-run because C:\Users\bvanevery\devel\build\Urho3D\CMakeFiles\generate.stamp is up-to-date.
78>------ Skipped Build: Project: PACKAGE, Configuration: Release x64 ------
78>Project not selected to build for this solution configuration 
79>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
79>Project not selected to build for this solution configuration 
========== Build: 75 succeeded, 1 failed, 0 up-to-date, 3 skipped ==========

Could this be as simple as CUSTOMBUILD failing to interpret an output code properly?

**Comment by bvanevery** [comment] 2015-09-30 19:30
Way waaaay back at the beginning of the doc build, thousands of lines ago, there are actually some meaty looking tuloa errors.  Could these errors be being saved for the entire doc process, thereby triggering error / failed as the final result?  I don't see any other explicit errors, only warnings.

3>------ Build started: Project: doc, Configuration: Release x64 ------
2>  luajit_interpreter.vcxproj -> C:\Users\bvanevery\devel\build\Urho3D\bin\luajit.exe
3>  Building Custom Rule C:/Users/bvanevery/devel/Urho3D/Docs/CMakeLists.txt
3>  CMake does not need to re-run because C:\Users\bvanevery\devel\build\Urho3D\Docs\CMakeFiles\generate.stamp is up-to-date.
3>  Dumping AngelScript API to ScriptAPI.dox
3>  [Wed Sep 30 15:15:07 2015] INFO: Initialized engine
3>  Dumping LuaScript API to LuaScriptAPI.dox
3>  The filename, directory name, or volume label syntax is incorrect.
3>  ***curr code for error is tolua_property__get_set float dampingRatio;
3>
3>  stack traceback:
3>  	[string "tolua embedded: lua/basic.lua"]:57: in function 'tolua_error'
3>  	[string "tolua: embedded Lua code 23"]:5: in main chunk
3>
3>CUSTOMBUILD : ** tolua internal error : [string "ToDoxHook.lua"]:220: attempt to index local 'tmpHandler' (a nil value).
3>
3>
3>  stack traceback:
3>  	[string "tolua: embedded Lua code 23"]:6: in main chunk
3>  Generating documentation with Doxygen
3>  Searching for include files...
[things look fine for thousands of lines after this]

**Comment by weitjong** [comment] 2015-10-01 07:21
> 72> C:/Users/bvanevery/devel/Urho3D/Docs/Reference.dox:3053: warning: multiple use of section label 'FileFormats_Shader' while adding section, (first occurrence: C:/Users/bvanevery/devel/Urho3D/Docs/Reference.dox, line 3028)
72>CUSTOMBUILD : warning : Call graph for 'Urho3D::Connection::ProcessExistingNode' not generated, too many nodes. Consider increasing DOT_GRAPH_MAX_NODES.

The first warning is new to me. The new section for SM4 was added probably at the time D3D11 development and got the duplicate label due to copy paste. The label will be fixed in a next commit.
The second warning though was already there as long as we have started to use dot in our doc build.

> Could this be as simple as CUSTOMBUILD failing to interpret an output code properly?

No. I already explained before that our build system relies on the exit status of a process to determine whether it has succeed or failed. It usually does not care what the content of the standard output or even error streams might be. Only in a rare case where an ill-written program/tool does not know how to return proper exit status then we are forced to add special logic to interpret the stdout/stderr. If you look at the CMakeLists.txt for the doc target, you know it is not the case here. The target success or failure are solely based on the exit status of its constituents.

It has been awhile since I last do VS build using the IDE itself but I did it just now to see what happens. Here are last few lines of my logs. I know it does not help you much but at least it shows you how a successful log should look like.
```
72>  Generating dependency graph for directory c:/Users
72>  Generating dependency graph for directory c:/Users/weitjong
72>  Generating index page...
72>  Generating page index...
72>  Generating module index...
72>  Generating namespace index...
72>  Generating namespace member index...
72>  Generating annotated compound index...
72>  Generating alphabetical compound index...
72>  Generating hierarchical class index...
72>  Generating graphical class hierarchy...
72>  Generating member index...
72>  Generating file index...
72>  Generating file member index...
72>  Generating example index...
72>  finalizing index lists...
72>  Running dot...
72>  Running html help compiler...
72>  lookup cache used 27498/65536 hits=269967 misses=30467
72>  finished...
77>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
77>  Building Custom Rule c:/Users/weitjong/ClionProjects/urho3d/Urho3D/CMakeLists.txt
77>  CMake does not need to re-run because C:\Users\weitjong\ClionProjects\urho3d\native-Build\CMakeFiles\generate.stamp is up-to-date.
78>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
78>Project not selected to build for this solution configuration 
79>------ Skipped Build: Project: PACKAGE, Configuration: Debug x64 ------
79>Project not selected to build for this solution configuration 
========== Build: 77 succeeded, 0 failed, 1 up-to-date, 2 skipped ==========
```

**Comment by bvanevery** [comment] 2015-10-01 14:37
I am have always built with URHO3D_D3D11.  Do you?  Maybe I expose a problem because some build option of mine is different from yours.  Rather than try such things one by one, can you attach your CMakeCache.txt from your successful run?

**Comment by bvanevery** [comment] 2015-10-01 18:10
I changed the title to correctly reflect what is now known.  It also installs the .chm just fine.  So it is a mystery if this error is of great consequence, other than confusing the heck out of a new user.  Which shouldn't be underestimated.  The .chm was buried under piles and piles of .html in the directory, and it's alphabetically last, so it took me a very long time to discover I even had it.  Not sure what to do about this.  If the error could be specifically detected, then message "ignore this" could be given, but I don't presently know how to detect it.

**Comment by weitjong** [comment] 2015-10-02 11:20
I doubt the actual build options used in the build tree has anything to do with this. With the *.chm correctly generated despite the error message or exit status given back by Doxigen then problem is clear to me to be resided on the Doxygen and/or HHC side instead of on our side. In my earlier comment I have asked you to specifically check the tool itself but you did not respond to that. If I were you then I would first try to isolate the problem. Call the HHC.exe with the generated index file to see if it works. Call the Doxygen with the generated Doxyfile to see if it works, etc. I have tried to help you but you have to listen on the advise given.

With your new revelation that the *.chm was actually generated despite the error and despite the missing include and lib were not present, I will now revert a change that I made earlier which was based on mislead information. Thus, the help compiler will now again be considered as found regardless the other vars. I have tested this in my VM by intentionally removing the include and lib dirs, the doc build still work fine in my test.

As I am quite sure this issue is not due to our build system setup for the doc target, but external to the tool(s) being installed, I am closing this issue for now. You are still able to post comments on this issue if you have more information to share or reopen the issue if you find evidence that problem is indeed resided on our side.

**Closed by weitjong** 2015-10-02 11:20 UTC

**Comment by bvanevery** [comment] 2015-10-02 17:48
The error is present on 3 different machines that I configured.  Generally speaking they all build Urho3D.  They are not "bad" build environments, they are what a Windows user would likely have.  I have built an awful lot of runs clean and out of source, they're not stale builds.

I would still like a copy of your CMakeCache.txt from your error free run.  Maybe I am building with Lua options that you're not, or some other such subtlety.  Meanwhile I will try a build that sets URHO3D_DOCS and nothing else, to see if the error magically goes away.

I am wondering if our versions of Doxygen are different.  "doxygen -v" says mine is 1.8.10.

I added hhc.exe to my PATH on one of my machines and ran it as follows on index.hhc.  No errors st all.

C:\Users\BVANEVRY\devel\build\Urho3D\Docs\html>hhc index.hhp
Microsoft HTML Help Compiler 4.74.8702

Compiling c:\Users\BVANEVRY\devel\build\Urho3D\Docs\html\Urho3D_Documentation_1.
4.588.chm


Compile time: 4 minutes, 14 seconds
11,617  Topics
222,732 Local links
1,050   Internet links
0       Graphics


Created c:\Users\BVANEVRY\devel\build\Urho3D\Docs\html\Urho3D_Documentation_1.4.
588.chm, 47,567,624 bytes
Compression decreased file by 49,691,886 bytes.

C:\Users\BVANEVRY\devel\build\Urho3D\Docs\html>

**Comment by bvanevery** [comment] 2015-10-02 18:31
Selecting Visual Studio 2015 generator 64-bit, URHO3D_64BIT, URHO3D_DOCS, and no other options, the error is still present.  This time I'm including more context as there are a number of warnings that don't seem to be present in your own successful run.  The warnings are part of why I think we may not be using the same Doxygen.  Mine is the latest, dated June 27, 2015.

On the positive side I don't see any Lua errors, but as I didn't say to build Lua, it may not be much exercised.

```
28>CUSTOMBUILD : warning : Tag `SYMBOL_CACHE_SIZE' at line 346 of file `generated/Doxyfile' has become obsolete.
28>           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
28>CUSTOMBUILD : warning : Tag `XML_SCHEMA' at line 1415 of file `generated/Doxyfile' has become obsolete.
28>           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
28>CUSTOMBUILD : warning : Tag `XML_DTD' at line 1421 of file `generated/Doxyfile' has become obsolete.
28>           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
28>CUSTOMBUILD : warning : doxygen no longer ships with the FreeSans font.
28>  You may want to clear or change DOT_FONTNAME.
28>  Otherwise you run the risk that the wrong font is being used for dot generated graphs.
28>CUSTOMBUILD : warning : Call graph for 'Urho3D::Connection::ProcessExistingNode' not generated, too many nodes. Consider increasing DOT_GRAPH_MAX_NODES.
28>CUSTOMBUILD : error : failed to run html help compiler on index.hhp
31>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
31>  Building Custom Rule C:/Users/BVANEVRY/devel/Urho3D/CMakeLists.txt
31>  CMake does not need to re-run because C:\Users\BVANEVRY\devel\build\Urho3Ddocs\CMakeFiles\generate.stamp is up-to-date.
32>------ Skipped Build: Project: PACKAGE, Configuration: Debug x64 ------
32>Project not selected to build for this solution configuration 
33>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
33>Project not selected to build for this solution configuration 
========== Build: 30 succeeded, 1 failed, 0 up-to-date, 2 skipped ==========
```

**Comment by bvanevery** [comment] 2015-10-02 18:56
Found someone observing the same Doxygen behavior in an unknown project (probably not Urho3D).  http://sourceforge.net/p/doxygen/discussion/130994/thread/95da5a02/  
```
Since I update doxygen to 1.8.9, I get an error message at the end of the chm generation:

    error: failed to run html help compiler on index.hhp

and of course, the CHM file is well generated.
I tried with an older version (1.7.4) and with the same project, I have some doxygen warning (expected due to new features) but no message of any html help compiler failure.

I'm working on Windows, and HHC is exiting with errorlevel = 1 when everything is OK.
```

**Comment by bvanevery** [comment] 2015-10-02 19:34
Ok, I've finally proven it's totally down to hhc.exe, nothing else.  The trick is to look at the %ERRORLEVEL% after it runs.  It returns "1" despite success.  This could be used in a custom command to warn the user it's spurious, if the hhc.exe run is isolated from other stuff.  However if Doxygen is driving it, I don't think there's a way to know that.  Doxygen's behavior regarding hhc.exe seems to have changed in recent versions.  I'll take it up with them.   A CMake-only workaround might be to detect any Doxygen error, then test to see if the .chm was actually generated.  If it was, advise the user that the error is probably spurious.
```
C:\Users\BVANEVRY\devel\build\Urho3D\Docs\html>doxygen -v
1.8.10

C:\Users\BVANEVRY\devel\build\Urho3D\Docs\html>echo %errorlevel%
0

C:\Users\BVANEVRY\devel\build\Urho3D\Docs\html>hhc index.hhp
Microsoft HTML Help Compiler 4.74.8702

Compiling c:\Users\BVANEVRY\devel\build\Urho3D\Docs\html\Urho3D_Documentation_1.
4.588.chm


Compile time: 2 minutes, 3 seconds
11,617  Topics
222,732 Local links
1,050   Internet links
0       Graphics


Created c:\Users\BVANEVRY\devel\build\Urho3D\Docs\html\Urho3D_Documentation_1.4.
588.chm, 47,567,624 bytes
Compression decreased file by 49,691,886 bytes.

C:\Users\BVANEVRY\devel\build\Urho3D\Docs\html>echo %errorlevel%
1

C:\Users\BVANEVRY\devel\build\Urho3D\Docs\html>
```

**Comment by weitjong** [comment] 2015-10-03 01:24
Glad that you now see the same conclusion as I did when I decided to close this issue. It is the faulty external tool that caused this.

**Comment by bvanevery** [comment] 2015-10-03 11:38
I've written a .cmd wrapper for hhc.exe that suppresses the error.  However Doxygen suppresses stdout so my helpful messages go unnoticed.  I will try writing a result file to the current binary directory.
