### ISSUE TITLE
Visual Studio 2017, 64 bit debug build, examples don't work properly

### ISSUE THREAD

**Issue by DavidHoogvorst** [urho3d/Urho3D#2318] opened 2018-05-25 07:33 UTC
Master branch 2482502 downloaded, ran CMake for Visual Studio 15 2017 Win 64, built solution, debug configuration.

For instance, in example 04, StaticScene, keys W/S don't move the camera, but mushrooms disappear/reappear.
When looking around, using the mouse, the screen goes black at some viewing angles.

Screen captures and further details in the forum topic:
https://discourse.urho3d.io/t/problem-going-from-32-to-64-bit-directx-11/4245

**Comment by eugeneko** [comment] 2018-05-25 11:37
I'll check it as soon as I get VS 2017

**Comment by weitjong** [comment] 2018-05-25 11:38
From our point of view, the build system and the code base do not differentiate between VS2015 and VS2017, as far as I am aware. Thus, the build should be configured to use the same compiler flags and compiler defines given a same build config. And since your issue did not manifest itself when using VS2015 or when using VS2017 with Release build config, chances are you have hit one of the VS2017 compiler regressions. I am not a VS user though, so take this with a grain of salt.

**Comment by melonlogic** [comment] 2018-05-26 21:04
@weitjong Have to agree with @DavidHoogvorst on this one, the release builds are doing fine however the debug ones are not. The screen goes black on moving the camera (both with WS and mouse). I'm also using VS 2017, Windows 10, building for Win 64.

**Comment by DavidHoogvorst** [comment] 2018-05-26 21:34
I found the following, perhaps making it easier to find the bug.

If, in example 04, StaticScene, you change the initial camera position in line 124 to:
`cameraNode_->SetPosition(Vector3(0.0f, 5.0f, 16.0083713531494f));`
You’ll see the missing bits in the foreground from the start.

If you change the initial camera position to:
`cameraNode_->SetPosition(Vector3(0.0f, 5.0f, -1.21793007850647f));`
The screen is black from the start. If you move forward (by pressing ‘W’), the scene becomes visible again.

**Comment by weitjong** [comment] 2018-05-27 01:37
Perhaps I was little harsh to label this issue as WONTFIX too quickly. In the past when we found issue with MinGW compiler, we still would tried to find ways to workaround the issue even when it could not be fixed at its root cause. The information I provided in my initial comment is still valid though.

**Comment by eugeneko** [comment] 2018-05-27 08:57
Reproduced! I'm starting working on it.

**Comment by DavidHoogvorst** [comment] 2018-05-27 09:50
@eugeneko : Very good to hear! If I can help, please let me know.

**Comment by melonlogic** [comment] 2018-05-29 23:58
@eugeneko thank you for the update! Looking forward to a VS bug fix. Yeah a bit tacky knowing this is a compiler bug...

**Closed** 2018-06-01 11:12 UTC
Labels: wontfix

**Comment by DavidHoogvorst** [comment] 2018-06-02 11:58
The problem is solved in VS 17.5.3.
