### ISSUE TITLE
Cannot create a new project for MSVC using CMake

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1136] opened 2016-01-05 09:38 UTC
Error when i press Configure
```
The C compiler identification is MSVC 19.0.23026.0
...
CMake Warning at CMake/Modules/Urho3D-CMake-common.cmake:128 (message):
  Could not use MKLINK to setup symbolic links as this Windows user account
  does not have the privilege to do so.  When MKLINK is not available then
  the build system will fallback to use file/directory copy of the library
  headers from source tree to build tree.  In order to prevent stale headers
  being used in the build, this file/directory copy will be redone also as a
  post-build step for each library targets.  This may slow down the build
  unnecessarily or even cause other unforseen issues due to incomplete or
  stale headers in the build tree.  Request your Windows Administrator to
  grant your user account to have privilege to create symlink via MKLINK
  command.  You are NOT advised to use the Administrator account directly to
  generate build tree in all cases.
Call Stack (most recent call first):
  CMakeLists.txt:21 (include)


CMake Error at CMake/Modules/FindUrho3D.cmake:322 (message):
  Could NOT find compatible Urho3D library in Urho3D SDK installation or
  build tree.  Use URHO3D_HOME environment variable or build option to
  specify the location of the non-default SDK installation or build tree.
  Change Dir: D:/MyGames/MiniGame/Build/CMakeFiles/CMakeTmp
```

Cmake found libraries but not detect lib_type

in condition
```
if (URHO3D_INCLUDE_DIRS AND URHO3D_LIBRARIES AND URHO3D_LIB_TYPE AND URHO3D_COMPILE_RESULT)
```
URHO3D_LIB_TYPE == ""
URHO3D_COMPILE_RESULT == false

Maybe the error occurred for a long time. Last time I used an empty VS project to start new project.

**Comment by weitjong** [comment] 2016-01-05 10:32
I beg to differ. We have now also setup scaffolding tests to be executed as part of the normal CI build on AppVeyor. The scaffolding tests are done without passing the URHO3D_LIB_TYPE for the newly created downstream projects. If the error is there then in theory it should be pickup by the CI build.

**Comment by weitjong** [comment] 2016-01-05 13:40
I have time to test this manually on my Windows 10 partition and I was able to cmake-gui to generate the my build tree correctly. Here are the minimalist steps required:

1. Specify the source tree path.
2. Specify the desired build tree path. The path will be created if not exists yet.
3. Click Configure button for the very first time.
4. Choose the desired CMake generator for the build tree.
5. CMake configures process stops half-way due to error (which is expected for cmake-gui because there is no way to pass URHO3D_HOME variable value unlike command line interface cmake).
6. Still, now CMake discovers new variables/build options and displays them in the GUI.
7. Use the GUI to enter the values for the variable. For this minimalist case, just enter the path of the Urho3D project build tree in the URHO3D_HOME variable. You can use the "..." button on the right to browse rather than type in manually.
8. Click Configure button one more time. If the URHO3D_HOME is correct then CMake should be happy already to generate the project build tree.
9. Finally, click Generate button.

With GUI, it is by design you have to click configure many times. Note that some of our build options are dependent on other options and they only reveal themselves when the dependency is met. For example, you don't see URHO3D_LUAJIT_AMALG in the GUI unless URHO3D_LUAJIT is already set. So, you can and have to click configure many times in order to discover them all.

**Comment by 1vanK** [comment] 2016-01-05 14:06
URHO3D_HOME is specifed in env variable

Also i try to  specife URHO3D_HOME in CmakeList.txt
```
SET(ENV{URHO3D_HOME} "d:/MyGames/Urho3D/Build/")
```
Previously it worked. 

I using CMakeList.txt from http://urho3d.github.io/documentation/1.5/_using_library.html and copy CMake dir to my project folter. 

What's my mistake?

**Comment by 1vanK** [comment] 2016-01-05 14:12
Also what compiler you tested?

**Comment by weitjong** [comment] 2016-01-05 14:13
Start from scratch again. Nuke everything. If you have URHO3D_HOME set as env variable as you claimed then the initial configuration CMake should use it. You can verify this by looking at the variable value in the GUI.

I am using VS 2015 but it does not really matter here as you have not even passed that point yet where the chosen compiler matter yet.

**Comment by 1vanK** [comment] 2016-01-05 14:15
> as you have not even passed that point yet where the chosen compiler matter yet.

What?

**Comment by weitjong** [comment] 2016-01-05 14:19
I meant you can encounter this error when URHO3D_HOME is not set correctly regardless of which compiler is being used.

**Comment by 1vanK** [comment] 2016-01-05 14:22
but cmake found Urho3d_d.lib

**Comment by 1vanK** [comment] 2016-01-05 14:31
May be CMakeLists.txt in  http://urho3d.github.io/documentation/1.5/_using_library.html is obsolete?

**Comment by weitjong** [comment] 2016-01-05 14:41
By right, if you are tracking the latest code in the master branch then you should use http://urho3d.github.io/documentation/HEAD/_using_library.html documentation also. We have not made drastic change yet although you are correct to say 1.5 version is now out-dated. The diff would cause the issue you are facing. If you really want me to guess what went wrong, I would say it is because you do not set up mklink to work properly for you Windows account. So, instead of creating symbolic links to ultimate source, you are having soft-copies everywhere that could easily get out-dated as well. Take for the instance, the modules in the Source/CMake directory of your project source tree should contain all the latest code. With symbolic links you can take that for granted but with soft-copies I would first double check that directory.

**Comment by 1vanK** [comment] 2016-01-05 14:46
> I using CMakeList.txt from http://urho3d.github.io/documentation/1.5/_using_library.html and copy CMake dir to my project folter.

**Comment by 1vanK** [comment] 2016-01-05 14:47
I download engine now and rebuild it. And recive same error. What logs do I need to show?

**Comment by 1vanK** [comment] 2016-01-05 14:51
![bug](https://cloud.githubusercontent.com/assets/13021826/12117952/5002d00a-b3dd-11e5-99db-ae3879b9823d.png)

**Comment by 1vanK** [comment] 2016-01-05 14:52
also my options when i compiling engine 
```
Urho3D/cmake_vs2015.bat Build -DURHO3D_OPENGL=ON -DURHO3D_STATIC_RUNTIME=ON -DURHO3D_SAMPLES=OFF -DURHO3D_LUA=OFF
```

**Comment by weitjong** [comment] 2016-01-05 15:19
Can you paste the complete try_run/compile log starting from "Run Build Command" onward to the end. From the list of the build options that you use for the library I don't think it can cause any of this, except URHO3D_STATIC_RUNTIME=ON. Can you rebuild the lib by setting it to off (its default) and see whether you can go further this time.

**Comment by 1vanK** [comment] 2016-01-05 15:32
Without URHO3D_STATIC_RUNTIME=ON same problem
Log:
http://pastebin.com/hRX5a64L

**Comment by weitjong** [comment] 2016-01-05 15:38
You need to set if off explicitly. Simply removing it from the command line does nothing to change the cache value.

**Comment by 1vanK** [comment] 2016-01-05 15:41
I tested only debug version of engine

CMake compiled CheckUrho3DLibrary as Release?

**Comment by 1vanK** [comment] 2016-01-05 15:43
> You need to set if off explicitly. Simply removing it from the command line does nothing to change the cache value.

I remove build dir everytime and restart cmake-gui

**Comment by weitjong** [comment] 2016-01-05 15:44
I have spotted that as well. But I could not explain that. The issue has been reported before in the forum and was already fixed in the latest master branch. Just now when I test I was using Debug configuration also and no problem. I am still have no idea what went wrong on your case. Except may be this is CMake 3.4.1 bug. I think I am using a slightly older version.

**Comment by weitjong** [comment] 2016-01-05 15:49
Either that or you don't have the latest FindUrho3D.module in your source tree.

**Comment by 1vanK** [comment] 2016-01-05 16:13
I build engine as shared lib
Urho3D/cmake_vs2015.bat Build -DURHO3D_OPENGL=ON -DURHO3D_LIB_TYPE=SHARED -DURHO3D_SAMPLES=OFF -DURHO3D_LUA=OFF

and it works normally

**Comment by cadaver** [comment] 2016-01-05 16:35
Started testing this too, since I got trouble with FindUrho3D on VS2013 in the tundra-urho3d project and had to rollback both Windows & Linux to use an earlier Urho version.

For me it seems that using VS2013, building Urho3D as shared (will try static later), setting up a project according to the "Using library" instructions will always produce

CMake Error at CMake/Modules/FindUrho3D.cmake:322 (message):
  Could NOT find compatible Urho3D library in Urho3D SDK installation or
  build tree.  Use URHO3D_HOME environment variable or build option to
  specify the location of the non-default SDK installation or build tree.
  Ensure the specified location contains the Urho3D library of the requested
  library type.

When I had compiled in Urho D3D9 mode, it was clearly trying to run the temp program produced by the FindUrho3D step, as I saw a dialog of missing D3DCompiler dll file (would it be enough to just compile instead of running?) Building in OpenGL mode fixed this, but the library wasn't still found according to FindUrho3D.

**Comment by weitjong** [comment] 2016-01-05 16:36
AppVeyor has currently 4 CI jobs. It tests 32/64-bit STATIC/SHARED combination. It uses Debug build configuration on normal CI build but switch to Release build configuration on CI packaging build. And more importantly all the jobs passed the build test for last couple of commits. I know none of this info helps you to troubleshoot but my point is our build system seems to be working fine, except on your system.

**Comment by 1vanK** [comment] 2016-01-05 16:44
I think in my case when CheckUrho3DLibrary is LINKED it try using Urho3d_d.lib always as dinamic lib

**Comment by weitjong** [comment] 2016-01-05 16:48
@cadaver Not sure I have tried D3D9. But definitely not on VS2013 as I don't have it in my new Win10 partition. We can fallback to use just try_compile for VS, but I think it is easier to fix it by copying the missing DLL over. We do that for Uho3D.dll anyway. The auto-discovery feature uses the output of the run to detect the defines directly. It only fallback to parse the export header and do the discovery indirectly thru the header and not the lib when cross-compiling. Of course, to keep it simple we could just do parsing instead of running it. But that's not the issue here. OP can't pass the compile/linking phase due build configuration mix up for some reason and it doesn't happen on AppVeyor and in my Windows.

**Comment by MonkeyFirst** [comment] 2016-01-05 16:49
well, I have some problems also) the double including lib in release setting:
1. I download last master (few min ago)
2. build project files with cmake-gui (with mklink issue, actually I have admin rights and setup all knowing stuff to allow cmake create an symblylic links, but it still do not create it) 
3. and build it in debug and release
4. create dir for my scratch project (copy into it bin+ cmake + CMakeLists.txt)
5. run cmake again for build project files for VS2013
6. set projects (%name% set as Startup project) then I going into project's property settings and find this:
![222](https://cloud.githubusercontent.com/assets/9577466/12121096/b635317c-b3fd-11e5-8ea0-096edd38a9d9.png)

and I think this produce this issue:
~~~
Urho3D_d.lib(DataDeserializer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in DebugUI.obj
1>Urho3D_d.lib(DataDeserializer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in DebugUI.obj
~~~
if I manually delete this debug lib all work fine. debug version work fine. this issue exist only with release version of project.

**Comment by 1vanK** [comment] 2016-01-05 16:52
> if I manually delete this debug lib all work fine. debug version work fine. this issue exist only with release version of project.

I not compiled release at all :)

**Comment by weitjong** [comment] 2016-01-05 16:59
@MonkeyFirst I don't have VS2013, so I cannot comment on your issue which is btw totally different one. But I can confirm the last time I tested this manually, I don't have problem with both Release and Debug coexist in the build tree using VS2015. And I think Enhex has confirmed it is working for him as well. See http://urho3d.prophpbb.com/topic1695.html.

**Comment by 1vanK** [comment] 2016-01-05 18:18
Well, I tested various combinations:

1) STATIC RELEASE library works, but 
![bug](https://cloud.githubusercontent.com/assets/13021826/12123380/0d7ccd90-b3fa-11e5-9c6f-c329c4842a58.png)

why lib_type is checkbox????

2) static debug does not works

3) shared debur works

**Comment by MonkeyFirst** [comment] 2016-01-05 18:19
Hi wrote what hi delete CMakeLists.txt for some reason, but I do not delete anything. I build engine and project from blank. New dirs. with new files and so on...

Also now I do trying to test build engine as SHARED (actually never used this option before) engine compiled fine, editor work fine, but my sketch project (from blank) after fine compiling (release and debug) are falling on startup, both version Release and Debug. Urho3D.dll are (exist) present in same dir with exe. 

@1vanK I guessing waht this is automatic option it grab option from your engine SDK options

**Comment by 1vanK** [comment] 2016-01-05 18:25
Also is it normal that CMake was found d3d, whean i use Opengl

**Comment by MonkeyFirst** [comment] 2016-01-05 18:35
>Also is it normal that CMake was found d3d, when i use Opengl?
Yes, this is for mixed rendering in one frame :)

Also I solve my little problem with falling shared version of my exe I forgot put my custom scene1.xml inro std scenes folder. so shared builds work fine for me now )

**Comment by cadaver** [comment] 2016-01-05 19:02
I retract my bug report, compiling on another machine with a completely clean checkout worked with VS2013. Could also have been a CMake version difference.

Urho3D-CMake-Common always searches for the DirectX SDK on Windows, because compiling SDL requires the DX headers. In case you are using old VS (2010 or earlier), a DX SDK is mandatory and if not installed as a VS default directory, SDL compilation will fail.

**Comment by 1vanK** [comment] 2016-01-05 19:49
> Could also have been a CMake version difference

I checked out the old version of CMake.

Engine - static debug Cmake 3.4.1
App - Cmake 3.3.0 - works fine!

So we have a bug: cmake 3.4.1 + static + debug

**Closed** 2016-01-06 00:30 UTC
Labels: build system

**Comment by weitjong** [comment] 2016-01-06 01:06
Let's hope someone else already has logged a bug report to CMake devs as bug like this should have hit other CMake users as well and hope that it will be fixed swiftly. I am hesitate to change our FindUrho3D module to bypass all the checks just for VS at this moment. So closing this for now as won't fix. We can reevaluate this again if the above assumption is wrong.

**Comment by 1vanK** [comment] 2016-01-06 06:07
```
            # BCM_VC_LIBRARIES variable is already set by FindBCM_VC module on RPI platform
            try_run (URHO3D_RUN_RESULT URHO3D_COMPILE_RESULT ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/CheckUrho3DLibrary.cpp
                CMAKE_FLAGS ${IOS_FLAGS} -DLINK_LIBRARIES:STRING=${URHO3D_LIBRARIES}\;${BCM_VC_LIBRARIES}\;${ANDROID_LIBRARIES} -DINCLUDE_DIRECTORIES:STRING=${URHO3D_INCLUDE_DIRS} ${COMPILER_32BIT_FLAG} ${COMPILER_STATIC_FLAG}
                COMPILE_OUTPUT_VARIABLE TRY_COMPILE_OUT RUN_OUTPUT_VARIABLE TRY_RUN_OUT)
```

Test build Release, but link it with debug version Urho3d_d.lib

```
    D:\Programs\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"D:\MyGames\MiniGame\Build\CMakeFiles\CMakeTmp\Release\cmTC_3a7e4.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib D:\MyGames\Urho3D\Build\lib\Urho3D_d.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"D:/MyGames/MiniGame/Build/CMakeFiles/CMakeTmp/Release/cmTC_3a7e4.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/MyGames/MiniGame/Build/CMakeFiles/CMakeTmp/Release/cmTC_3a7e4.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_3a7e4.dir\Release\CheckUrho3DLibrary.obj
 
 
  Urho3D_d.lib(LibraryInfo.obj) : error LNK2038: ���������� ��������������
  ��� "_ITERATOR_DEBUG_LEVEL": �������� "2" �� ������������� �������� "0" �
  CheckUrho3DLibrary.obj
  [D:\MyGames\MiniGame\Build\CMakeFiles\CMakeTmp\cmTC_3a7e4.vcxproj]
```

http://pastebin.com/hRX5a64L

**Comment by 1vanK** [comment] 2016-01-06 06:09
We should force build debug version for CheckUrho3DLibrary when available only Urho3d_d.lib

**Comment by weitjong** [comment] 2016-01-06 06:50
> We should force build debug version for CheckUrho3DLibrary when available only Urho3d_d.lib

This is correct assessment but we have already done that. See 
https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/FindUrho3D.cmake#L230-L234

**Comment by 1vanK** [comment] 2016-01-06 07:13
Ok, I send bugreport to CMake
https://public.kitware.com/Bug/view.php?id=15905

**Comment by 1vanK** [comment] 2016-01-08 22:11
@weitjong can you see this thread https://public.kitware.com/Bug/view.php?id=15905 ?

**Comment by 1vanK** [comment] 2016-01-12 00:52
Brad King from CMake team recommends to improve FindUrho3D module

**Comment by weitjong** [comment] 2016-01-12 01:53
@1vanK I am sorry that I have other fire to fight at the moment. I know who is Brad King, been tracking CMake git repository for some time. I will pay him a visit later in their bugtracker. I just want to add a short comment here that for MSVC compiler, the try_run() never loops. See: https://github.com/urho3d/Urho3D/blob/df2e152a6cba22b590ebfbb368a183cc036d6054/CMake/Modules/FindUrho3D.cmake#L167-L171
The loop is designed to only take place when the chosen compiler is really multilib capable and MSVC is not. As for his recommendation for creating package configuration information, yes, we/I have been thinking about it. However, we are currently still being tied up by Travis-CI using ancient CMake 2.8.7 so we cannot safely use those more modern CMake constructs.

**Comment by weitjong** [comment] 2016-01-22 12:07
I have 3.3.2 earlier on my Windows 10. I originally wanted to reproduce your issue with 3.4.1 but it turns out 3.4.2 already out, so I downloaded that instead. And the verdict is: still producible. STATIC + debug works find for building Urho3D library and using Urho3D library.

In the CMake issue tracker I believe I have read you commented that the FindUrho3D module appeared to be looped one time. That should not happen at all. I think you must have called FindUrho3D twice instead. Look at the updated documentation in http://urho3d.github.io/documentation/HEAD/_using_library.html, especially on how the CMakeLists.txt should read. The HEAD version does not use FindUrho3D module there anymore. Not sure that is your problem though. Perhaps, I am just getting lucky again and that 3.4.2 is the good version to use.

**Comment by 1vanK** [comment] 2016-01-22 13:33
Confirmed. Cmake 3.4.2 has no problem.
