### ISSUE TITLE
Sprite Scaling bug

### ISSUE THREAD

**Issue by cjmxp** [urho3d/Urho3D#2396] opened 2018-11-27 04:37 UTC
![default](https://user-images.githubusercontent.com/2855349/49058921-31f90700-f241-11e8-8404-fbc08b756be0.png)
![default](https://user-images.githubusercontent.com/2855349/49058937-3de4c900-f241-11e8-8285-15842d54d511.png)

**Comment by weitjong** [comment] 2018-11-27 08:58
Duplicate of #2374

**Comment by cjmxp** [comment] 2018-11-27 09:10
Oh, oh.

**Comment by cjmxp** [comment] 2018-11-27 09:13
@weitjong  

Windows compiles android. Can you compile android?

**Closed** 2018-11-27 09:14 UTC
Labels: duplicate

**Comment by weitjong** [comment] 2018-11-27 16:15
> Windows compiles android. Can you compile android?
> I have a lot of people here who can't compile anndorid on Windows.

This is off-topic here. Search our forum and you will find the answer there. In short, Android build on Win7 host system is being reported as fine, not on Win10 though (issue with command.exe line buffer). I haven't really tested it, but I bet running `gradlew` on top of WSL might actually just work.

**Comment by cjmxp** [comment] 2018-11-27 16:31
Thanks for your help

**Comment by cjmxp** [comment] 2018-11-28 08:12
@weitjong 
![default](https://user-images.githubusercontent.com/2855349/49137768-5bd92900-f328-11e8-93ae-743557b528cb.png)
There seems to be some problems.

**Comment by weitjong** [comment] 2018-11-28 09:22
I am sorry to hear that.  I am also sorry to say that this should be the last time I answer this off-topic question here in this issue log.  For any other questions, please use our forum. Back to your Gradle issue. make sure your Gradle is working correctly first before attempting to use it to build Urho3D project. It looks like your build environment is not properly configured yet. I would check the PATH environment variable and other variables to see they point to software that lives on the WSL side. Good luck.
