### ISSUE TITLE
why there is no windows version in the latest snapshot build ?

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#951] opened 2015-10-14 08:15 UTC
Hi
   I want to use the latest snapshot version, I had checked the url http://sourceforge.net/projects/urho3d/files/Urho3D/Snapshots/, there is no recent windows version, I`m not sure what happened.

**Comment by cadaver** [comment] 2015-10-14 09:33
There can be random hickups in the build/upload process (servers too busy, build taking too long, sourceforge unresponsive.)

To be honest, for serious development work I would personally build Urho myself rather than relying on prebuilt libs, which are somewhat a hazard due to there being no C++ ABI standard. The downloads are most useful to quickly check Urho (the sample programs for instance) and to verify that the build process functions correctly for all platforms.

**Comment by weitjong** [comment] 2015-10-14 10:24
There are regression issues in the Travis CI setup at the moment. It was broken by some other unrelated changes that we made in the build system. I have noticed at least two things now:
1. ScriptCompiler tool is not being built correctly for Windows build causing this issue.
2. Mirror CI branches are not being created when commit message contains shell wildcard characters.

**Comment by weitjong** [comment] 2015-10-16 10:34
The second issue seems to be resolved by itself. Most probably it was caused Travis CI side.

**Closed** 2015-10-23 15:12 UTC
Labels: bug
