### ISSUE TITLE
Android Gyro not working?

### ISSUE THREAD

**Issue by gwald** [urho3d/Urho3D#1315] opened 2016-04-08 00:04 UTC
Sample 18 CharacterDemo, tested on my phone and tablet.
The gyro option isn't working on the demo.
May be related to: https://github.com/urho3d/Urho3D/issues/1303

**Comment by hdunderscore** [comment] 2016-04-08 05:20
I don't believe I touched any gyro related code, when was the last version of urho that worked with gyro?

**Comment by weitjong** [comment] 2016-04-08 07:56
I can confirm it was still working prior to SDL 2.0.4 upgrade branch being merged into master.

**Comment by cadaver** [comment] 2016-04-08 08:47
The gyro was previously a "virtual joystick". I think that should still be the case (by default) as of 2.0.4, controlled by the hint SDL_HINT_ACCELEROMETER_AS_JOYSTICK.

**Comment by weitjong** [comment] 2016-04-08 11:58
I found something else while looking into this issue. Tested on my old Galaxy Tab, the sampler browser is either crashing or flickering when the device has a landscape orientation while it being launched. While holding the device in portrait orientation is OK. The problem goes away when I drop the target SDK from 21 back to 12 in the Android manifest file. As I understand it, that would mean the sample browser will run in compatibility mode on newer Android.

**Comment by weitjong** [comment] 2016-04-09 03:27
I found the culprit. I suppose our code doesn't expect to find a joystick on Android platform but when it finds one then the code assumes it is the accelerometer (treated as 3-axis joystick) without checking. This is fine on SDL 2.0.3 but not on SDL 2.0.4. Based on the logcat comparison, I can confirm that app built with 2.0.3 only registers one "joystick" which is the accelerometer, however, app built with 2.0.4 registers multiple "joysticks" and the one for accelerometer is actually the last in the iteration. In my test, quickly skipping all the other joysticks and leave the accelerator as the only being registered solves the issue. Those being skipped have name such as: "sec_jack", "sec_touchscreen", "sec_keys", "Button Jack", "sec_powerkey", and "Virtual". The one that we need has this name "Android Accelerometer".

Now, I am not sure  if this is a SDL 2.0.4 bug, i.e. those bogus ones should be skipped? Or this is our bug, i.e. we should query the number joysticks first and looks for the one with the right name? I haven't got time to trace the SDL code to understand why SDL 2.0.4 behaves differently though. See https://github.com/urho3d/Urho3D/blob/b682f559b6703a6807a35977018c765a33a668ed/Source/ThirdParty/SDL/src/core/android/SDL_android.c#L219-L232. This part of the code looks almost identical between 2.0.3 and 2.0.4, the difference is on 2.0.4 it appears this functions is being triggered multiple times.

**Comment by cadaver** [comment] 2016-04-09 11:17
This sounds just like carelessness on our part, because there could be actual joysticks attached in any case, so the name should be compared.

**Comment by weitjong** [comment] 2016-04-09 11:44
Yes, I agree. Since the "Gyro" button specifically says it is for toggling the gyroscope accelerometer input handling then the code should have check for the correct "joystick" in case there are other joystick being attached. However, arguably we could also say something is not quite right with SDL 2.0.4 registering those bogus joysticks. I did not continue my debugging session after making the above comment.

**Comment by cadaver** [comment] 2016-04-09 13:17
This seems to be handled by the SDLActivity Java code. Before 2.0.3 they added only InputDevice.SOURCE_CLASS_JOYSTICK devices, now they add also InputDevice.SOURCE_CLASS_BUTTON devices, which does look a bit questionable.

**Comment by weitjong** [comment] 2016-04-09 13:23
I am exactly looking at that code. Thinking about the same thing as well. Plan to check their commit log and saw the GitHub notification message from your comment. No kidding. :smile:

**Comment by weitjong** [comment] 2016-04-09 13:27
https://github.com/urho3d/SDL-mirror/commit/34a0b0478654e8dfaf111aecc0e4535875c4ec87

**Closed** 2016-04-09 13:50 UTC
Labels: bug

**Comment by weitjong** [comment] 2016-04-09 14:31
I have added a new API to get the joystick by its name instead of index. However, I have stopped short to make changes in the sample code themselves.

**Comment by cadaver** [comment] 2016-04-11 08:45
Agreed (sorry for late reply). If we later find it's necessary we could add the detection to rather use SOURCE_GAMEPAD / SOURCE_DPAD instead of SOURCE_CLASS_BUTTON.
