### ISSUE TITLE
ListBase Field Visibility Warnings

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2652] opened 2020-06-26 02:25 UTC
Compiling the latest master I'm getting a lot of warnings along the lines of:
```
/home/nathan/Projects/Urho3D/Source/Urho3D/Graphics/../IO/../Container/../Container/ListBase.h:93:18: warning: ‘Urho3D::ListBase’ declared with greater visibility than the type of its field ‘Urho3D::ListBase::head_’ [-Wattributes]
   93 | class URHO3D_API ListBase
      |                  ^~~~~~~~
/home/nathan/Projects/Urho3D/Source/Urho3D/Graphics/../IO/../Container/../Container/ListBase.h:93:18: warning: ‘Urho3D::ListBase’ declared with greater visibility than the type of its field ‘Urho3D::ListBase::tail_’ [-Wattributes]
```
This is with gcc version 9.2.1 20191008 if that matters.

**Comment by weitjong** [comment] 2020-06-29 11:16
Duplicate of #2637

**Comment by 1vanK** [comment] 2020-08-08 14:07
Because ListBase have URHO3D_API and exported, but used ListNodeBase without URHO3D_API

**Comment by weitjong** [comment] 2020-08-18 16:09
This issue is fixed in the `upgrade-toolchains` dev branch. This commit 32dc04cd28c0a2257080d70b3dd7c8e2bf914d93 should fix it.

**Comment by weitjong** [comment] 2020-08-19 16:00
Perhaps I have closed this too quickly. The issue come back when using `-std=c++11` instead of `-std=gnu++11`.

**Closed** 2020-08-31 12:08 UTC
Labels: bug, build system
