### ISSUE TITLE
iOS physical iPhone device running error

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#1369] opened 2016-05-18 07:59 UTC
My testing device is iPhone 6 with iOS 9.3.1 installed.
It seems that the script module is not working correctly.

`
2016-05-18 15:56:02.942 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectBehaviour' with 'Array' and 'bool f(int&in, bool&out)' (Code: -7)
2016-05-18 15:56:02.942 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectBehaviour' with 'Array' and 'Array<T>@ f(int&in)' (Code: -7)
2016-05-18 15:56:02.942 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectBehaviour' with 'Array' and 'Array<T>@ f(int&in, uint)' (Code: -7)
2016-05-18 15:56:02.943 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectBehaviour' with 'Array' and 'Array<T>@ f(int&in, uint, const T &in)' (Code: -7)
2016-05-18 15:56:02.943 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectBehaviour' with 'Array' and 'Array<T>@ f(int&in type, int&in list) {repeat T}' (Code: -7)
2016-05-18 15:56:02.943 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectBehaviour' with 'Array' and 'void f()' (Code: -7)
2016-05-18 15:56:02.943 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectBehaviour' with 'Array' and 'void f()' (Code: -7)
2016-05-18 15:56:02.943 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'T& opIndex(uint)' (Code: -7)
2016-05-18 15:56:02.944 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'const T& opIndex(uint) const' (Code: -7)
2016-05-18 15:56:02.944 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'Array<T>& opAssign(const Array<T>& in)' (Code: -7)
2016-05-18 15:56:02.944 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Insert(uint, const T& in)' (Code: -7)
2016-05-18 15:56:02.944 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Erase(uint)' (Code: -7)
2016-05-18 15:56:02.944 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Push(const T& in)' (Code: -7)
2016-05-18 15:56:02.944 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Pop()' (Code: -7)
2016-05-18 15:56:02.945 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Reserve(uint)' (Code: -7)
2016-05-18 15:56:02.945 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Resize(uint)' (Code: -7)
2016-05-18 15:56:02.945 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Clear()' (Code: -7)
2016-05-18 15:56:02.946 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Sort()' (Code: -7)
2016-05-18 15:56:02.948 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Sort(uint, uint)' (Code: -7)
2016-05-18 15:56:02.948 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void SortReverse()' (Code: -7)
2016-05-18 15:56:02.948 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void SortReverse(uint, uint)' (Code: -7)
2016-05-18 15:56:02.949 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void Reverse()' (Code: -7)
2016-05-18 15:56:02.949 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'int Find(const T&in) const' (Code: -7)
2016-05-18 15:56:02.949 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'int Find(uint, const T&in) const' (Code: -7)
2016-05-18 15:56:02.949 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'int FindByRef(const T&in) const' (Code: -7)
2016-05-18 15:56:02.950 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'int FindByRef(uint, const T&in) const' (Code: -7)
2016-05-18 15:56:02.950 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'bool opEquals(const Array<T>&in) const' (Code: -7)
2016-05-18 15:56:02.950 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'uint get_length() const' (Code: -7)
2016-05-18 15:56:02.950 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'void set_length(uint)' (Code: -7)
2016-05-18 15:56:02.951 Urho3DPlayer[2161:1173395] :0,0 Failed in call to function 'RegisterObjectMethod' with 'Array' and 'bool get_empty() 
...
`

**Comment by cadaver** [comment] 2016-05-18 11:10
Native calling convention is not supported by AngelScript on ARM64 processors, so getting this working would require converting the script bindings to generic calling convention. Same issue is encountered on the Emscripten platform.

**Comment by SuperWangKai** [comment] 2016-05-20 00:59
So we cannot use AngelScript in Urho on iOS? That's very sad.

**Comment by cadaver** [comment] 2016-06-11 00:03
Now with the generic convention support installed originally for Emscripten we're close to solving this.

I was able to get NinjaSnowWar running on a 64bit iPad. However as XCode was building the universal binary, I now got unresolved external symbol errors for armv7 (32bit) build, as the native convention asm functions (_armFuncxxx and co.) were not included. To get it building I simply dropped the armv7 architecture. 

@weitjong Do you have ideas for this? Ugly solution would be to default to generic convention for all iOS architectures, which I suppose lowers performance. However I suspect a large part of users are already using 64bit devices.

**Comment by weitjong** [comment] 2016-06-11 04:14
There should be a cleaner fix. It could be just a regression issue after recent commits to add support for generic ARM build. I had to tweak a number of things to get all the platforms build happily. However, I don't have actually any 64-bit ARM devices so the 64-bit ARM binaries are untested by me.

**Comment by weitjong** [comment] 2016-06-11 05:12
I leave the issue as open still because I could not verify my changes.

**Comment by cadaver** [comment] 2016-06-11 12:13
Verified to run on hardware. Thanks! Closing this now.

**Closed by cadaver** 2016-06-11 12:13 UTC
Labels: bug, enhancement
