### ISSUE TITLE
assimporter generates different bone names, thus animation cannot be properly played

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1599] opened 2016-09-18 11:21 UTC
Please see the attached zip file.  skin.FBX contains a model with bones. fly.FBX and attacked.FBx are two animations. If using assimporter to generate the mdl and ani files, these two animations cannot be properly played. Some of the bone animations are missing during playing. I tracked the code down to AnimationState.cpp, function SetStartBone(Bone* startBone). It seems like some animation tracks are renamed to like Bone17_$$AssimpFBX$... and thus cannot find the correponing trackBone. These two animations can be properly played in Unity. 

[anim.zip](https://github.com/urho3d/Urho3D/files/478661/anim.zip)

**Comment by OldSnake22** [comment] 2016-09-18 12:04
Maybe it should be the right time to update Assimp version in Urho3D ? there is tons of bugfixes compared to the actual version used in the engine.

**Comment by MonkeyFirst** [comment] 2016-09-18 12:13
I tried to import fbx into Blender and got only one properly worked animation file - attaked.fbx
fly.fbx - do not have any kind of animation keys
also the actions has names in fbx like some kind of hell :)

**Comment by yushli** [comment] 2016-09-18 12:17
Even the attacked.fbx is not properly played. One animation track is missing because if (nameHash == startBone->nameHash_) is false, as stateTrack.track_->name_ is like "bone17_$AssimpFBX$translation", but startBone->name_ is "bone_17".

**Comment by MonkeyFirst** [comment] 2016-09-18 13:41
I guess the way to solve this, it's use ship model with skeleton and re-assign animations on orig skel again.
and export ship with blender plugin
So I do this for you.
![12323](https://cloud.githubusercontent.com/assets/9577466/18616088/53010320-7da5-11e6-8374-ac2571b1067b.png)

see this files http://rgho.st/76y5MSHB9

**Comment by cadaver** [comment] 2016-09-18 13:53
You could try the -np switch, which disables the FBX extra node suppression code contributed by @Lumak. Probably needs the author himself to fix/improve it, since the code is quite godlike. Otherwise updating assimp is a good idea, but may be unrelated to this.

**Comment by Lumak** [comment] 2016-09-18 15:43
I'm looking at your models and animations in game and in Maya now, but I can see that the root node (Bone017) doesn't seem to animate in game.  I'll start debugging now.

**Comment by Lumak** [comment] 2016-09-18 16:15
Stepped through the assetImporter and see that the animation is a sceneAnimation, not a model animation.  And this is why the "suppress node" doesn't come into play because to be able to suppress the animation, it needs to reference the model and extrapolate animation based on the bone definition.  

The way the assetImporter is written is that if there is no model in the scene then it'll treat it as scene, hence, results in sceneAnimation.  For me to try to associate "node suppression" feature to a scene would be a huge rewrite of the program flow, which would be a major undertaking.  

To get around this short coming, your animation export would work properly if you have animation with model.

**Comment by Lumak** [comment] 2016-09-18 16:29
Or perhaps that it's a bug that fbx animation file with skeleton and no geometry gets assigned as sceneAnimation?

I'd like to hear some thoughts regarding this.

**Comment by Lumak** [comment] 2016-09-18 16:40
Nvm, I think I found a bug related to the "node suppression" on animation lookup.

**Comment by Lumak** [comment] 2016-09-18 16:59
Actually, there is no bug. The bone info is created only when the 
model.meshes_.Size() > 0 && mesh->mNumBones > 0

So, w/o skinned mesh in the fbx file, it'll treat the animation as sceneAnimation and no "node suppression" can occur because there is no bone definition.

Not a bug, sorry.

**Comment by Lumak** [comment] 2016-09-18 17:03
But still... perhaps, it's a bug that the conditions:
    model.meshes_.Size() > 0 && mesh->mNumBones > 0
must be true to be able to create a bone definition because the file does have skeleton.

Thoughts?

**Comment by cadaver** [comment] 2016-09-18 17:12
Where's that condition? I couldn't find it with a search from the AssetImporter code.

**Comment by Lumak** [comment] 2016-09-18 17:26
In the void CollectBones(OutModel& model, bool animationOnly) function:
-2nd for loop checks for model.meshes_.Size()
-3rd loop then checks mesh->mNumBones
And because of these two conditions, bone definition is not created.

I'm gonna look into this and see if a bone definition can be created.

**Comment by cadaver** [comment] 2016-09-18 17:40
Thanks for looking into it. CollectBones is currently in the sense of "collect assimp bones" which do require a skinned mesh. Otherwise you'd just be collecting scene nodes. These are missing the skinning / offset information but should be enough for animations.

**Comment by Lumak** [comment] 2016-09-18 20:17
submitted PR - added a feature to be able to export fbx animation w/o skinned mesh #1601

**Comment by yushli** [comment] 2016-09-19 01:26
Thanks for looking into this and provides a solution so quickly. You guys are amazing!

**Comment by cadaver** [comment] 2016-09-19 08:35
Btw. I looked at assimp's repo and issue tracker, seems they have a bit of a mixup regarding the C++ standard they use. Just pulling their latest code could result in Urho tools not compiling with VS2010, but requiring newer.

https://github.com/assimp/assimp/issues/992

If Urho community consensus is that this would be OK, then fine; I don't have a strong opposition, though this is code that used to work just fine with old compilers. I don't think I would be fixing their code to be back-compatible.

**Comment by yushli** [comment] 2016-09-19 08:42
It is fine with me.

**Comment by cadaver** [comment] 2016-09-19 15:07
Closing this since there's the separate offset issue.

**Closed by cadaver** 2016-09-19 15:07 UTC
