### ISSUE TITLE
[Emscripten] Compilation failure at SDL_cpuinfo.c

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#2565] opened 2019-12-27 00:34 UTC
Fresh pull of Urho3D and Emscripten latest. Configured for web build, compilation fails at SDL_cpuinfo line 462 with the error: 

**implicit declaration of function 'sysctlbyname' is invalid in C99**

Additional errors at Line 783,

**use of undeclared identifier 'CTL_HW'** and **use of undeclared identifier 'HW_MEMSIZE'**

By passing SDL_CPUID=0 when invoking cmake I can get past that, but then it chokes on compiling SDL_string.c with multiple errors of the 'implicit declaration of function XXX is invalid in C99' variety, including _strrev, _strupr, etc...

This occurs on both Windows and Linux builds.

Edit: During configuration, the tests checking for sysctlbyname, _strrev, etc... pass with 'found'

**Comment by weitjong** [comment] 2020-01-12 04:57
Closing this as it will be fixed after we have merged the "web-build-with-LLVM-backend" to master branch. I labelled as "bug" although straightly speaking it is not. You cannot expect to update to the latest Emscripten SDK periodically and expect our build system to work with the latest available since Emscripten is known to make breaking changes all the times.

**Closed by weitjong** 2020-01-12 04:57 UTC
Labels: bug, build system

**Comment by weitjong** [comment] 2020-01-12 05:00
Don't get me wrong. The reporting of the new issue due to any break caused by newer Emscripten SDK  is welcome.
