### ISSUE TITLE
2D Position problem/question

### ISSUE THREAD

**Issue by Hevedy** [urho3d/Urho3D#587] opened 2014-12-29 18:30 UTC
When in the 2D example add 2 walls like this:

     // Create ground.
    Node@ wallLeftNode = scene_.CreateChild("Ground");
    wallLeftNode.position = Vector3(-30.0f, -3.0f, 0.0f);
    wallLeftNode.scale = Vector3(1.0f, 200.0f, 0.0f);
    // Create 2D rigid body for ground
    RigidBody2D@ wallLeftBody = wallLeftNode.CreateComponent("RigidBody2D");
    StaticSprite2D@ wallLeftSprite = wallLeftNode.CreateComponent("StaticSprite2D");
    wallLeftSprite.sprite = boxSprite;
    // Create box collider for ground
    CollisionBox2D@ wallLeftShape = wallLeftNode.CreateComponent("CollisionBox2D");
    // Set box size
    wallLeftShape.size = Vector2(0.32f, 0.32f);
    // Set friction
    wallLeftShape.friction = 0.5f;
	
    // Create ground.
    Node@ wallRightNode = scene_.CreateChild("Ground");
    wallRightNode.position = Vector3(30.0f, -3.0f, 0.0f);
    wallRightNode.scale = Vector3(1.0f, 200.0f, 0.0f);
    // Create 2D rigid body for ground
    RigidBody2D@ wallRightBody = wallRightNode.CreateComponent("RigidBody2D");
    StaticSprite2D@ wallRightSprite = wallRightNode.CreateComponent("StaticSprite2D");
    wallRightSprite.sprite = boxSprite;
    // Create box collider for ground
    CollisionBox2D@ wallRightShape = wallRightNode.CreateComponent("CollisionBox2D");
    // Set box size
    wallRightShape.size = Vector2(0.32f, 0.32f);
    // Set friction
    wallRightShape.friction = 0.5f;

and left is to -30 and right is to 30, why are in different positions using the ground box to compare the distance ?

**Comment by aster2013** [comment] 2015-01-08 13:01
Why left is 30.0f, right is -30.0f?
wallLeftNode.position = Vector3(30.0f, -3.0f, 0.0f);
wallRightNode.position = Vector3(-30.0f, -3.0f, 0.0f);

**Comment by Hevedy** [comment] 2015-01-08 16:18
Fixed, but look that https://dl.dropboxusercontent.com/u/28070491/URho3D/Forums/DemoUrho2D.png

**Comment by aster2013** [comment] 2015-01-09 03:08
Sorry I can not view your image. I am in China, it has a great wall :-1:

**Comment by friesencr** [comment] 2015-01-09 03:22
@Hevedy you can upload images to github issues by drag and dropping file in the text box

**Comment by Hevedy** [comment] 2015-01-09 10:09
@aster2013 ok good to know that.
@friesencr thanks for the tip.
![demourho2d](https://cloud.githubusercontent.com/assets/3521442/5678174/e3874352-97ef-11e4-9ba0-d31543ce9f49.png)

**Comment by Mike3D** [comment] 2015-02-07 14:21
@Hevedy, is this issue still valid, I can't reproduce.

**Comment by aster2013** [comment] 2015-10-08 09:13
Fixed in commit https://github.com/urho3d/Urho3D/commit/67a3b10e947043b285649cc1ec972f37b5119a3c

**Closed by aster2013** 2015-10-08 09:13 UTC
