### ISSUE TITLE
Possible problem at DetourCrowd **integration** causing random segfault at 64-bit build using MSVC compiler toolchain

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1200] opened 2016-02-16 03:01 UTC
Since we have enabled AppVeyor (VS2015) to test run all the sample apps as part of the CI jobs, we have observed random segfault on 64-bit build of 39_CrowdNavigation for both STATIC and SHARED lib types. The problem appears at random and only manifests itself once in a blue moon. 32-bit MSVC builds do not exhibit this problem. CI jobs using other compiler toolchains (Clang and GCC) also do not exhibit this problem in any build configurations and ABIs.

**Comment by cadaver** [comment] 2016-02-16 08:49
Since I don't think DetourCrowd uses threads, it could be an uninitialized memory issue.

**Comment by weitjong** [comment] 2016-02-21 01:30
If this issue cannot be fixed at the soonest then probably we should temporarily move the 39_CrowdNavigation out from the default AppVeyor CI and into a new CI-mirror branch by itself temporarily so that it does not raise false alarm to PR submitter.

**Comment by weitjong** [comment] 2016-02-21 04:03
The prevalence rate of this issue on VS2015 seems to increase lately, i.e. it crashes more often than not now on AppVeyor, which is actually a good thing. If it constantly crashes instead of random crash then I think VS user would eventually notice it too instead of just AppVeyor, and hopefully it is easier for them then to study the stacktrace while it happened and fix the issue permanently.

**Comment by cadaver** [comment] 2016-02-24 09:05
Yes, no problem moving it away from the CI build. A while ago I tried reproducing this on VS2015 64bit but no luck so far.

**Comment by JSandusky** [comment] 2016-02-25 05:11
No shit it's broken, you radically changed your build scripts and expect things to work the same? WTF is wrong with you - the last time that got a 64bit check was by me x 1024? The library has degenerated into filth, it's 2016 and you still don't have Geometry/Hull/Domain/Compute shaders or even Texture arrays because you couldn't pull the stick out of your own ass without tearing it.

Don't pass the bullshit off on crowds or detour. I may have no interest but what you have all just expressed are fighting words. Don't drag me into this, when you call it a generic crowd thing - that's what you're doing.

And do some fucking research so you can see that UE is suffering the same problem. Fucking idiots talking like they know some shit.

**Comment by weitjong** [comment] 2016-02-25 05:15
I have locked this issue for internal member discussion only. But I will keep the comment from Sinoid as an anti pattern.

**Comment by weitjong** [comment] 2016-02-25 05:20
@JSandusky. One more unprovoke insult and you will block out from our GitHub repo for good.

**Comment by weitjong** [comment] 2016-02-25 06:15
@cadaver I have made good on my promise. Since the action applies to all repos that I own or co-own, it means the block is effective for Urho3D as well. Let me know if this is excessive and I can be removed from Urho3D as repo owner to limit the block to reach here.

**Comment by cadaver** [comment] 2016-02-25 11:53
It's OK. This kind of hostility is not welcome.

**Comment by weitjong** [comment] 2016-03-01 16:00
I have highlighted the **integration** word in the title to make it clear that the possible problem, if indeed there is one, resides in the integration part of the code and not within the DetourCrowd library itself.

@cadaver The 39_CrowdNavigation unit test has been moved out from primary AppVeyor CI to a new secondary AppVeyor CI build now. The secondary AppVeyor CI build runs the offending unit test in extra verbose mode. However, it seems that when it segfaulted, nothing useful has been captured in log so far. At the very least, we have solved the false-alarm issue.

**Comment by weitjong** [comment] 2016-03-03 08:59
It seems that both ```ctest -VV``` and ```msbuild /verbosity:diag``` do not reveal anything useful when offending app segfaulted. The former just shows the application's log as we normally see when run the sample locally, the latter produces tons of diagnostic information from msbuild itself. If anyone knows how to configure msbuild (VisualStudio) to output something useful when debugging, let me know.

**Closed** 2016-05-21 04:04 UTC
Labels: bug
