### ISSUE TITLE
WebGL GPU Memory Leak

### ISSUE THREAD

**Issue by kannsokusha** [urho3d/Urho3D#2627] opened 2020-04-29 11:55 UTC
When I change the size of the canvas, the video memory will increase and will not be released later. If I repeat this, the program will crash.
You can reproduce it in official Web samples like this:(play speed 6x)
![2](https://user-images.githubusercontent.com/26665589/80592734-8154ef80-8a52-11ea-9d01-05ac7febc130.gif)

**Comment by eugeneko** [comment] 2020-04-29 11:58
@ArnisLielturks I guess here is the first bug in new Web shell...
TBH I have no clue how to debug GPU memory leak, especially in Web

**Comment by ArnisLielturks** [comment] 2020-04-29 12:40
The resize functionality calls the `SetMode` function in the Graphics subsystem. Maybe there's some cleanup required when new screen size is set or just before it. Anyway, will check.

**Comment by ArnisLielturks** [comment] 2020-04-29 12:53
Strangely enough can't reproduce it on an OSX system (10.15). Memory usage increases during the resizing, but quickly goes back down to normal.

**Comment by ArnisLielturks** [comment] 2020-04-29 13:08
Tested on my windows machine, the memory seems to be released after some time (~30 seconds), but still seems like there's something left. Initially app uses 100mb of GPU, after multiple resizes and wait it stops at ~600mb)
![image](https://user-images.githubusercontent.com/7426555/80599135-1ba53b00-8a33-11ea-9c02-288537d3f139.png)

**Comment by eugeneko** [comment] 2020-04-29 22:49
For me it doesn't drop tho.

I wonder if it's relevant:
https://stackoverflow.com/questions/23598471/how-do-i-clean-up-and-unload-a-webgl-canvas-context-from-gpu-after-use

When window is resized, `Graphics::Release(false, true)` is called.
It _doesn't release any objects_, it only calls `OnDeviceLost` because once cannot be 100% sure whether the context is alive (according to comments, may be lie).

So everything relies on GC to collect the context and all the resources.

**Comment by ArnisLielturks** [comment] 2020-04-30 07:01
@eugeneko If GC is really the case, then I have no idea how we could possibly fix this. Maybe there are some references in the emscripten's code that are not released when we do the resizing, our current implementation is basically a workaround and there might be some parts of the code that don't play nicely to the original ES code. I will do some testing in the upcomming days to see if I could improve it a bit. Also would be great to check what OS's and browsers are affected.

**Comment by kannsokusha** [comment] 2020-04-30 08:10
When I load a scene that consumes a lot of GPU memory, the program use Shared GPU memory first, then push into Dedicated GPU memory, and do again. 
After the first time, only one frame is rendered, and after the second the camera is free to move. However, the Shared GPU memory is not released at the end.
I think it has something to do with that.

![TIM截图20200430150714](https://user-images.githubusercontent.com/26665589/80683291-92573c80-8af6-11ea-8365-fd134777f8b7.png)

**Comment by ArnisLielturks** [comment] 2020-05-01 05:58
@kannsokusha can you give your feedback to the linked PR?

**Comment by kannsokusha** [comment] 2020-05-01 12:11
> @kannsokusha can you give your feedback to the linked PR?

It does reduce effects, but doesn't solve the bug.
I want to test a scene that consumes a lot of GPU memory, but I failed. Then I discovered the bug.
This suggests that GPU Memory Leaks occur not only when the window resized, but when the window created.

**Comment by eugeneko** [comment] 2020-05-01 22:51
@ArnisLielturks I think I fixed this leak. At least it doesn't go above 1 GB for me.
Can you cherry pick this commit and test it? For some reason I cannot build Urho locally for Web, only rbfx.
https://github.com/rokups/rbfx/commit/eb368a273e3a0ab2aef51738c4bc9ad094e1b4c0

**Comment by ArnisLielturks** [comment] 2020-05-02 07:19
@eugeneko Nice! I have applied your fixes to the demo link. Make sure to clear the browser cache first (just to make sure you'll get the latest build)

**Comment by kannsokusha** [comment] 2020-05-02 12:20
> @ArnisLielturks I think I fixed this leak. At least it doesn't go above 1 GB for me.
> Can you cherry pick this commit and test it? For some reason I cannot build Urho locally for Web, only rbfx, so I cannot really try it myself.
> [rokups/rbfx@eb368a2](https://github.com/rokups/rbfx/commit/eb368a273e3a0ab2aef51738c4bc9ad094e1b4c0)
> 
> If it works, maybe include this commit into your PR... or I can put it in separate one, whatever.

Nice!

![image](https://user-images.githubusercontent.com/26665589/80863984-536de600-8cb2-11ea-8aa7-5c0df7db43e3.png)

**Comment by eugeneko** [comment] 2020-05-02 12:30
@kannsokusha So you confirm that the issue is resolved, right?

**Comment by kannsokusha** [comment] 2020-05-02 16:55
> @kannsokusha So you confirm that the issue is resolved, right?
> 
Now,creating or resizing the window will cause almost GPU memory leaks. Thanks!

**Comment by kannsokusha** [comment] 2020-05-02 17:05
> I'm still quite surpised that this leak affects you that badly. In my case, memory consumtion was much smaller.

2.2G Texture for PBR, It could not be load before.  (T-T)
![TIM20200503005451](https://user-images.githubusercontent.com/26665589/80870565-cdfe2c00-8cd9-11ea-98b4-8666183c0114.png)

**Comment by ArnisLielturks** [comment] 2020-05-09 16:22
Fixed in #2628

**Closed by ArnisLielturks** 2020-05-09 16:22 UTC
Labels: backlog, bug
