### ISSUE TITLE
No shortcut to Autoload folder (Win 10)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1974] opened 2017-06-06 08:02 UTC
CMake creates shortcut to CoreData and Data folders, but Autoload is missing, so PBRDemo.bat does not work without manual coping. Also CMake does not copy PBRDemoDeferred.bat and PBRDemoDeferredHWDepth.bat

**Comment by weitjong** [comment] 2017-06-06 14:05
Because that folder is quite huge so it does not make sense to have it platform that does not support it or for user that does not need PBR. The symlink or copying 'action' for Autoload will only happen when PBRMaterials sample is being included in the build.

As for the missing batch files, it seems they were added at the later time. And whoever did it has not even bother to add their shell scripts counterpart. I wonder are we really that lazy. The extra argument can be passed in via the original batch file or shell script.

**Comment by 1vanK** [comment] 2017-06-06 15:58
Also, since are used symlinvs instead copyng bat files, its search Urho3DPlayer.exe/Urho3DPlayer_d.exe in Urho3D\bin\ instead Build\bin\ and does not works

**Comment by weitjong** [comment] 2017-06-06 16:59
I am not using my Win10 boot partition at the moment and I am not sure I understand your last statement, so please kindly rephrase it or wait until I have time boot into it.

**Comment by 1vanK** [comment] 2017-06-06 22:52
![1](https://user-images.githubusercontent.com/13021826/26855398-5ae76e52-4b23-11e7-86f2-4fa7afce794f.png)

d:\MyGames\Urho3D16\Build\ - folder with builded urho
d:\MyGames\Urho3D16\Urho3D\ - folder with sources

Translated message:
Can not find "d:\MyGames\Urho3D16\Urho3D\bin\Urho3DPlayer_d.exe". Pls check file name and try again.

I.e. there is a search exe in sources folder

**Comment by 1vanK** [comment] 2017-06-19 23:06
if using  .LNK instead symlink for *.bat files (or just copy bat files) all works perfect

**Comment by weitjong** [comment] 2017-06-26 03:09
> if using standart .LNK (shortcuts) instead symlink for *.bat files (or just copy bat files) all works perfect

Sorry for the late response (been busy with my work, actually more like having fun with Kotlin :-). Our build system can only use the cross-platform "setup fixture" that CMake supports. I see no reason why symlink cannot be made to work correctly. Will try to fix that when I have time.

**Comment by weitjong** [comment] 2017-07-02 04:10
Tested this on my Win7 VM and I could not reproduce the issue with the auto-generated symlink (MKLINK) on my test environment. I don't think using Win10 is of any difference, so closing this.

**Closed by weitjong** 2017-07-02 04:10 UTC
Labels: bug, build system

**Comment by 1vanK** [comment] 2017-07-02 05:31
on windows 7 I had no problems either

**Comment by 1vanK** [comment] 2017-07-02 05:34
may be just coby bat files? They have a small size and It solve the problem

**Comment by weitjong** [comment] 2017-07-02 06:03
Interesting. I really see no reason why but will check again when I boot into my Win10 partition on bare metal.

**Comment by weitjong** [comment] 2017-07-02 15:53
Tested with Win10 and still not reproducible. All the symlinks are created correctly and usable. In fact, it works better than I have expected (my source tree is somewhere in the "bash on Windows"'s home directory and my build tree is in the native Windows's Users directory; so the symlinks are pointing to files in %localappdata/lxss and yet they all work).

Below is part of the "dir" command output from my build-tree's "bin" directory.
```
02/07/2017  11:37 PM    <SYMLINKD>     Autoload [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\Autoload]
02/07/2017  11:37 PM    <SYMLINK>      ConvertModels.bat [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\ConvertModels.bat]
02/07/2017  11:37 PM    <SYMLINKD>     CoreData [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\CoreData]
02/07/2017  11:42 PM         4,488,896 d3dcompiler_47.dll
02/07/2017  11:37 PM    <SYMLINKD>     Data [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\Data]
02/07/2017  11:37 PM    <SYMLINK>      Editor.bat [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\Editor.bat]
02/07/2017  11:48 PM           349,696 lua.exe
02/07/2017  11:48 PM           668,816 lua.ilk
02/07/2017  11:48 PM           995,328 lua.pdb
02/07/2017  11:48 PM           261,120 luac.exe
02/07/2017  11:48 PM           490,756 luac.ilk
02/07/2017  11:48 PM           839,680 luac.pdb
02/07/2017  11:37 PM    <SYMLINK>      NinjaSnowWar.bat [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\NinjaSnowWar.bat]
02/07/2017  11:37 PM    <SYMLINK>      PBRDemo.bat [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\PBRDemo.bat]
02/07/2017  11:37 PM    <SYMLINK>      PBRDemoDeferred.bat [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\PBRDemoDeferred.bat]
02/07/2017  11:37 PM    <SYMLINK>      PBRDemoDeferredHWDepth.bat [C:\Users\weitjong\AppData\Local\lxss\home\weitjong\SDKs\urho3d\Urho3D\bin\PBRDemoDeferredHWDepth.bat]
02/07/2017  11:48 PM    <DIR>          tool
02/07/2017  11:48 PM        29,397,504 Urho3DPlayer_d.exe
02/07/2017  11:48 PM        42,743,016 Urho3DPlayer_d.ilk
02/07/2017  11:48 PM        56,922,112 Urho3DPlayer_d.pdb
             154 File(s)  4,286,350,860 bytes
               6 Dir(s)   7,780,810,752 bytes free
```

**Comment by 1vanK** [comment] 2017-07-02 17:58
may be your "bin" is in PATH variable?

**Comment by weitjong** [comment] 2017-07-03 00:20
No, I either cd into the bin first then execute or use a fully qualified path to execute the binaries.

**Comment by 1vanK** [comment] 2017-07-03 04:00
Does anyone else have such a problem?

**Comment by 1vanK** [comment] 2017-07-03 07:37
I add to SOURCES\bin\Editor.bat two lines which show paths:

```
:: @echo off


echo %cd%
echo %~dp0%
pause

if exist "%~dp0Urho3DPlayer.exe" (set "DEBUG=") else (set "DEBUG=_d")
if [%1] == [] (set "OPT1=-w -s") else (set "OPT1=")
start "" "%~dp0Urho3DPlayer%DEBUG%" Scripts/Editor.as %OPT1% %*
```

https://stackoverflow.com/questions/4419868/what-is-the-current-directory-in-a-batch-file
%cd% will give you the current working directory (variable)
%~dp0 will give you the full path to the batch file's directory (static)

%cd% (current dir) is BUILD/Bin
%~dp0 (path to bat) is SOURCES/Bin

![2](https://user-images.githubusercontent.com/13021826/27782425-2cc17712-5fdb-11e7-9af3-5a4241f37b95.png)

in bat files used %~dp0 (path to SOURCES/Bin that not contain *exe files) and I do not know why windows found *.exe on your system

**Comment by weitjong** [comment] 2017-07-03 08:51
I expect the symlink on Windows to work similarly to the rest and by that what I have observed in my build environment is in fact consistent with the rest and expected. I also setup my Windows system such that I can develop using a non-Admin account. Again similar to how I setup for the rest of my build environments.

I am not familiar enough now with Windows system (have been moved on to greener pasture for so many years), so I have really no idea what could be the course of your issue. Sorry.

**Comment by 1vanK** [comment] 2017-07-03 08:55
can you show your echo %~dp0% ?

**Comment by weitjong** [comment] 2017-07-03 09:11
Not near my computer now. But I believe it should echo out the path to the "bin" directory in my build tree, or else the batch file won't work.

**Comment by 1vanK** [comment] 2017-07-11 19:14
```
             154 File(s)  4,286,350,860 bytes
               6 Dir(s)   7,780,810,752 bytes free
```
why your "dir" command shows so many files?
My output:
```
11.07.2017  22:06    <DIR>          .
11.07.2017  22:06    <DIR>          ..
11.07.2017  22:03    <SYMLINKD>     Autoload [D:\MyGames\Urho3D16\Urho3D\bin\Autoload]
11.07.2017  22:03    <SYMLINK>      ConvertModels.bat [D:\MyGames\Urho3D16\Urho3D\bin\ConvertModels.bat]
11.07.2017  22:03    <SYMLINKD>     CoreData [D:\MyGames\Urho3D16\Urho3D\bin\CoreData]
11.07.2017  22:03    <SYMLINKD>     Data [D:\MyGames\Urho3D16\Urho3D\bin\Data]
11.07.2017  22:03    <SYMLINK>      Editor.bat [D:\MyGames\Urho3D16\Urho3D\bin\Editor.bat]
11.07.2017  22:03    <SYMLINK>      NinjaSnowWar.bat [D:\MyGames\Urho3D16\Urho3D\bin\NinjaSnowWar.bat]
11.07.2017  22:03    <SYMLINK>      PBRDemo.bat [D:\MyGames\Urho3D16\Urho3D\bin\PBRDemo.bat]
11.07.2017  22:03    <SYMLINK>      PBRDemoDeferred.bat [D:\MyGames\Urho3D16\Urho3D\bin\PBRDemoDeferred.bat]
11.07.2017  22:03    <SYMLINK>      PBRDemoDeferredHWDepth.bat [D:\MyGames\Urho3D16\Urho3D\bin\PBRDemoDeferredHWDepth.bat]
11.07.2017  22:06        19 749 888 Urho3DPlayer_d.exe
11.07.2017  22:06        27 151 404 Urho3DPlayer_d.ilk
11.07.2017  22:06        57 839 616 Urho3DPlayer_d.pdb
               9 файлов    104 740 908 байт
               5 папок  388 165 963 776 байт свободно
```
p.s. I do not believe that I have a non-standard version of Windows :) Moreover,  %~dp0 leads as it is written in help

**Comment by 1vanK** [comment] 2017-07-23 00:23
Hm, when I use CMAKE-GUI (with default settings) instead console command
```
Urho3D/cmake_vs2015.bat Build -DURHO3D_OPENGL=ON -DURHO3D_SAMPLES=OFF -DURHO3D_LUA=OFF -DURHO3D_STATIC_RUNTIME=ON -DURHO3D_TOOLS=OFF
```
all resources copied to build\bin dir instead make simlinks (pls do not fix it, or replace simlinks to copy bat files in console version)

**Comment by weitjong** [comment] 2017-07-23 03:23
As far as I concerned this issue is already closed, so rest assure I will not make any changes for it :smile:. Just want to add that, whether cmake is invoked via GUI or CLI, they are all the same. What could make the difference is the "environment" where the invocation takes place.

**Comment by 1vanK** [comment] 2017-07-23 08:23
This is a rather strange position...

**Comment by 1vanK** [comment] 2017-07-23 08:32
Ok, I open issue, if it is problem
