### ISSUE TITLE
Clipping issue with pyramidal models.

### ISSUE THREAD

**Issue by ext-1** [urho3d/Urho3D#2133] opened 2017-09-25 20:00 UTC
Hello,

I've been exploring the CharacterDemo and encountered some clipping issues related to pyramidal models:

![screenshot1](https://user-images.githubusercontent.com/32102283/30828088-d3e1a9f8-a212-11e7-9997-732966408ea9.jpg)
![screenshot2](https://user-images.githubusercontent.com/32102283/30828095-d8c05e1a-a212-11e7-9ac9-80855292a6c3.jpg)

Also happens on FirstPerson:

![screenshot3](https://user-images.githubusercontent.com/32102283/30829096-3840afae-a216-11e7-824f-ed251ac8c351.jpg)
![screenshot4](https://user-images.githubusercontent.com/32102283/30829105-3c5aa77a-a216-11e7-97dc-87df7117f1f9.jpg)

I've made a small test demo if anyone is interested in replicating the issue: https://gist.github.com/ext-1/f9234495e52666aed4a3181f55ef4e4b#file-characterdemo-cpp-L184-L194
(just look left and the left face of the pyramid will clip)

Have anyone encountered this issue before?

Best regards.

**Comment by eugeneko** [comment] 2017-09-25 20:45
Cannot reproduce. This issue is very stange because Urho doesn't have any mechanism of partial culling (except front/back face culling).

Could it be environment problem?
Try another GAPI.

**Comment by ext-1** [comment] 2017-09-25 21:04
I believe you're right. Tested it on other machines and there are no issues there.
Must be related to the environment here.
Thank you. Sorry for the bad report.

**Comment by eugeneko** [comment] 2017-09-25 21:11
If you use Windows, try another renderer. It could be a bug in your video driver (I tested with DX11, NVidia GTX 840m)

**Comment by ext-1** [comment] 2017-09-25 21:42
Was testing on Debian with some older OpenGL drivers:
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.1 (Core Profile) Mesa 10.3.2
OpenGL core profile shading language version string: 1.40
```
Didn't realize this machine was that un-updated. My bad.

**Comment by eugeneko** [comment] 2017-09-25 21:45
Then, I'll close it for now.

**Closed by eugeneko** 2017-09-25 21:45 UTC
Labels: question
