### ISSUE TITLE
urho3d crashes on android when reopen the app

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#2221] opened 2017-12-26 10:36 UTC
please see https://github.com/urho3d/Urho3D/pull/2087

**Comment by weitjong** [comment] 2017-12-27 14:23
I am not able to reproduce it in my test AVD using x86_64 arch.

**Comment by yushli** [comment] 2017-12-27 14:40
The crash happens on an android mobile phone with arm arch. 
This commit fixes the crash before upgrading sdl to 2.0.7. But after the upgrade, even when this commit is added, the re open app crash still happens. Maybe @rokups has some idea what causes this crash.

**Comment by rokups** [comment] 2017-12-27 14:42
Comment in that PR says:

> Hash of activity object that owns state, kept around in order to prevent dying activity overwriting state it no longer owns.

I do not really remember what was going on there. Something with multiple activities doing unexpected thing apparently.

**Comment by yushli** [comment] 2017-12-27 14:53
The interesting thing is that, when using sdl 2.0.6, before adding this commit, re open app crashes. after adding this commit, the crash is fixed. now after upgrading to sdl 2.0.7, the crashes happens, with or without this commit. I don't know whether it is my test mobile's issues. Both are a bit old now. I need to change     AndroidManifest.xml to 
<uses-sdk
        android:minSdkVersion="10"
        android:targetSdkVersion="12"/>for them to work.

**Comment by weitjong** [comment] 2017-12-27 14:54
That patch should be obsolete now because the base SDLActivity class from 2.0.7 is very different from 2.0.5. The guard is now implemented differently but it is still there.

**Comment by yushli** [comment] 2017-12-28 14:28
I am going to replace the old test phones with a new one. will close this right now if no one else encounters this issue.

**Comment by weitjong** [comment] 2018-01-27 16:24
@yushli Will probably try to revert back changes to switch to Java 8 language feature (or may be still use it but then setup the build to still generate bytecode for JVM 6) because just may be some older Android devices only have older JVM.

Sorry for double post. I meant to comment it here instead.

**Comment by weitjong** [comment] 2018-07-08 04:39
This issue is now fixed in the `gradle-kotlin-dsl` dev branch. That dev branch will be merged soon. To safe me time to come back to issue log again later, I am closing it now.

**Closed by weitjong** 2018-07-08 04:39 UTC
Labels: bug
