### ISSUE TITLE
Urho3DPlayer Crash

### ISSUE THREAD

**Issue by BlueMagnificent** [urho3d/Urho3D#954] opened 2015-10-14 16:32 UTC
I pulled the latest master yesterday (14 Oct 2015) and it built well, the sample applications run without problem but Urho3DPlayer crashes when you try to run some scripts, like scripts that have zone component or physics component.

My Build is MinGw-w64 on windows with the following options 
-DURHO3D_SSE -DURHO3D_FILEWATCHER -DURHO3D_PROFILING -DURHO3D_LOGGING 
-DURHO3D_THREADING -DURHO3D_OPENGL -DURHO3D_STATIC_DEFINE
 -DURHO3D_ANGELSCRIPT -DURHO3D_NAVIGATION -DURHO3D_NETWORK
 -DURHO3D_PHYSICS -DURHO3D_URHO2D

**Comment by cadaver** [comment] 2015-10-14 17:23
What is your GCC version in MinGW?

**Comment by BlueMagnificent** [comment] 2015-10-14 20:59
the gcc version is 5.1.0

**Comment by cadaver** [comment] 2015-10-15 07:41
Ok, then it looks like GCC / MinGW isn't fixing this problem in future versions, and we're better fallback to -msse again.

**Comment by BlueMagnificent** [comment] 2015-10-15 08:19
Funny enough I can recall complaining about this same kind of issue when a similar modification was made earlier and -msse option had to be returned to for it to be resolved. If there is no much performance advantage that I'll forfeit in using -DURHO3D_SSE=0 then I'm ok with it

**Comment by cadaver** [comment] 2015-10-15 10:46
This is likely the true cause:
http://www.peterstock.co.uk/games/mingw_sse/

**Comment by weitjong** [comment] 2015-10-15 12:56
I am thinking since it only crashes when running AngelScript scripts, should we just fix the stack alignment issue at the entry point where AngelScript function is being called? If I understood correctly then passing this compiler flag instructs GCC to perform the check globally in all functions. Since OP reported all the sample app run fine, the fix looks a little bit overkill to me.

**Comment by weitjong** [comment] 2015-10-20 14:33
I am cross-compiling using MinGW to target Win 64-bit and SSE on without the stackrealign flag. I am not able to reproduce the Urho3DPlayer crash. I am testing it using my Win7 VM on VirtualBox, however. Hoping to reproduce it there than rebooting into my Win7 on baremetal. @BlueMagnificent Could you tell me which scripts have you used to crash the Urho3DPlayer?

**Comment by BlueMagnificent** [comment] 2015-10-20 21:22
I'd have to build the latest master and test out if any new changes have been made, but basically any script that had zone and physics components was sure to crash Urho3DPlayer

**Comment by weitjong** [comment] 2015-10-21 00:04
I was using physics stress test script and it runs fine. When I have time later today I will try MinGW on Win7 host itself to build to see if it makes any difference.

**Comment by weitjong** [comment] 2015-10-23 11:46
Upgraded to Windows 10 64-bit on my baremetal. Still, I was not able to crash my Urho3DPlayer without the stackrealign compiler flag. Newly installed the mingw-w64 (x86_64-posix-seh-rev0) with GCC 5.2.0, built everything in 64-bit, SSE on using native arch. Tested with NinjaSnowWar.as, 12_PhysicsStressTest.as, and others with zone and physics. Could it be that this is 32-bit SSE build specific? If so, I really would like to remove the flag to avoid paying the penalty of stackrealign check for every functions in MinGW 64-bit build.

**Comment by cadaver** [comment] 2015-10-23 12:57
The builds I've made when it crashes have been 32-bit.

**Comment by weitjong** [comment] 2015-10-23 15:23
Thanks for the confirmation. I have just sent a patch to only use the stackrealign flag for 32-bit build and not for 64-bit build. Will still experiment a little bit tomorrow to see we could do without that flag even for 32-bit.

**Comment by cadaver** [comment] 2015-10-23 15:25
Thanks! I will do some testing too if I can pinpoint the exact crash inside AngelScript. I though I saw it crash also in pure C++ physics calls but will have to confirm.

**Comment by weitjong** [comment] 2015-10-24 14:34
I have "better luck" in crashing the Urho3DPlayer and other sample applications in 32-bit build and I use that to identify which functions that could potentially out of alignment. They are mainly functions/methods with SSE intrinsics. After adding the ```__attribute__((force_align_arg_pointer))``` as proposed by the link you provided earlier, the crash seems to go away. Having said that, I am entirely sure whether my fix is the proper solution or why that BulletPhysics library and STB_image library do not suffer the same problem.

**Comment by weitjong** [comment] 2015-10-25 05:14
I could not commit my changes yet because it seems the fix only works in Debug build configuration, as soon as ```-O1``` or higher optimization flag kicks in then it crashes again. Somehow the optimization flag has prevented MinGW to inline those functions defined in the ```xmmintrin.h``` although they have been declared with ```extern __inline __m128 __attribute__((__gnu_inline__, __always_inline__, __artificial__))```. I suspect the functions are not inlined because I could set a breakpoint on it and it triggered, while in non-optimized build the breakpoint did not trigger at all. Not sure why or how to rectify this.

**Comment by weitjong** [comment] 2015-10-27 13:49
I have a lucky break today. I manage to find most of the program entry points that require stack realignment and the crash seems to also disappear for non-Debug build configuration. I think I should be able to commit after some cleaning up.

**Comment by weitjong** [comment] 2015-10-29 15:40
In the end I have decided not to use the local function attribute in favor of global compilation flag.
In the latest master branch we have enabled SSE code path in LuaJIT and Bullet libraries on MinGW build. Also, in higher optimization level the GCC compiler can and will inline some of the Matrix functions and Quaternion functions into other outer functions that use the math functions, which makes the ```__attribute__((force_align_arg_pointer))``` in the inner functions useless. Preventing those math functions to be inlined does not seem to be the right way to go. Additionally, we have also attempted to use -O3 for MinGW release build which allows GCC to use auto-vectorize optimization on the code. IMHO, using global ```-mstackrealign``` is the only sane approach for 32-bit build. So, I am closing this for now.

**Closed by weitjong** 2015-10-29 15:40 UTC
Labels: bug

**Comment by cadaver** [comment] 2015-10-29 15:54
I suppose this might be an AngelScript bug in the end, if the asm code for function calls causes the stack to go unaligned. The code too godlike for me to debug though.

**Comment by weitjong** [comment] 2015-10-29 16:32
In my experiment I actually did not encounter problem (yet) with AS asm code. The movaps crashes I observed came from SSE code in our math functions or the outer functions that have those functions inlined (when build with optimization flag on). Still, I do agree with you that using AS generic convention is useful in some platforms.
