### ISSUE TITLE
Node->LookAt as well as FromLookRotation reverse direction

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1961] opened 2017-05-27 23:05 UTC
If one uses Node->LookAt() of quat.FromLookRotation() they find-out that both node and quat
look in reverse direction from what it was intended to. While operated in global coordinates,
this one might be really confusing. Found this while trying to rotate head and chest bone in direction of player. Tried with Quaternion first, but had to reverse direction. Was confused a bit and then tried with
Node->LookAt and found the same issue. A long time ago I tried these and they were working
(in the same circumstances) so I wonder what is going on. I could not find any proof I'm doing something
wrong here, so I submit a bug. The code is simple:

```c++
void BTBlackboard::HandleSceneDrawableUpdateFinished(Urho3D::StringHash eventType, Urho3D::VariantMap& eventData)
{
        Node *head = node_->GetChild("head", true);
        Node *spine = node_->GetChild("spine02", true);
        Node *root = node_->GetChild("root", true);
        if (look_at_enabled && look_at) {
                Node *lookat_target = look_at;
                if (look_at->HasTag("player")) {
                        VariantMap vars = look_at->GetVars();
                        bool first_person = vars["first_persin"].GetBool();
                        if (first_person)
                                lookat_target = (Node *) vars["camera_node"].GetPtr();
                        else {
                                lookat_target = look_at->GetChild("head", true);
                        }
                } else {
                        lookat_target = look_at->GetChild("head", true);
                }
                if (!lookat_target)
                        lookat_target = look_at;
                URHO3D_LOGINFO("looking at: " + lookat_target->GetName() + " " + lookat_target->GetWorldPosition().ToString());
                URHO3D_LOGINFO("from: " +  head->GetWorldPosition().ToString());
                Quaternion prep;
                Vector3 dir = -(lookat_target->GetWorldPosition() - node_->GetWorldPosition() - Vector3(0.0f, 0.7f, 0.0f));
                URHO3D_LOGINFO("dir: " +  dir.ToString());
                prep.FromLookRotation(dir, Vector3(0.0f, 1.0f, 0.0f));
                Quaternion rot = root->GetWorldRotation();
//              Quaternion head_initial = head->GetParent()->GetWorldRotation().Inv();
//              Quaternion rot = spine->GetWorldRotation();
////            spine->SetWorldRotation(rot.Slerp(prep * Quaternion(0.0f, -180.0f, 0.0f), 0.5));
                spine->SetWorldRotation(rot.Slerp(prep, 0.5));
//              Quaternion rotl = head->GetWorldRotation();
////            head->SetWorldRotation(prep * Quaternion(0.0f, -180.0f, 0.0f));
///             Quaternion correction(-15.0f, 0.0f, 0.0f);
////            head->SetWorldRotation(prep);
                head->LookAt(lookat_target->GetWorldPosition());
        }
}
```

**Comment by slapin** [comment] 2017-06-01 00:07
I think this is related - world rotations are broken in Urho.
I run the following script on imported model of house with doors. I export into collada and use
AssetImporter (as Blender exporter doesn't support scenery export).

```c++
class Bungalow: ScriptObject {
        Array<Node@> doors;
        void Start()
        {
                Array<Node@>@ things = node.GetChildren(true);
                for (int i = 0; i < things.length; i++) {
                        if (things[i].name.StartsWith("door_"))
                                doors.Push(things[i]);
                }
                for (int i = 0; i < doors.length; i++)
                        doors[i].worldRotation = doors[i].worldRotation * Quaternion(0.0f, 5.0f, 0.0f);
        }
}
```
As you can see this should rotate doors 5 degrees upon world Y axis.

And what I get as result:

![worldrotationissue](https://cloud.githubusercontent.com/assets/6099/26659123/33726080-4677-11e7-8715-db685d81b308.png)

Well, this is too broken. I probably should stop using it, need to take a break for a few moths and see how Urho will evolve. Otherwise I will be too frustrated to continue.

**Comment by slapin** [comment] 2017-06-01 00:47
the source file can be acquired from 
https://www.blendswap.com/blends/view/15091

then Apply scale and then Apply rotation for all objects.
name all doors door_something. 
Then export to Collada. After that use AssetImporter to import scene and fix file locations if necessary.
After that you can instance the prefab and set the above script in prefab root node.
That will repeat the result.

**Comment by Lumak** [comment] 2017-06-01 02:28
I don't see a problem with the rotation.  It rotated in Y like you wrote it. Y rotation is in green, and Z rotation in blue.
![bungalowfrontdoor](https://cloud.githubusercontent.com/assets/14249868/26662183/188bd21e-4637-11e7-9fa1-b73cdaaa7a3b.png)

**Comment by slapin** [comment] 2017-06-01 09:35
Ok, let it be mystery then. I will stop using Urho and go try some other engines for a few months - will probably find something which I'm able to use.

**Comment by slapin** [comment] 2017-06-01 19:42
Well, this local issue is resolved - this is documentation issue + me not being persistent enough.
All different packages do Quaternion math differently, that is what confused me. I never actually
thought about mechanism behind, so I consulted the source and people on forum told me now that the
rotations are accumulated from right to left, so to rotate in global space I need to do
delta * baseQuat and to rotate in local space i need to do baseQuat * delta. I think this kind of hint should be in documentation. Not everyone using the engine should remember / know such things.

**Comment by slapin** [comment] 2017-06-01 19:45
BTW why would you label this wontfix while I close it myself? Is it just for bookkeeping or some other reason, I wonder.

**Comment by OvermindDL1** [comment] 2017-06-01 19:49
> I think this kind of hint should be in documentation.

This is normal vector/matrix math, as taught in school, a quaternion is just a 4d-unit-vector is all, the math is identical on it as with a 3d-unit-vector or a 2d-unit-vector.  :-)
Quaternions being a 4d-unit-vector means that the 3d component points to a direction and the last 4d-component part represent 'around' the 4d hypersphere, thus detailing 'how' you face a 3d point in 3d space once it is projected back down.  It is a convenient and efficient way to represent 3d rotation unambiguously.  :-)

> BTW why would you label this wontfix while I close it myself? Is it just for bookkeeping or some other reason, I wonder.

`wontfix` does not mean that it is or is not a bug or anything else of the sort, it is just a marker to mark an issue that it is "Conversation only" and not something that has work that needs associated with it.  :-)

**Comment by eugeneko** [comment] 2017-06-01 19:52
I have no ideas where it shall be documented because it is not something Urho-specific but just math.
Probably documentation need Math section and order of transform multiplication shall be specified there.

**Comment by slapin** [comment] 2017-06-01 20:45
The ordering is what should be documented. I wonder how many people after
25 years old and not doing math every day after that
remember quaternion transform order. Also all other packages I used before
used quaternion multiplication differently,
i.e. it is first time I need to know such details. The idea is that each
quaternion creates its own space and if multiplied, the rotation will be in
that space,
so if you want to control where you rotate you should put your rotation as
space around which the world will rotate.
So delta rotation was always intuitive simple thing. this is first time I
see that Quats are not that easy to use and you need to dig into math each
time
to make sure your expressions are right. Most engines handle these very
simple and very standard way, you don't need to think too much
about your rotation logic. In general it is made as simple as with
translations - you have global and local, and can rotate both which gives
predictable results.
While waving math knowledge gives boost to self-importance, that means
complication, and being complication it might be some last thing after which
a person says "what the fuck is going on?" and leaves. So yes, that should
be fucking documented unless you want people to leave without clue.
Also Urho's non-transitive multiplications are from right to left, which is
also needs to be mentioned, btw. Don't be snob about this. These are basic
things which are needed to be documented on 5 year old level. Just because
people have very different kind of expertise. Quaternion math is not among
things people need
every day.

**Comment by eugeneko** [comment] 2017-06-01 20:51
Probably you just were lucky and used libs with left-to-right order of transformation.

**Comment by OvermindDL1** [comment] 2017-06-01 21:20
>  Also all other packages I used before used quaternion multiplication differently

I'm quite curious what packages these are?  It is a mathematical property that defines this and I do not see how a package could make it different as sometimes you need one way and sometimes you need another.  I'm curious to see how they've accomplished that.

> this is first time I see that Quats are not that easy to use and you need to dig into math each time

Yeah Quaternions are a bit of a mind-f***.  ^.^  My schooling only spent a half-day on them before never mentioning them again. ^.^

Just remember, they are just like 3d Unit-Vectors, but they are 4d, keeping that in mind all math for them is the same as any other Unit Vector.  :-)

> Most engines handle these very simple and very standard way, you don't need to think too much about your rotation logic.

Sounds like you may have used transforming matrices before.  Order matters on them too but the math is significantly more simple, plus it is more that they themselves are transformed instead of transforming other things in most usage.  Sadly though they are *significantly* more computationally expensive.  I've never used a 3D rendering engine that did not have Quaternions front and center, though most also use transformation matrices as well as that is what you end up 'rotating' with a quaternion.  :-)

> you have global and local, and can rotate both which gives predictable results.

Ehhhhh teeeeechnically there is no global.  All rotations are done via some transformation space.  Local just means 'no transformation', but you can transform 'relative' to anything else, absolutely anything else that has a transformation.  Usually when engines say something is a 'Global' transform then they are actually doing (potentially *multiple*) costly relative transformations to get to some upper-layer parent node in the scenegraph.  Take the Panda3D engine, it's not efficient by any stretch but it does things very intuitively and correctly, you transform relative to something else, there is no global operation, if you want to transform relative to your root scenenode then you literally pass in your root scenenode as the relative node.  It is quite a nice design and great for teaching rendering in.  :-)

> While waving math knowledge gives boost to self-importance

Oh nothing of the sort, most of this stuff (and everything mentioned here) is fairly trivial linear algebra, high school math, but there are a number of documents on the internet for brushing up on this subject as well.

Now hard math that I tend to stay away from is symbolic calculus, that stuff is not fun to translate in to something that a computer can efficiently do...  >.>

> Also Urho's non-transitive multiplications are from right to left, which is
also needs to be mentioned

In as far as I recall, the way urho does it, direction and all, is identical to how it was taught in my classes a few decades ago so it seems correct?  Though I tend to use the Eigen library more often so I may be recalling that API...  >.>

**Comment by slapin** [comment] 2017-06-02 00:14
At least my schooling IIRC teached about multiplying a number to vector, a
vector to matrix, and not vice versa.
For me Urho math is quite a bit new.

**Comment by slapin** [comment] 2017-06-02 00:20
Yeah, that was matrices indeed. I could get Quaternion from a matrix, do
operations on it but final transform was always using matrix.
So I did not need to do tricks, yes.

**Comment by OvermindDL1** [comment] 2017-06-02 14:47
> Yeah, that was matrices indeed. I could get Quaternion from a matrix, do
> operations on it but final transform was always using matrix.
> So I did not need to do tricks, yes.

Yep, a lot of engines that do not worry too heavily about optimization just use matrices as they are easier, just a lot slower for certain kinds of work.  :-)

**Comment by slapin** [comment] 2017-06-03 01:46
Well, but LookAt still doesn't work on me. Had to replace it with some logic, but thing about Quats is more clear now. as I understand LookAt should work fine in case of Z-forward mesh, I try to use LookAt on bone node and it doesn't work (looks 180 degrees from what I need) and this is still there.

**Comment by Lumak** [comment] 2017-06-03 04:44
Still not a bug.  I see the error in your code in your 1st post.

**Comment by slapin** [comment] 2017-06-03 06:49
I don't see any bugs in my code.

**Comment by Lumak** [comment] 2017-06-03 07:19
if you can't see it, take a look inside the Node::LookAt() function and see what you're doing wrong.

**Comment by slapin** [comment] 2017-06-03 09:45
Well, not nice. Let it hang for a bit, probably it will resolve itself.

**Comment by Lumak** [comment] 2017-06-03 14:23
I don't understand the logic in your response, but ok. I'm done wasting my time. good luck to you.

**Comment by weitjong** [comment] 2017-06-03 15:33
I think we have seen enough also.

**Closed by weitjong** 2017-06-03 15:33 UTC
Labels: wontfix
