### ISSUE TITLE
cmake_vs2013.bat and other do not work when the path contains spaces

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#779] opened 2015-07-14 05:26 UTC
When the sources are located in a folder whose path contains spaces, they can not be compiled with *.bat files

**Comment by weitjong** [comment] 2015-07-14 08:23
This is a known problem. In the past both our cmake_*.bat and cmake_*.sh could not handle spaces in the source/build tree paths. The problem is fixed for cmake_*.sh by enclosing the path with double quotes. However, the same fix for cmake_*.bat has caused other unwanted side effect and causing error instead. The fix has been reverted back (See commit 365a83bda13c45f8ea213f16beace3d8ec7fd3d9) and it has not been reattempted since then. You are welcome to contribute for the fix.

**Comment by weitjong** [comment] 2015-08-31 07:37
Fixed in commit a29449a2669c1224356bf3fb6c860f1402ec0a51

**Closed by weitjong** 2015-08-31 07:37 UTC
Labels: bug
