### ISSUE TITLE
After git pull latest code , nanodbc.cpp compile error

### ISSUE THREAD

**Issue by lvshiling** [urho3d/Urho3D#1273] opened 2016-03-23 11:26 UTC
compiler: vs2013
>C:\cygwin64\home\a\Urho3D\Source\ThirdParty\nanodbc\src\nanodbc.cpp(2614): error C2039: “snprintf”: 不是“std”的成员
2>C:\cygwin64\home\a\Urho3D\Source\ThirdParty\nanodbc\src\nanodbc.cpp(2614): error C3861: “snprintf”:  找不到标识符

**Comment by weitjong** [comment] 2016-03-23 13:55
As stated in the other issue, I could not help you much here as I don't have Win7 and VS2013 build environment to reproduce your issue. However, I will be very surprise if it indeed has this kind of error because I believe nanodbc project also employs quite stringent tests on their side.

Can anyone else on Win7 help to verify this. Thanks.

**Comment by rikorin** [comment] 2016-03-23 23:13
Compiles fine for me using vs2015.

**Comment by lvshiling** [comment] 2016-03-24 02:53
add below to nanodbc.cpp and change all std::snprintf to _snprintf in nanodbc.cpp
#if defined(_MSC_VER)
	#define snprintf _snprintf
#endif

**Comment by weitjong** [comment] 2016-03-24 02:58
If you are convinced this is an issue then you may want to file it in the nanodbc project directly instead of here. Once the issue is rectified upstream, we can easily merge the fix from upstream to our master branch.

**Comment by cadaver** [comment] 2016-03-24 10:21
Can check this later (today?) on vs2013 and vs2015.

**Comment by cadaver** [comment] 2016-03-24 12:29
As a small sidenote, it's rather bold that nanodbc targets C++14+ according to their own words.

**Comment by weitjong** [comment] 2016-03-24 13:07
It was still c++11 at the time it first integrated. That's the reason internally our build system would switch on that standard when it is enabled.

**Comment by cadaver** [comment] 2016-03-24 17:31
On VS2015 Update 1 I get a different error error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt<char16_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_SDU_Mbstatet@@@std@@2V0locale@2@A)

which seems to be a known VS issue http://nanapro.org/en-us/thread.php?id=06fb9a88a17b19df9b2d28f053da5f98&stmp=1443830400041

**Comment by cadaver** [comment] 2016-03-24 20:45
Confirmed the snprintf problem on VS2013.

**Comment by weitjong** [comment] 2016-03-30 16:23
> On VS2015 Update 1 I get a different error error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt::id" (__imp_?id@?$codecvt@_SDU_Mbstatet@@@std@@2V0locale@2@A)

This is a regression issue, i.e. the issue has been workaround before in Feb but the latter changes in the source code overlook/overwrite the workaround code.

> Confirmed the snprintf problem on VS2013.

It seems like both GCC (with C++11 standard enabled) and VS2015 understand std::snprintf. While VS2013 doesn't and even worse it only understands _snprintf. What to do? So many standards, so many compilers, so many versions to support?

**Comment by cadaver** [comment] 2016-03-30 19:33
To me it's fine to not support VS2013 in this case, as the library targets C++11 and newer and VS2013 seems *not* to be compliant. Also if the library authors themselves don't view this as an issue, then it's an ungrateful job to maintain additional fixes in Urho.

**Comment by OvermindDL1** [comment] 2016-03-30 19:48
Plus standards are called standards for a reason.

**Comment by weitjong** [comment] 2016-03-31 04:20
I have my fix for the VS2015 linker error on my Windows 10 partition. Will check in that the next time I reboot into it. After sleeping on the VS2013 snprintf issue, I also come the same conclusion. So closing this issue as won't fix.

**Closed by weitjong** 2016-03-31 04:20 UTC
Labels: bug
