### ISSUE TITLE
[Emscripten] Performance Issues

### ISSUE THREAD

**Issue by hdunderscore** [urho3d/Urho3D#1259] opened 2016-03-19 04:34 UTC
It seems that the recent updates have some big issues with performance (eg, Skeletal Animations). I haven't had a chance to investigate thoroughly, anyone have clues?

**Comment by weitjong** [comment] 2016-03-19 05:13
There are a few things I can think of. The new detection mechanism should not be the root cause because for Emscripten compiler the result is almost identical whether it is auto-generated or pre-generated. But as you know we have changed the way how we build SDL now for Web platform. So you might try to use back the SDL2 port from Emscripten-port to see if it makes any difference. If it does then it means those changes Emcripten devs made in their SDL2 Emscripten-port are critical. We chosen not to merge those changes from their repo into ours unless they are proven absolutely necessary (see discussion in the forum). You might also try to use older Emscripten version (or the one you have used before). I have made a mistake during SDL-2.0.4 upgrade work where I also upgraded my Emscripten version and since Emscripten might have regression issue on their part (see https://groups.google.com/forum/#!searchin/emscripten-discuss/slow/emscripten-discuss/u8YSfKVP8Es/ums5DnYoAgAJ), I could not make any meaningful performance comparison. I have no idea whether the I/O performance problem has been resolved in 1.36 or not.

I will log another separate issue in GitHub to improve our current CTest to also check on the FPS as one of the criteria for passing the test.

**Comment by weitjong** [comment] 2016-03-21 04:39
Fortunately none of the above is true cause. It was caused by something totally unrelated. We have at the same time attempted to standardize the checks on compiler toolchain with a new module. Some how it erroneously detects that Emscripten is capable of SSE/SSE2 now. Turning off the SSE in the build give the performance back.

**Closed** 2016-03-21 04:56 UTC
Labels: bug
