### ISSUE TITLE
Building issues persist on MinGW-w64 with D3D9 and D3D11

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#1254] opened 2016-03-17 22:35 UTC
Updated to the latest to get weitjong's commit to fix the MinGW build, but still having problems.

CMake Error at CMake/Modules/FindDirectX.cmake:83 (message):
  Could not find MinGW system root.  Use MINGW_SYSROOT environment variable
  or build option to specify the location of system root.

Specifying MINGW_SYSROOT manually on the command line as C:/mingw64, configuration proceeds as expected until I end up with the exact same errors as noted in issue #1247  with D3D not found:

CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find DirectX using MinGW default search paths (missing: D3D)

I am invoking the build process as:

cmake_mingw Build -DURHO3D_64BIT=1 -DURHO3D_LUAJIT=1 -DURHO_3DOPENGL=0 -DMINGW_SYSROOT=c:/mingw64

When building with -DURHO_3DOPENGL=1 for a GL build, the process succeeds. Embedded in the output text scroll is the line:

-- Found DirectX: TRUE  found components:  DInput DSound XInput missing components:  XAudio2

So clearly it's finding SOME of DirectX, even if it can't find D3D.

I'm not very skilled at the CMake build system, so I'm not sure what I can do to help track this down. But if you need any further information from me, let me know. In the meantime, I've rolled back some commits and am continuing to use the older version of Urho for work on my game.

**Comment by furyn** [comment] 2016-03-17 23:45
I got the errors as you. The DirectX error was fixed by installing VS2015 community (still using codelite + MinGW). When I go to build the project however, I get the same MINGW_SYSROOT error?

**Comment by weitjong** [comment] 2016-03-18 05:04
I think it is because there are more than one party producing the MinGW software package for Windows host system. The MinGW package that I installed seems to be working fine with the fixed FindDirectX.cmake module. I just use this command ```rake cmake mingw URHO3D_LUAJIT=1 URHO3D_OPENGL=0``` to generate a build tree that matches your build configuration. I did not specify MINGW_SYSROOT explicitly as for my case it is auto-detected correctly.

```
//Path to MinGW system root (MinGW on Windows host only)
MINGW_SYSROOT:PATH=C:/Program Files/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32
```

Note that my sysroot even has a space in the path and yet it is still working correctly.  And if I did a list dir, I got the expected subdirectories, namely "include/" and "lib/". This is where the headers and libraries are being searched for.

```
weitjong@Igloo MINGW64 ~/ClionProjects/urho3d/Urho3D (master)
$ ls "C:/Program Files/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32"
bin/  include/  lib/
```

It could be that other MinGW packages for Windows do not install the same way. So, the current sysroot detection may not work yet for them all. Of course, the actual path is not being hard-coded here. The path is derived from where MinGW found the d3dcompiler.h (if it could actually find it).

You can try to output those intermediate CMake variable using message() command to help to troubleshoot why the current logic does not work for your MinGW installation. It is not possible for me alone to make it works 100% well for all the MinGW out there. But if you help to provide what is the detected MINGW_SYSROOT variable value and list the actual directory being pointed by this variable value then I may be able to help you to get it through.

**Comment by weitjong** [comment] 2016-03-18 05:16
Or we could revert back everything. Just assume MinGW would have everything. In the past we don't stop at the CMake configuration/generation phase because we don't check anything at all for MinGW. However, some of you actually would have problem building later due to missing headers or libraries. In the past we also just blindly link against libd3dcompiler.a (unversioned) and make it an assumption that it is an import library for d3dcompiler_46.dll and would attempt to find this version of the DLL and install it beside the target binary. In the new module, we do away with all these assumption. We also stop user at his/her track while configuring/generating the build tree if it does not pass the checks. As the logic is new, I am not surprise to have teething problem. If anyone could do it better, also be my guest to fix it by sending a PR directly.

**Comment by hdunderscore** [comment] 2016-03-18 09:25
In my case continuing on without MINGW_SYSROOT doesn't prevent me from building urho, although cmake warns of potential problems. How poor of an assumption is it to assume the parent of the CMAKE_C_COMPILER directory is the MINGW_SYSROOT? eg:
```cmake
if (NOT EXISTS ${MINGW_SYSROOT})
  get_filename_component(MINGW_SYSROOT ${CMAKE_C_COMPILER} DIRECTORY)
  get_filename_component(MINGW_SYSROOT ${MINGW_SYSROOT} DIRECTORY)
endif ()```

**Comment by hdunderscore** [comment] 2016-03-18 12:15
Trying to build emscripten with now, seems like there's more to the issue than that.

**Comment by weitjong** [comment] 2016-03-18 14:55
> Trying to build emscripten with now, seems like there's more to the issue than that.

Probably you need to raise another GitHub issue for this. Also please elaborate more. Over here and on Travis CI, the builds seem to go fine with Emscripten master 1.36. For sure, I don't have time to profile all the platforms while doing SDL-2.0.4 upgrade, so there could be performance or other runtime issues left undetected. SDL 2.0.3 -> 2.0.4 is a major upgrade in any case, barring any regression on Emscripten side. I learnt they have issue with slow i/o performance after 1.33.

**Comment by weitjong** [comment] 2016-03-18 15:14
> n my case continuing on without MINGW_SYSROOT doesn't prevent me from building urho, although cmake warns of potential problems. How poor of an assumption is it to assume the parent of the CMAKE_C_COMPILER directory is the MINGW_SYSROOT?

For me, sysroot is a path to a parent directory containing the "include" and "lib" subdirs. Your approach might work but so does what I have now implemented where it tries to find a path to an include file then back track to its parent directory. However, they are both not bullet proof because we still rely on the knowledge of how many level we need to back track. On Linux side, all is not rosy as well. If you look at mingw.toolchain.cmake, we are actually making two big assumptions there: if looks like Redhat then do this and if looks like Debian then do that. Now on Windows side, I really have no idea how many variants out there yet. Therefore, the module is designed to let user to supply the MINGW_SYSROOT externally as a stop gap. In other words, for those that still failed, please try to find a good candidate for the sysroot (again it is a path to a parent dir containing lib and include subdirs) and supply it explicitly.

**Comment by cadaver** [comment] 2016-03-18 19:09
Can confirm similar errors as @JTippets on mingw-w64 4.9.2. Will try the newest version next.

**Comment by JTippetts** [comment] 2016-03-18 19:29
The way my MinGW install is structured, in the root directory (c:/mingw64) there lies a bunch of different folders, including an include, bin and lib folder. There is also a folder named x86_64-w64-mingw32 which ALSO has include, bin and lib folders inside. Passing the path to the root of the MinGW install (c:/mingw64) does not work. However, if I pass the path to this internal folder (x86_64-w64-mingw32) then it does work. Which makes sense, because the D3D library is found within the include/lib folders in this inside folder, but which doesn't make sense because this internal folder is not really the root of the MinGW install. Still, it DOES work to pass this inside folder, and the job of determining the path to this inside folder from the base install might be difficult, since the name of the internal folder can change (IIRC).

**Comment by cadaver** [comment] 2016-03-18 20:47
Somewhat unrelated issue, but since we're already talking of DirectX and MinGW, on D3D11 + MinGW 4.9.2 I also got the blank screen bug (talked about on the forum) when Urho uses D3DCompiler_47.dll.

**Comment by JTippetts** [comment] 2016-03-18 20:55
Another related issue: When building with LuaJIT configured, the generation step for tolua++ fails due to undefined MINGW_SYSROOT. The build process proceeds well, building the ThirdParty libraries through LibCpuid, but when it gets to the tolua++ stage, I get:

[ 50%] Built target LibCpuId
Scanning dependencies of target tolua++
[ 51%] Creating directories for 'tolua++'
[ 51%] No download step for 'tolua++'
[ 51%] No patch step for 'tolua++'
[ 51%] No update step for 'tolua++'
[ 51%] Performing configure step for 'tolua++'
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: C:/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at C:/Users/Joshua/Documents/Projects/Urho3D/CMake/Modules/Urho3D-CMake-common.cmake:105 (message):
  Could not use MKLINK to setup symbolic links as this Windows user account
  does not have the privilege to do so.  When MKLINK is not available then
  the build system will fallback to use file/directory copy of the library
  headers from source tree to build tree.  In order to prevent stale headers
  being used in the build, this file/directory copy will be redone also as a
  post-build step for each library targets.  This may slow down the build
  unnecessarily or even cause other unforseen issues due to incomplete or
  stale headers in the build tree.  Request your Windows Administrator to
  grant your user account to have privilege to create symlink via MKLINK
  command.  You are NOT advised to use the Administrator account directly to
  generate build tree in all cases.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


CMake Error at C:/Users/Joshua/Documents/Projects/Urho3D/CMake/Modules/FindDirectX.cmake:83 (message):
  Could not find MinGW system root.  Use MINGW_SYSROOT environment variable
  or build option to specify the location of system root.
Call Stack (most recent call first):
  C:/Users/Joshua/Documents/Projects/Urho3D/CMake/Modules/Urho3D-CMake-common.cmake:478 (find_package)
  CMakeLists.txt:51 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Joshua/Documents/Projects/Urho3D/BuildLuaJIT/Source/Urho3D/tolua++-prefix/src/tolua++-build/CMakeFile
s/CMakeOutput.log".
Source\Urho3D\CMakeFiles\tolua++.dir\build.make:104: recipe for target 'Source/Urho3D/tolua++-prefix/src/tolua++-stamp/t
olua++-configure' failed
mingw32-make[2]: *** [Source/Urho3D/tolua++-prefix/src/tolua++-stamp/tolua++-configure] Error 1
CMakeFiles\Makefile2:1426: recipe for target 'Source/Urho3D/CMakeFiles/tolua++.dir/all' failed
mingw32-make[1]: *** [Source/Urho3D/CMakeFiles/tolua++.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

This only occurs on a LuaJIT build; a vanilla Lua build completes successfully.

**Comment by JTippetts** [comment] 2016-03-18 21:38
Further issue: upon successful completion of the build of my game's EXE, on execution I get "The program can't start because D3DCOMPILER_47.dll is missing from your computer." I seem to remember previously that the Urho3D build would unpack d3dcompiler_46.dll into the bin folder (and certainly, the only place that d3dcompilier_46.dll exists is within various Urho-related project folders on my hard drive). No such unpacking is being done now for _47.

**Comment by cadaver** [comment] 2016-03-18 22:45
Tested with the mingw-w64 5.3.0. This too required setting sysroot manually to a similar path as above. The versions I acquired were from
https://sourceforge.net/projects/mingw-w64/?source=typ_redirect
with all other installer settings except version kept at default.

**Comment by azzvx** [comment] 2016-03-19 01:42
I got an error when I tried to make a LuaJIT build either.
    Could NOT find DirectX using MinGW default search paths (missing: D3D)
But it's completes successfully when I set URHO3D_LUAJIT to 0.

**Comment by JTippetts** [comment] 2016-03-19 02:41
I was able to "fool" the build process by removing libd3dcompiler_47.a from my MinGW lib folder and re-configuring Urho so that when it searches for D3D, it fins _46 instead. Now I don't get the "missing dll", and the Urho build process builds d3dcompiler_46.dll as before. However, on execution I get "The application was unable to start correctly (0xc000007b)" which leads me to believe that somewhere it is mixing 32 bit and 64 bit. (I build with -DURHO3D_64BIT=1). Using Dependency Walker on the Urho3DPlayer.exe file indicates that the d3dcompiler_46.dll is the 32-bit culprit.

**Comment by weitjong** [comment] 2016-03-19 03:01
I think I have bettet idea now of the issue. Thanks for all the reports. @JTippetts or others , could you paste the first few lines of the file content found in "find-mingw-sysroot" or something sounds like that in the root of your build tree. Btw, mingw root and sysroot should be different on my book. I am also just learning about all these cross-compiling thing, so I could be wrong, but sysroo is a short hand of system root. Also have an idea why LuaJIT throws the error again, ithas been configured as CMake external project. As for _47.a or _46.a, I have commented in the forum. Probably we need a build option for this. Still in my bed :smile:

**Comment by JTippetts** [comment] 2016-03-19 03:18
Here is the contents of that file in its entirety: http://pastebin.com/e9AnQ05r

Also, regarding the d3dcompiler_xx.dll issue: I have a build of Urho3DPlayer.exe from before all of this kerfuffle, and running Dependency Walker on that exe, with the d3dcompiler_46.dll file alongside it, I get this information line for the d3dcompiler dll:

http://imgur.com/yZ9mrM0

You can see that dependency walker shows it as an x64 module. Now, if I copy that .dll to a folder with Urho3DPlayer.exe built today and run dependency walker, I get this:

http://imgur.com/7Nw0thz

Same exact .dll, only now Dependency Walker thinks it's x86 instead of x64. So something is different in how Urho3DPlayer.exe sees that DLL, and it's causing it to fail on startup.

**Comment by weitjong** [comment] 2016-03-19 03:55
Thanks for that. I think I see the culprit now in your file. Could you also tell me what's the value of MINGW_SYSROOT that works for you.

As for why it worked for you in the past,  I would say it is just a mere coincidence. The walker clearly shows you were actually d3dcompiler_43.dll instead of _46. I already explained why this is so. If you delete the _46.dll along side the old .exe, you can see it would not look for it. What happened, I think, it searched the system paths and found one with the right ABI by coincidence. The same thing happened with new .exe, only this time it found _46.dll with wrong ABI.

**Comment by hdunderscore** [comment] 2016-03-19 04:20
Probably you need to raise another GitHub issue for this. Also please elaborate more. Over here and on Travis CI, the builds seem to go fine with Emscripten master 1.36. 

My bad, previously I was able to improperly use make without going through emmake so that was causing an issue with these updated cmake scripts. Using emmake works as expected.

**Comment by JTippetts** [comment] 2016-03-19 04:22
C:/mingw64/x86_64-w64-mingw32 is what I need to use for sysroot.

**Comment by JTippetts** [comment] 2016-03-19 04:41
I suspect that my system only has a dll for up to d3dcompiler_43 because I only have the June 2010 DirectX SDK installed, and have not installed the Windows 8 SDK.

**Comment by weitjong** [comment] 2016-03-19 05:21
What you have in your host system does not really much actually. I believe you want to let others run your binaries on their Windows and you cannot be sure of what they have or don't have. Seriously I actually not sure how you guys on Windows manage this DLL hell.

**Comment by weitjong** [comment] 2016-03-19 05:33
Sorry for being so negative in my earlier comment. This is what I do know. If you use libd3dcompiler_43.a or libd3dcompiler.a then your target binary will need d3dcompiler_43.dll during runtime. In order for others to execute your binary then you must ensure d3dcompiler_43.dll is available along side the binary because you cannot assume this DLL version is available in your users default system path. Now our new module has actually designed to do the right thing. It will search the DLL with the right version in **your** host system and copy it to the same location where target binary reside, but only when the module is able to find it. Most of the case, it won't find it without any hint from you. See the comment regarding DIRECT3D_DLL_REDIST_SEARCH_PATHS in the module itself.

**Comment by weitjong** [comment] 2016-03-19 11:32
Feel free to reopen this issue again if the issue persists instead of creating a new one.

**Closed** 2016-03-19 11:31 UTC
Labels: bug

**Comment by weitjong** [comment] 2016-03-19 11:44
One more thing. I am still hesitate to add a new build option to control the MinGW d3dcompiler library search order or preferences. It is hard-wired to look for _47.a, _46.a, _43.a, _42.a. Both me and cadaver has confirmed _47.a (or _47.dll) is problematic with MinGW + D3D11 build configuration. User with recent MinGW installation might also want to use specific version instead of what is the latest in the MinGW installation. Having said that, I also want to keep thing simple. KIV.
