### ISSUE TITLE
cmake codeblocks win32 mingw

### ISSUE THREAD

**Issue by dev-brother** [urho3d/Urho3D#1090] opened 2015-12-12 14:02 UTC
Hi Guys

I recently tried to build urho3d-1.5 on win7 using the cmake_codeblocks.bat file.

It fails in cmake_gui as well as in cmake command line. Do you have an update on this file for codeblocks compiling with mingw?

The script also uses vs2010 compiler, but doesn't give option to compile with mingw on windows.

Output on fail:
```

D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32>cmake_codeblocks.bat mingw_
sysroot="C:\Program Files (x86)\CodeBlocks\MinGW\bin"
-- The C compiler identification is MSVC 16.0.30319.1
-- The CXX compiler identification is MSVC 16.0.30319.1
-- Check for working C compiler using: Visual Studio 10 2010
-- Check for working C compiler using: Visual Studio 10 2010 -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/CMakeTestCCo
mpiler.cmake:61 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  10.0/VC/bin/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: D:/Resources/MyCode/Urho/Urho3D-1.5/Urho3D-1.5-Win32/mingw_sysroo
t/CMakeFiles/CMakeTmp



  Run Build
  Command:"C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe"
  "cmTC_996ce.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=10.0"

  Microsoft (R) Build Engine version 4.0.30319.17929

  [Microsoft .NET Framework, version 4.0.30319.17929]

  Copyright (C) Microsoft Corporation.  All rights reserved.



  Build started 2015/12/12 03:57:37 PM.

  Project
  "D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32\mingw_sysroot\CMakeFiles
\CMakeTmp\cmTC_996ce.vcxproj"
  on node 1 (default targets).

  PrepareForBuild:

    Creating directory "cmTC_996ce.dir\Debug\".
 -- Configuring incomplete, errors occurred!
See also "D:/Resources/MyCode/Urho/Urho3D-1.5/Urho3D-1.5-Win32/mingw_sysroot/CMa
keFiles/CMakeOutput.log".
See also "D:/Resources/MyCode/Urho/Urho3D-1.5/Urho3D-1.5-Win32/mingw_sysroot/CMa
keFiles/CMakeError.log".
   Creating directory "D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32\ming
w_sysroot\CMakeFiles\CMakeTmp\Debug\".

  InitializeBuildStatus:

    Creating "cmTC_996ce.dir\Debug\cmTC_996ce.unsuccessfulbuild" because "Always
Create" was specified.

  ClCompile:

    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\CL.exe /c /Zi /W3
 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /
D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTC_996ce.
dir\Debug\\" /Fd"cmTC_996ce.dir\Debug\vc100.pdb" /Gd /TC /analyze- /errorReport:
queue testCCompiler.c
    Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80
x86
    Copyright (C) Microsoft Corporation.  All rights reserved.

    cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_IN
TDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScop
e /Fo"cmTC_996ce.dir\Debug\\" /Fd"cmTC_996ce.dir\Debug\vc100.pdb" /Gd /TC /analy
ze- /errorReport:queue testCCompiler.c

    testCCompiler.c

  ManifestResourceCompile:

    C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\rc.exe /nologo /fo"c
mTC_996ce.dir\Debug\cmTC_996ce.exe.embed.manifest.res" cmTC_996ce.dir\Debug\cmTC
_996ce_manifest.rc

  Link:

    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\link.exe /ERRORRE
PORT:QUEUE /OUT:"D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32\mingw_sysr
oot\CMakeFiles\CMakeTmp\Debug\cmTC_996ce.exe" /INCREMENTAL /NOLOGO kernel32.lib
user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib co
mdlg32.lib advapi32.lib /MANIFEST /ManifestFile:"cmTC_996ce.dir\Debug\cmTC_996ce
.exe.intermediate.manifest" /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /D
EBUG /PDB:"D:/Resources/MyCode/Urho/Urho3D-1.5/Urho3D-1.5-Win32/mingw_sysroot/CM
akeFiles/CMakeTmp/Debug/cmTC_996ce.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE
 /NXCOMPAT /IMPLIB:"D:/Resources/MyCode/Urho/Urho3D-1.5/Urho3D-1.5-Win32/mingw_s
ysroot/CMakeFiles/CMakeTmp/Debug/cmTC_996ce.lib" /MACHINE:X86 cmTC_996ce.dir\Deb
ug\cmTC_996ce.exe.embed.manifest.res
    cmTC_996ce.dir\Debug\testCCompiler.obj  /machine:X86 /debug

  LINK : fatal error LNK1123: failure during conversion to COFF: file invalid
  or corrupt
  [D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32\mingw_sysroot\CMakeFiles
\CMakeTmp\cmTC_996ce.vcxproj]


  Done Building Project
  "D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32\mingw_sysroot\CMakeFiles
\CMakeTmp\cmTC_996ce.vcxproj"
  (default targets) -- FAILED.



  Build FAILED.




  "D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32\mingw_sysroot\CMakeFiles
\CMakeTmp\cmTC_996ce.vcxproj"
  (default target) (1) ->

  (Link target) ->

    LINK : fatal error LNK1123: failure during conversion to COFF: file invalid
or corrupt [D:\Resources\MyCode\Urho\Urho3D-1.5\Urho3D-1.5-Win32\mingw_sysroot\C
MakeFiles\CMakeTmp\cmTC_996ce.vcxproj]



      0 Warning(s)
      1 Error(s)



  Time Elapsed 00:00:00.38





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)

```

**Comment by weitjong** [comment] 2015-12-12 15:04
Your error at the beginning clearly shows that you have PATH environment variable problem. It appears your host system also has MSVC installed and its binaries are in the PATH entries. For MinGW compiler to work, you have to adjust the PATH accordingly so that it can be found by CMake. Usually MinGW installation provides a batch file which would set up the PATH environment variable before launching a command prompt window. Invoking cmake_mingw.bat or cmake_codeblock.bat in this window should fix this kind of error. Good luck.

**Comment by dev-brother** [comment] 2015-12-13 20:14
I got some very wierd behaviour from the bat file cmake_mingw.bat.
First off, cmake_gui works fine on ubuntu 14. Had no problems with cmake generating whats needed without resorting to the bash scripts.

On windows, it's a different kettle of fish. I uninstalled VS2010. Left VS2008 still installed. Then specified paths to:
```
MINGW_DIR
CMAKE_DIR
``` 
And added both to PATH environment variable.

Now hears is where it gets wierd. Running...
```
cmake_mingw.bat build
```
or
cmake_mingw.bat build -demscripten
```
I get the project compiling with VS2008!? Successfully, bar for two headers! 

I am trying to use the MINGW that comes with codeblocks, but the bat file just won't play nicely and keeps trying to compile with whatever VS is installed.

Woulda used cmake_gui, but resorted to the using the bat files when cmake_gui failed repeatedly.

What is your setup for codeblocks/mingw/win7? Can you give some details, and whether you are using a standalone download of mingw?

Thanks for the help.

dev-brother

**Comment by dev-brother** [comment] 2015-12-13 20:17
For ref here is cmake_gui output on win.
```
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Configuring incomplete, errors occurred!
```

**Comment by weitjong** [comment] 2015-12-14 05:17
With the assumption that there are nothing wrong with our CMake scripts, the root cause of your problem is still within your Windows host system. Our convenient batch files simply invokes ```cmake``` (CLI) to do the actual work. Whether CLI or GUI, they are just the same, i.e. if you get problem on one then you will get problem on the other.

You do not need to uninstall VS from your host system. Basically what you need to ensure is to let CMake able to find the compiler toolchain that you want to use whether it is MinGW, MSVC, or any others. And to do that you have to adjust the environment variable(s), usually it is just PATH env-var, correctly for the selected compiler toolchain.

We have received reports from our users before that they have better success with standalone MinGW installation, especially MinGW-W64, The TDM-GCC compiler toolchain provided by C::B has been known to cause problems to our users, although I have not verified that personally. Perhaps, that was your problem as well. Personally I use standalone MinGW-W64 installation and use a batch file that it shipped together which set the env-vars as necessary before launching a CMD shell. I have mentioned this in my earlier comment.

In my opinion your problem is not unique to Urho3D project. With the incorrect host environment, you would get CMake error regardless of which project you try to configure. And if you suspect others might have encountered the same problem as yours then you are right. If you do a Google search on our support forums then you should be able to find similar issues have been reported in the past with their resolution. In view of that, I am closing this issue from our tracker for now. Feel free to reopen it if you are sure your problem was caused by our CMake scripts.

**Closed by weitjong** 2015-12-14 05:17 UTC
Labels: question
