### ISSUE TITLE
Compiling with Urho3D as library fails

### ISSUE THREAD

**Issue by hjmediastudios** [urho3d/Urho3D#866] opened 2015-08-30 23:19 UTC
My issues with using Urho3D as a library have popped back up again, as I'm suddenly getting the following messages when compiling with no project changes, just an Urho3D update from the latest revision. This occurs on an Ubuntu 14.04 x64 computer even after I `make clean` and remove the CMake cache.

```
:-1: error: /usr/local/lib/Urho3D/libUrho3D.a(SDL_syssem.c.o): undefined reference to symbol 'sem_getvalue@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0:-1: error: error adding symbols: DSO missing from command line
```

**Comment by rasteron** [comment] 2015-08-31 09:11
Have you tried regenerating a separate CMake build? or CMakeCache.txt deleted?

**Comment by cadaver** [comment] 2015-08-31 09:45
Could this be related to the recent change to pthread library linking?

**Comment by hjmediastudios** [comment] 2015-08-31 14:07
Rasteron- Yes to both. I suspect it *is* a pthread-related bug- the linker seems to be omitting certain libraries or ordering them incorrectly. My project itself builds correctly, but when Urho3D's library works its magic (compiling, linking) then the overall build fails.

**Comment by weitjong** [comment] 2015-08-31 14:26
I have a 64-bit Ubuntu 14.04 VM too and I haven't used the VM for quite some time. Just now I started it and pulled from Urho3D master branch. However, I was able to build the library and the samples with a single ```rake make``` command, i.e. it reconfigured my existing build tree and build from there just fine.

Unless you are able to list out the exact step by step on how to reproduce your build issue, I am afraid we cannot help you much here.

**Comment by hjmediastudios** [comment] 2015-08-31 14:32
It's not a problem with building Urho3D itself- I can run the editor and samples just fine. It's when I try to build my project, using the setup described in [this documentation](http://urho3d.github.io/documentation/HEAD/_using_library.html), that uses Urho3D as an external library. It worked with previous Urho3D builds, but upon pulling the latest Urho3D from here and building it (which went through without problems), my project now fails to build.

**Comment by weitjong** [comment] 2015-08-31 15:25
That still doesn't say much, unless your existing project setup was really that old like it was setup as per Urho3D version prior to 1.4.

**Comment by hjmediastudios** [comment] 2015-08-31 16:44
Nope, I'm setting my project up exactly like it says in the most current documentation, and I still get this.

**Comment by hjmediastudios** [comment] 2015-08-31 16:59
All right, I've got my project to compile by adding -lpthread at the end of the link.txt file in my CMake-generated directory. It seems that the pthread library is required by Urho3D but the default build scripts don't take this into account.

**Comment by cadaver** [comment] 2015-08-31 18:08
This is the recent modification in Urho3D-CMake-common.cmake which setups pthread linking and the REENTRANT define, is it possible it is getting omitted for an external project?

```
            set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")     # This will emit '-DREENTRANT' to compiler and '-lpthread' to linker on Linux and Mac OSX platform
            set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread") # However, it may emit other equivalent compiler define and/or linker flag on other *nix platforms
```

**Comment by weitjong** [comment] 2015-09-01 06:07
That change is part of the commit d29d5f188e35ae8567011926ff32f447001bccff. The commit made two integral changes to the Urho3D-CMake-common module. And since the changes are in the common module, they will be applied to both Urho3D project and external projects using Urho3D library (reusing our Urho3D build system). The new project scaffolding test has been done continuously in our CI build, so we can rule out that it has caused problem to external project or the CI build won't pass at all.

I agree that change mentioned by @cadaver seems to be the one causing the build issue. Having said that, I think there must be something else at play here and that something else was the actual root cause, perhaps something specific to OP project setup. Without OP elaborating on the steps to reproduce, I cannot figure that out.

Let's just assume for a moment that his project setup used symlink to our CMake modules. After the pull, his project also had the latest version of the common module, so no problem. Now assume for a second that his project setup used soft-copy instead, which means his project still used the old common module after git pull, however, since the old modules were working fine from the beginning then there should be no problem there too. The pthread was explicitly link in old module and is now implicitly link in new module. Either way it should just work. I don't know how his project could end up in neither here nor there situation.

**Comment by weitjong** [comment] 2015-09-07 15:44
I am closing this issue for now as there is no more updates since the last comment. Feel free to reopen.

**Closed by weitjong** 2015-09-07 15:44 UTC
