### ISSUE TITLE
Android native glue bugs

### ISSUE THREAD

**Issue by kabukunz** [urho3d/Urho3D#2248] opened 2018-01-31 20:06 UTC
While setting up Android to work with 1.7, I happened to find a couple bugs. In com/github/urho3d/Urho3D.java line 71 the statement:

> String[] array = libraryNames.subList(startIndex, libraryNames.size()).toArray(new String[libraryNames.size() - startIndex]);

fails with IndexOutOfBoundsException. The culprit appears to be in line 62 where stamement:         

> int startIndex = libraryNames.indexOf("Urho3DPlayer");

set startIndex to -1. Adding the statement:

> if (startIndex==-1) startIndex = 0;

solves the problem. 
The error triggers another bug in org/libsdl/app/SDLActivity.java, line 158, where, strangely, exception catching is returning null in e.getMessage() (possibly an android java system bug). Can be fixed by adding the statement:

> if (errorMsgBrokenLib == null)errorMsgBrokenLib="An Exception occurred while loading app";

I can push the fix if you need

**Comment by weitjong** [comment] 2018-01-31 20:48
Thanks for bringing this up to our attention. I believe the first issue would only surface when the sample Android build is configured with AngelScript build option turned off. However, the proposed fix is not general enough because we cannot assume the startIndex can be reset to 0 if that is the case. This is because in other build combination, like build with SHARED Urho lib type then the first position may be `libUrho3D.so` which is the shared library itself that should not listed in the sample list; or build with non-default ANDROID_STL runtime or build with other 3rd-party shared library may all occupied the top place and they all should be listed in the UI for user to choose. So, the "Urho3DPlayer" also serves as a sentinel here separating the *.so that should not be listed with those *.so from our samples. So, the fix might be if the index is -1 then do another search using the name of the first sample.

**Comment by weitjong** [comment] 2018-01-31 21:00
Forget to address the second issue. The NPE issue will be the thing of the past after we migrate the Android sample launcher app to Kotlin.

**Comment by weitjong** [comment] 2018-02-26 18:32
The issue is still valid. The Android build should work out of the box with or without AS enabled.

**Comment by weitjong** [comment] 2018-07-08 04:37
This issue is now fixed in the `gradle-kotlin-dsl` dev branch. That dev branch will be merged soon. To safe me time to come back to issue log again later, I am closing it now.

**Closed by weitjong** 2018-07-08 04:37 UTC
Labels: bug
