### ISSUE TITLE
Cmake does not correctly configure VS2015

### ISSUE THREAD

**Issue by moonshineTheleocat** [urho3d/Urho3D#861] opened 2015-08-29 14:25 UTC
Yeah, it seems like that VS2015's project file is not correctly configured by CMake.

Through all the samples, the include paths are invalid even though they should technically work.

All LuaAPI files are non-existant on the disk, however Visual studio believes they should exist.

http://i.imgur.com/kUKjBTm.png
http://i.imgur.com/mMyzBVl.png

I haven't tried using Visual Studio's 2013 yet.

**Comment by weitjong** [comment] 2015-08-29 15:20
This could be a duplicate of #831.

**Comment by 1vanK** [comment] 2015-08-29 15:36
As far as I know, the console version of cmake in Windows works incorrect if a path to the sources contains spaces

**Comment by cadaver** [comment] 2015-08-29 17:20
Added note to the build documentation of the path with spaces issue. Verified (again) that a path with spaces fails on VS2015, while a path without spaces builds successfully.

**Comment by moonshineTheleocat** [comment] 2015-08-29 19:47
I should note here that I didn't use the console. I used Cmake. And this is Windows 10 x64bit

I tried both 32, and 64 but didn't have any luck.

The problem is coming from #includes where the enviorment can not find the file.

There is also supposed to be files such as...
AudioLuaAPI.CPP
CoreLuaAPI.cpp
EngineLuaAPI.cpp
ect

But they don't exist. I guess something is supposed to generate those?

**Comment by moonshineTheleocat** [comment] 2015-08-29 19:55
Alright. Nevermind.

So from the looks of things, you need to compile it regardless of any errors you find.

**Closed** 2015-08-29 20:59 UTC

**Comment by weitjong** [comment] 2015-08-31 07:43
The spaces in paths should now be supported in all the target platforms.

> So from the looks of things, you need to compile it regardless of any errors you find.

You didn't say the "error" was before you run any build. The so-called generated files are truly only generated on the fly when the build is running. Sometimes, our build system even builds a host tool on the fly and use the tool to generate those files. So, IDE only has placeholders initially before the initial build run takes place.
