### ISSUE TITLE
Error when initially building Urho

### ISSUE THREAD

**Issue by jonyTF** [urho3d/Urho3D#1802] opened 2017-02-06 05:31 UTC
When building Urho, at around 37%, this error arises:

`C:/Users/Jonathan/Desktop/Urho3D-1.6/Source/ThirdParty/Bullet/src/LinearMath/btScalar.h: In member function 'virtual void btConnectivityProcessor::processTriangle(btVector3*, int, int)':
C:/Users/Jonathan/Desktop/Urho3D-1.6/Source/ThirdParty/Bullet/src/LinearMath/btScalar.h:448:16: internal compiler error: Segmentation fault
  return sqrtf(y);
                ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://sourceforge.net/projects/mingw-w64> for instructions.
mingw32-make.exe[2]: *** [Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj] Error 1
mingw32-make.exe[1]: *** [Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
Source\ThirdParty\Bullet\CMakeFiles\Bullet.dir\build.make:787: recipe for target 'Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj' failed
mingw32-make.exe[2]: Leaving directory 'C:/Users/Jonathan/Desktop/Urho3D-1.6/Build'
CMakeFiles\Makefile2:1239: recipe for target 'Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'C:/Users/Jonathan/Desktop/Urho3D-1.6/Build'
C:/Users/Jonathan/Desktop/Urho3D-1.6/Build/Makefile:148: recipe for target 'all' failed
Process terminated with status 2 (9 minute(s), 10 second(s))
4 error(s), 3 warning(s) (9 minute(s), 10 second(s))`

More pictures of the error:
![error1](http://i.imgur.com/WqXDbQR.png)
![error2](http://i.imgur.com/HFZuBha.png)

Why is this happening to me? Is this a perhaps problem with minGW rather than Urho?

For reference, I am following this tutorial: http://urho3d.wikia.com/wiki/Building_Urho_1.5_(Windows_10,_MinGW/GCC) 
I am also using Urho 1.6
`

**Comment by weitjong** [comment] 2017-02-06 07:15
Duplicate of #1552

**Closed by weitjong** 2017-02-06 07:15 UTC
