### ISSUE TITLE
URHO3D_MACOSX_BUNDLE option does not find Resource folders

### ISSUE THREAD

**Issue by danhambleton** [urho3d/Urho3D#1655] opened 2016-10-17 15:40 UTC
Building the samples with URHO3D_MACOSX_BUNDLE=1 and using Xcode as the generator will create bunch of apps packaged up with Plists, icons, and the Data/CoreData folders. However, on start, the app cannot find the Data/CoreData folders. 

I've tried quite a few different combos of resource locations and custom resource prefixes. The only thing that kind of works is to provide the full, absolute, path to the resources. This is of course not really a solution, since it assumes a single location for the app.

What I really don't understand is if my app contents looks like this:

-App
--Contents
---MacOS
----AppExecutable
---Resources
----CoreData
----Data

and I provide the custom Resource prefix "../Resources", why the app can't find the Resources. I suspect something is up with FileSystem::CurrentDir() but I don't know.

**Comment by weitjong** [comment] 2016-10-17 15:55
All I can say is it used to work. Have you try to debug it?

**Comment by weitjong** [comment] 2016-10-17 16:02
Also make sure you are using the latest CMake version when you are building with Xcode 8. I couldn't upgrade to Xcode 8 yet, but like I said before, that build option works for me with previous version of Xcode.

**Comment by cadaver** [comment] 2016-10-18 10:49
Will check this on Xcode 8 today or shortly after.

**Comment by danhambleton** [comment] 2016-10-18 13:34
Ok great - I will also double check that I'm using the latest cmake, etc.

**Comment by cadaver** [comment] 2016-10-18 19:50
Tested with the samples. Clicking the bundle's icon, or alternatively doing a manual start in terminal inside the MacOS dir with ./ExecutableName -pp ../Resources both worked for me.

**Comment by danhambleton** [comment] 2016-10-21 16:22
So, the app store is being annoying, but I can confirm that the apps can't find the Resource Dirs using -DURHO3D_MACOSX_BUNDLE=1 and XCode 7.2. 

I will keep trying to install XCode 8.

**Comment by weitjong** [comment] 2016-11-07 16:46
Just curios, were you using this file ```CMake/Modules/MacOSXBundleInfo.plist.template``` in your build?

**Comment by weitjong** [comment] 2016-12-01 14:15
Since there is no more update from OP and also I am not able to reproduce the issue on my macOS Sierra + Xcode 8, so closing this issue for now.

**Closed by weitjong** 2016-12-01 14:15 UTC
Labels: build system
