### ISSUE TITLE
For CI - setup Clang-tidy as the linter tool

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#2113] opened 2017-09-03 00:49 UTC
It can be configured to use C++ Core Guidelines checks. A place holder Lint build stage has been added in our primary CI configuration for a few weeks already. The Clang-tidy has an auto fix it feature, if the corresponding check support it. So, in the background we can also use this tool to check and fix our code base. Initially we will the let the warnings in the CI passed but eventually once we have configured which checks we want to enforce and after our code base has passed those checks in flying colors then a flag will be switched on to treat the warning as error. That is, PRs and commits will be subjected to those checks automatically and only accepted when they produce no errors.

**Comment by weitjong** [comment] 2017-09-05 13:25
Update: CLion appears to have built-in Clang-tidy tool with some sane options set.

**Comment by weitjong** [comment] 2017-09-06 14:08
In the next couple of days I will make a few commits to push the automatic fixes done by the CLion built-in Clang-tidy tool. The default enabled/disabled checks are listed [here](https://confluence.jetbrains.com/display/CLION/Clang-Tidy+in+CLion%3A+default+configuration). Intentionally each individual commit will contain fixes for one check for easy reversal. So, please shout as early as possible if you disagrees with those enabled checks as setup by the bright people from JetBrains.

**Comment by weitjong** [comment] 2017-09-07 14:26
There is something wrong with our project setup that prevents the built-in Clang-tidy tool to produce complete analysis result. Some how it just reports/fixes issues from Source/Samples and Source/Tools, but not from the Sample/Urho3D itself. In view of that, I will stop doing what I plan to do until I figure out why this is so.

**Comment by weitjong** [comment] 2017-09-09 11:47
It was caused by PCH. Temporarily disable it in my build tree and I am back in business.

**Comment by weitjong** [comment] 2017-09-13 14:56
Just want to point out a drawback of my current approach. As I am using the tool in Linux, the tool only "sees" the code branch using the OpenGL graphics API. In other words, those modernization and also auto-fixes from Clang-tidy will not touch DirectX graphics APIs, so manual work is still needed to bring the code base to be fully consistent with each other.

**Comment by weitjong** [comment] 2017-09-13 15:05
One more thing. As I will be rebasing the branch every now and then, please leave any comment here instead of in the commit itself as GitHub will not keep them after rebasing altered the commit SHA.

**Comment by eugeneko** [comment] 2017-09-15 18:22
I have some issues.

1. `UIElement::SetColor`: CS violation: `corner_color`

2. Why `colors_` in `AnimatedSprite2D.cpp`? I don't even understand how does it compile.

3. modernize-loop-convert ended up with lots of `auto` that is not redundand at all. For example, it was almost impossible to understand underlying type when reviewing the commit. So I suggest to un-auto-fy these places.

**Comment by weitjong** [comment] 2017-09-16 03:32
Thanks for your feedback.

> UIElement::SetColor: CS violation: corner_color

My bad. Doing too many CSS3 authoring lately at work and accidentally carried the code style over :smiley: It will be fixed.

>  Why colors_ in AnimatedSprite2D.cpp? I don't even understand how it compiles.

Overall I am still not happy with my last two commits. The CI builds have not even been all green yet. Hopefully I find sometime to fix the error complained by the AppVeyor and also the one you pointed later.

It was an auto-refactored result (with my manual override)  from Clion on the commented out code branch. As you know some of the code branches are conditionally commented by the compiler preprocessor guard. In the above case as I don't have `URHO3D_SPINE` in my build tree, those replace code are not being compiled at all. The variable was wrongly replaced based on its name similarity alone. Conclusion: Next time I will be careful to give the "manual override" to the refactoring tool to prevent things like this.

> modernize-loop-convert ended up with lots of auto that is not redundand at all. For example, it was almost impossible to understand underlying type when reviewing the commit. So I suggest to un-auto-fy these places.

With all due respect, I have to disagree. If the usage of `auto` keyword in `for (auto item: v)`, where v is a known vector or any other collection types, is considered a bad form then I don't know how to program C++11 anymore. As this is an opinionated view, there will be no end to this type of discussion. However, I am more of a pragmatic guy, so I will not spend extra time to "unfix" those modernized code by the tool.

**Comment by weitjong** [comment] 2017-09-16 04:26
Another pragmatic way is to configure the Clang-tidy tool not to use the "modernize-loop-convert" check at all. Then the last two commits can be erased from the commit history. The implication of not having that check would be that later our CI linter build stage won't enforce anything on this. It will turn a blind eye on any old-style for-loop that could have been potentially modernized for prosperity.

Another more pragmatic and drastic way for me is to stop all this work now, if all of you have doubt on the benefit of having Clang-tidy as the linter tool,

**Comment by eugeneko** [comment] 2017-09-16 09:11
> If the usage of auto keyword in for (auto item: v), where v is a known vector or any other collection types, is considered a bad form then I don't know how to program C++11 anymore

BTW, this is clarified in Google code standard.
I consider it as the most readability-friendly guideline.
https://google.github.io/styleguide/cppguide.html#auto

> (Allowed) When the type is clear from local context (in the same expression or within a few lines). Initialization of a pointer or smart pointer with calls to new commonly falls into this category, as does use of auto in a **range-based loop over a container whose type is spelled out nearby.**

> (Encouraged) **When iterating over a map with a range-based loop** (because it is often assumed that the correct type is std::pair<KeyType, ValueType> whereas it is actually std::pair<const KeyType, ValueType>). This is particularly well paired with local key and value aliases for .first and .second (often const-ref).

In most places auto gives literally no benefit (e.g. auto instead of Octant*) but some confusion (it's really harder to e.g. review the code). And finally, there still are many range loops with explicit type.
However, I could fix this item on my own when your work is merged.

> Overall I am still not happy with my last two commits. The CI builds have not even been all green yet. 

> Another more pragmatic and drastic way for me is to stop all this work now, if all of you have doubt on the benefit of having Clang-tidy as the linter tool,

Is it hard to configure Clang-tidy step by step? Start with items that doesn't cause any problems, like `virtual` stuff and so on. Put breaking items on hold.

**Comment by weitjong** [comment] 2017-09-16 09:20
If you wish to manuall un-auto those then be my guess. Just note than I may git rebase from time to time, so my devs branch is generally hard to track. I think that check only cares about modernize the for-loop itself, so I reckon it will still consider the modified range-based for-loop as good with or without `auto` keyword being used.

**Comment by weitjong** [comment] 2017-09-25 14:37
There is a regression issue with the last commit dace613a4d8a823b7ed47a925525ffc4eadba786. The refactored Math classes, like StringHash, have made AS bindings go haywire. Running complex AS scripts like Editor.as would show the regression clearly. Lua side is tested ok so far. Will investigate further but would appreciate some help here.

**Comment by eugeneko** [comment] 2017-09-25 19:59
I don't see any problem neither in code (except some garbage) nor in the built version (msvc 2015 debug)
Could you elaborate?

**Comment by weitjong** [comment] 2017-09-25 23:50
If you check out the commit and build then running the Editor, you should see it actually doesn't work any more. Even the initial Scenegraph is being listed in the hierarchy window. The inspector window also not showing anything when a node/component is selected.

**Comment by eugeneko** [comment] 2017-09-26 06:18
So, It worked for me. So strange...

**Comment by weitjong** [comment] 2017-09-26 06:29
Not at all. AS binding uses calling convention that is specific to each platform. At least we know it works for Windows platform now and only failed on 64-bit Linux. It probably means `=default` may generate code that AS does not known how to bind. And if so, it is beyond the scope of what I am assigning for.

**Comment by eugeneko** [comment] 2017-09-26 08:25
This is also strange because C++ standard doesn't specify any new calling convention for =default stuff.
Does reverting op= fix the problems?

IMO AS integration in Urho is the ugliest thing in the whole engine. It's a kind of time bomb because of those hacks with assembler mixins.

**Comment by weitjong** [comment] 2017-09-26 09:42
Reverting the last commit or just the StringHash class fixed the problem. But I am afraid the StringHash is not the only problematic classes. Need to get into the bottom of this to see how wide spread the regression issue caused by `=default` for GCC on Linux platform. Later when I have time I will try using Clang.

**Comment by eugeneko** [comment] 2017-09-26 09:52
Could you please try to revert only op= for StringHash?
If the problem is only with this op, we should avoid defaulting it neither via Clang nor manually.

**Comment by weitjong** [comment] 2017-09-26 10:48
I believe I have tried that and didn't help. Will retry again just to be sure.

**Comment by eugeneko** [comment] 2017-09-26 11:02
I'm asking because ctors are not exposed into AS at all: they are wrapped into helper functions.
So, AS asm hacks shouldn't be altered by defaulted ctor.

**Comment by weitjong** [comment] 2017-09-26 13:48
Same problem with Clang compiler, which in a way is a good thing, i.e. it is not GCC bug or anything like that. The problematic code is the copy-ctor and not the `operator=()`.

**Comment by eugeneko** [comment] 2017-09-26 14:16
What if you just delete these ops? I believe they are unneed in `StringHash`

**Comment by weitjong** [comment] 2017-09-27 01:45
It is still a "regression" if we do that.

**Comment by weitjong** [comment] 2017-09-27 16:03
I can confirm that the `X64_CallFunction()` in the as_callfunc_x64_gcc.cpp file is not receiving the correct input parameter. Just as I afraid. If it is the native calling convention of AS does not play ball then it is beyond my skill to troubleshoot it.

**Comment by weitjong** [comment] 2017-09-29 12:56
Just tested the AS generic calling convention targeting Web platform with all the refactored code from this branch and AS scripting API worked just fine there. I will try to build with AS generic calling convention on Linux platform. I remember in the past Lasse has mentioned the preference to switch to the generic calling convention for all platforms whenever it is possible.

**Comment by weitjong** [comment] 2017-10-05 16:20
Made some changes on the math classes binding to use the C++11 support from the AS library to fix the problem with the native calling convention. Tested  fine on my 64-bit GCC build. Pushed to CI to verify on the rest of the platforms.

**Comment by eugeneko** [comment] 2017-10-06 08:41
Great!
BTW, what's the purpuse of all_float and all_int tags?

**Comment by weitjong** [comment] 2017-10-06 10:41
See http://www.angelcode.com/angelscript/sdk/docs/manual/doc_register_val_type.html.

**Comment by eugeneko** [comment] 2017-10-15 17:55
I don't understand recent changes in Serializable virtual methods.
Why function parameter became the property of the class? I don't see any long-term meaning of this property, so it looks like a cludge.

**Comment by weitjong** [comment] 2017-10-16 00:48
Yes, I agree. I also think so too, but forget to put a comment there that more future refactoring is needed. The instance default flag was introduced by me years ago when I introduced the feature "reset to default" for UI-Element classes. A new parameter with default value was added to the Load() virtual method to achieve that. The default value shields its impact to other non UI-Element classes. However, clang-tidy does not like that. Cannot have default parameter in virtual method. So, I moved that flag up to the class. Ideally it should be only added to the base UIElement class. But it is quicker for me that time to move it to where the action takes place. As my main focus now is still to get the clang tidy work completed. You are welcome to change the code if you have time to fix it proper now.

**Comment by eugeneko** [comment] 2017-10-16 01:07
I didn't tested it, but I prefer classical approach: virtual method with max amount of parameters, non-virtual pass-through helpers instead of default arguments. Is there any problems with this approach?

PS. I also think GetMaterial should be non-virtual because of the same reason.

**Comment by weitjong** [comment] 2017-10-16 01:32
In order to avoid the miscommunication like last time, I will reserve to comment until I see some code.

**Comment by eugeneko** [comment] 2017-10-16 08:26
I mean smth like this:
```
virtual bool Load(xml, flag);
bool Load(xml) { return Load(xml, false); }
```

**Comment by weitjong** [comment] 2017-10-16 09:36
I see. But it is still not optimal. If you really look at the code, the flag is always false in all cases, expect when loading the UI Element style. I actually regretted for adding the flag there later. So, I take this as an opportunity to rectify the mistake.

**Comment by weitjong** [comment] 2017-10-16 15:08
Quick update: 1367 more lint error to go!

**Comment by eugeneko** [comment] 2017-10-16 15:17
You have done so much work...
BTW, what's the "lint error"? Is it rule violation alert?

**Comment by weitjong** [comment] 2017-10-16 15:33
It's a mix bag. See https://confluence.jetbrains.com/display/CLION/Clang-Tidy+in+CLion%3A+default+configuration
I could also just flip the switch to off and pretend nothing happens :) So far, I did not do that.

**Comment by weitjong** [comment] 2017-10-22 05:57
The `noexcept` change has manifested an old MinGW bug on our 32-bit build. Attempt to workaround the Internal Compiler Error has failed also. Upgrading MinGW version on Travis build environment is out of the option. I could not find any newer backported MinGW version for Ubuntu 14.04 Trusty. If no workable solution could be found then I would be forced to drop 32-bit MinGW build for now.

**Comment by eugeneko** [comment] 2017-10-22 06:59
@weitjong Maybe it worths to drop `noexcept` linter? Since Urho don't use exceptions, noexcept looks verbose and meaningless.
I suppose it may be useful only for move ctors and so on.

**Comment by weitjong** [comment] 2017-10-22 10:27
Just to be clear. I am not proposing to drop the platform support for 32-bit MinGW build, but just the CI build itself on Travis-CI. User with newer MinGW version should have no problem compiling code with `noexcept` specifier. Also, there is no "modernizer-noexcept-like" check that imposes us to use `noexcept`in our code per se. I added the `noexcept` as a way to mitigate the errors when [cert-err58-cpp](https://www.securecoding.cert.org/confluence/display/cplusplus/ERR58-CPP.+Handle+all+exceptions+thrown+before+main%28%29+begins+executing) check is being observed. That is, instead of defensively declare all our static globals inside try-catch block, what I attempted to do is by convincing the compiler that our ctor won't throw any exception. It seems to work. Those that I have changed in the last commit are the easier one where they genuinely do not throw. I am still not sure what to do with those ctor that could possibly throw yet. I don't think we could blindly add the `noexcept` when, for example, the ctor allocation may throw an out of memory exception. Although Urho does not use C++ exception feature, the downstream project that uses Urho as external library might. Anyway, disabling the crt-err58-cpp will not move the problem away. Our coverity-scan setup will still report them as issues, I believe. So we may as well get the job done well while we are at it.

**Comment by eugeneko** [comment] 2017-10-22 10:59
@weitjong Well, this makes sence, I see.

**Comment by weitjong** [comment] 2017-10-29 03:38
Back on track again. Finally done enough "sacrifice" to keep the "old God" happy.

**Comment by weitjong** [comment] 2017-12-17 07:15
I will probably merge this in before completing the whole exercise for a selfish reason so that I don't have to deal with constant rebasing of the whole lot and also incoming changes in big number due to license year bump.

**Comment by rokups** [comment] 2018-01-08 11:24
I see this was merged. Any chance we could get clang-tidy/format config files you have used? I am still hoping this to be usable by users before pushing changes to repo.

**Comment by weitjong** [comment] 2018-01-08 11:50
The work is not finished yet. But yes, this is ultimately the goal as I stated in the issue description.

**Comment by rokups** [comment] 2018-01-08 12:16
Is config just incomplete or does it break things in unexpected ways? Incomplete config would still be useful for downstream projects or contributors to use.

**Comment by weitjong** [comment] 2018-01-08 12:26
The way I have in mind is to setup the linter stage configured in the CI. The place holder is already in place. With the code base that we have right now, the primary CI will always be reported as failed if I enable this prematurely. The target config will be what has been preset by JetBrains for their Clion.

**Comment by weitjong** [comment] 2018-01-13 11:53
Quick update: left with 68 more lint error to go!

**Comment by weitjong** [comment] 2018-01-14 02:48
All cleared now. I will merge the dev branch into master later today when I have time and hopefully together with the build system enhancement to invoke the `clang-tidy` host tool in the CI lint phase.

@eugeneko one of the mitigation is to replace the static down cast to dynamic cast in the library user code, but I am totally not sure the usefulness of that particular check itself. If I want to use static_cast then I must be sure what the original type is and prepare to shoot myself in the foot for the slight performance gain over the dynamic_cast. Last night I was this close to just disable that check. That would be the first check got flipped if I do so. In the end I just give in. Doing dynamic cast without checking for null return is a bit pointless though. What do you think?

**Comment by weitjong** [comment] 2018-01-16 05:22
After a second thought I have decided to disable the check instead. The commit in question will be reverted back in the dev branch soon.

**Comment by eugeneko** [comment] 2018-01-16 07:48
For some reason I missed previous message, sorry.
I agree, this replacement doesn't worth possible performance loss.
`static_cast`s in Urho code are quite justified.

**Comment by weitjong** [comment] 2018-01-17 17:29
The initial setup for the lint stage is done. However, I am not able to tighten the screw yet to treat all warnings as errors because I haven't found way to filter out lint warnings/errors from the 3rd-party libs.

**Comment by weitjong** [comment] 2018-01-18 14:38
I think I figured out how to configure the header filter. Now trying to treat all warnings as errors. Since our code as it is now still have a few remaining issues, the CI lint stage should fail. So, it is good as our test case.

Depends on the severity of the remaining issues (seems like `clang-tidy` in CLI mode does a more thorough job), we will need a few more rounds of fixing to do to make our code passing with flying colors.

**Comment by weitjong** [comment] 2018-01-21 16:36
Only left with the lint errors coming from "cert-err58-cpp". This is harder to fix than I originally thought. I might have to revert 4a04c814e72f0c58814222065bc61731dccc4de4 and partial revert e2ecc52adcf146f6a5ca3bfe52932d62ecb2f912 and rethink on how to mitigate those global static definitions to pass this particular check. Moving some of them into function/method scope may have performance impact as C++11 compiler will add extra guard code to guarantee thread-safety of such construct. It will be great if I have second opinion on how to mitigate this proper.

The header filter regex gives me problem also. On my local Fedora 26, the negative lookahead RE works as expected to exclude the 3rd-party code, but on Travis CI (Ubuntu Trusty) even the basic RE does not work, not to mention the extended one (I guess due to poorer regex support for older libstdc++). As we do not want to touch 3rd-party code for this purpose, any errors coming from 3rd-party code will also fail CI lint job with the current setup. Not good. Will probably have to workaround this by not treating warnings as errors and then somehow perform the filtering logic on our own.

**Comment by weitjong** [comment] 2018-01-22 16:15
As there are no feedback and I don't know how best to mitigate this without causing performance impact at all, I have reverted back those static global to namespace scoped and disable the cert-err58-cpp check for now.

**Comment by weitjong** [comment] 2018-01-23 18:09
Also workaround the header filter regex problem by utilizing the regex support from Rake. I believe I am done here. If there is no objections then this dev branch will be merged to master at the soonest.

**Closed** 2018-01-24 00:37 UTC
Labels: build system, enhancement

**Comment by rokups** [comment] 2018-01-24 10:51
Congratulations on finishing this one up! Any chance we will see official `clang-format` config soon as well?

**Comment by weitjong** [comment] 2018-01-24 10:55
Thanks. Yes, I am thinking about that too. But may be after merging some of the PR.

**Comment by weitjong** [comment] 2018-01-25 02:16
I just realize `clang-tidy` version 3.9 actually does not perform as well as Clion code inspection for some cases. So I am building Clang version 4.0 this morning and submitting a CI build job to test it just now. If it still does not cut it then I will probably think of our own way to build Clang 5 or 6 using Travis build environment. At the moment we are highjacking the build script from Emscripten SDK to do that and they still stuck at 4.0.

**Comment by weitjong** [comment] 2018-01-27 04:38
Version 4 of the `clang-tidy` host tool is much better than version 3.9, but still not close to what “clang-tidy” inspection of Clion provides. Probably we need to install Clang 5/6 to match it. However, the standalone host tool wins out in corner cases when a few of our classes are too complex for Clion code inspection and it simply gives up doing any inspection on them. That’s the reason even our host tool version is older, it still found linter errors after I completed “all” the fixes in Clion IDE.

**Comment by weitjong** [comment] 2018-01-29 23:41
I have managed to build and install the LLVM/CLang 6 (release candidate). Our newer `clang-tidy` should be on par (if not better) now compared to what Clion has. That's the good news. The bad news is, the new tool now should churn out new linter errors to fix. However, this time we could be more liberal in deciding which new checks to be turned off as our new initially enabled checks list now supersedes what Clion's initial list.
