### ISSUE TITLE
iOS version Urho3D link error.

### ISSUE THREAD

**Issue by lhinuz** [urho3d/Urho3D#1131] opened 2016-01-02 03:52 UTC
When compile iOS version, link error occurred, Urho3D is newest, Xcode 7.1.1, OS X 10.11.1

Ld /Users/att/Work/Temp/Urho3D_Build/ios/Source/Tools/Urho3DPlayer/Urho3D.build/Debug-iphonesimulator/Urho3DPlayer.build/Objects-normal/i386/Urho3DPlayer normal i386
    cd /Users/att/Work/Dev_SDK/Urho3D
    export IPHONEOS_DEPLOYMENT_TARGET=9.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk -L/Users/att/Work/Temp/Urho3D_Build/ios/bin -F/Users/att/Work/Temp/Urho3D_Build/ios/bin -filelist /Users/att/Work/Temp/Urho3D_Build/ios/Source/Tools/Urho3DPlayer/Urho3D.build/Debug-iphonesimulator/Urho3DPlayer.build/Objects-normal/i386/Urho3DPlayer.LinkFileList -mios-simulator-version-min=9.1 -Xlinker -objc_abi_version -Xlinker 2 -framework AudioToolbox -framework CoreAudio -framework CoreGraphics -framework Foundation -framework OpenGLES -framework QuartzCore -framework UIKit -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/att/Work/Temp/Urho3D_Build/ios/lib/libUrho3D.a -ldl -ldl -Xlinker -dependency_info -Xlinker /Users/att/Work/Temp/Urho3D_Build/ios/Source/Tools/Urho3DPlayer/Urho3D.build/Debug-iphonesimulator/Urho3DPlayer.build/Objects-normal/i386/Urho3DPlayer_dependency_info.dat -o /Users/att/Work/Temp/Urho3D_Build/ios/Source/Tools/Urho3DPlayer/Urho3D.build/Debug-iphonesimulator/Urho3DPlayer.build/Objects-normal/i386/Urho3DPlayer

clang: error: no such file or directory: '/Users/att/Work/Temp/Urho3D_Build/ios/lib/libUrho3D.a'

**Comment by weitjong** [comment] 2016-01-02 04:24
There is not enough information to help you to troubleshoot. To me, the last error coming from Clang is already clear **what** was the root cause but not **why** it happened. Follow our [build documentation](http://urho3d.github.io/documentation/HEAD/_building.html) carefully. The doc mentions that we need the latest of CMake version to match with latest of Xcode. Good luck.

**Comment by weitjong** [comment] 2016-01-11 07:50
As there were no more updates, closing it for now. Feel free to reopen it if you have more information.

**Closed by weitjong** 2016-01-11 07:50 UTC
Labels: build system, wontfix
