### ISSUE TITLE
"NMake Makefiles" generator bug

### ISSUE THREAD

**Issue by alex-rass-88** [urho3d/Urho3D#1851] opened 2017-03-09 07:43 UTC
If using "NMake Makefiles" generator and CMAKE_BUILD_TYPE=Release, cmake runs executable after link.

problem line:
https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/UrhoCommon.cmake#L1633

Tested on MSVS 2010 and 2013

**Comment by weitjong** [comment] 2017-03-09 11:06
That generator is currently not supported. I believe it has been discussed before here.

**Comment by alex-rass-88** [comment] 2017-03-09 11:15
if comment line
https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/UrhoCommon.cmake#L1634
all works. 
i think need detect nmake
```
if (CMAKE_BUILD_TOOL STREQUAL "nmake")
    set(NMAKE TRUE)
endif ()
```

and add workaround:

`if (CMAKE_BUILD_TYPE STREQUAL Release AND NOT WEB AND NOT NMAKE)`

**Comment by weitjong** [comment] 2017-03-09 14:04
Duplicate of #1126.

**Comment by cadaver** [comment] 2017-03-09 14:32
@alex-rass-88 NMake build appears to work with the above fix and by disabling PCH (URHO3D_PCH=0). It could be a nice addition for scripting MSVC-based builds, but the PCH should work before we'd call it supported. Would say there's no pressing need to support it either, so it's largely a question if someone (for example you) has interest to make it fully working.

**Comment by alex-rass-88** [comment] 2017-03-09 14:52
NMake build system working excellent. But after merging refactor-buildsystem in release builds cmake run executable after linking. This is one problem what i have.

**Comment by cadaver** [comment] 2017-03-09 14:55
For now I tested in VS2010 command prompt, which is fairly ancient. Could retest in newer VS.

**Comment by alex-rass-88** [comment] 2017-03-09 14:57
I am build with `-DURHO3D_LUA=0 -DURHO3D_SAMPLES=0 -DCMAKE_BUILD_TYPE=Release`

**Comment by weitjong** [comment] 2017-03-09 15:37
IMHO, it failed not because of it is ```MS nmake``` but simply because VS/MSVC compiler toolchain does not have ```strip``` command. So, the condition should be aptly written as

```
if (CMAKE_BUILD_TYPE STREQUAL Release AND NOT WEB AND NOT MSVC)
```

However, this is exactly what worries me. In a few cases the build scripts have conditions that are not explicitly written. Previously checking for the condition ```CMAKE_BUILD_TYPE STREQUAL Release ``` is enough to exclude the MSVC into the picture (since multi-config generator does not define CMAKE_BUILD_TYPE), but now with nmake generator (which I suppose is a single-config generator), suddenly the exclusion would need to be defined explicitly. Now, I cannot recall where I made that kind of optimization but for sure this is not the only instance. Having said that, if the build system works or nearly works as originally intended with ```nmake``` after the above fixes then great. Don't count on it from staying that way though, i.e. someone (and it won't be me) need to constantly maintain it to keep it that way.

**Comment by cadaver** [comment] 2017-03-09 16:12
We could put in that fix and call NMake a kind of use-at-your-own-risk generator, ie. not supported, but if it works, good for you.

**Comment by alex-rass-88** [comment] 2017-03-10 06:51
Test with
`if (CMAKE_BUILD_TYPE STREQUAL Release AND NOT WEB AND NOT MSVC)`
msvc2010 x86 and amd64
msvc2013 x86 and amd64
msvc2015 x86 and amd64
All works excellent.

**Comment by cadaver** [comment] 2017-03-10 11:45
Possibly something wrong with the machine I'm using, or an unclean build tree, still got permission denied errors from the PCH with NMake, even when using newer VS and also updating NMake. Nevertheless, will apply the fix.

**Closed** 2017-03-10 11:45 UTC
Labels: build system, duplicate

**Comment by alex-rass-88** [comment] 2017-03-10 14:42
I have problems with pch only when using nmake with ninja or jom. If use nmake for build it working.

**Comment by weitjong** [comment] 2017-03-12 01:27
> Possibly something wrong with the machine I'm using, or an unclean build tree, still got permission denied errors from the PCH with NMake, even when using newer VS and also updating CMake. Nevertheless, will apply the fix.

Currently our build scripts assume that MSVC compiler toolchain is only used in a msbuild-based build tree, such as VS solution file. This has two implications:
- Since CMake/VS generator is a multi-config generator, our build scripts may use the single/multi-config generator condition to include/exclude certain logic for MSVC. This has been pointed out in my previous comment.
- To workaround the limitation of MSVC (or at least to mitigate the discrepancy between it and the rest of the compiler toolchains), our build scripts may use tricks (or hacks) that relies on the internal structure of the msbuild-based build tree generated by the CMake/VS generator.

The enable_pch() macro for MSVC may not work as originally intended because ```nsmake``` invalidates all the above.
