### ISSUE TITLE
Android Studio: Could not check compiler toolchain as it does not handle '-E -dM' compiler

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1910] opened 2017-04-14 20:23 UTC
I am getting this error through Android Studio, but it works fine through terminal. If I bypass the lines in CheckCompilerToolchain.cmake it seems to work fine. Can we have this check optional?
```
-- Check for working C compiler: /Users/sabo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/sabo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/sabo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/sabo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMake/Modules/CheckCompilerToolchain.cmake:161 (message):
  Could not check compiler toolchain as it does not handle '-E -dM' compiler
  flags correctly
Call Stack (most recent call first):
  CMake/Modules/UrhoCommon.cmake:98 (include)
  CMakeLists.txt:18 (include)
-- Configuring incomplete, errors occurred!
```

**Comment by weitjong** [comment] 2017-04-15 02:28
Android Studio and/or Gradle build system is not officially supported yet, though probably it will be sometime in future. Contribution is welcome, if you want to make that happen sooner.

**Comment by sabotage3d** [comment] 2017-04-15 11:18
I am still working on it still have some problems but I can share my project when I am done. What I am not sure is why this check doesn't work under Android Studio? And if it is needed at all.

**Comment by weitjong** [comment] 2017-04-15 11:57
As it's name implies, this module checks the capabilities of the chosen compiler toolchain. The build script may use the info to configure the build tree one way or another. The logic was in the main UrhoCoommon module before it being externalized in a separate module. So, you cannot do away with it. As for why it failed in your case, that's hard for me to say. Clearly the toolchain was not setup accordingly in the Android Studio or it was not setup according to what the scripts expect.

I may come to revisit this sometime later when I have extra time to make our scaffolding support even better and to add gradle build support for Android platform. But I am afraid you are on your own for now.

**Comment by sabotage3d** [comment] 2017-04-15 12:40
I have a feeling that CMake's execute_process inside Android Studio might not be allowed. I also tried gradlew from the terminal but I got the same problem.

**Comment by cadaver** [comment] 2017-04-16 11:53
Check that the ndk is the newest you can get (if Android Studio supports installing a newer one). I remember having that error message with ... ndk13?

**Comment by sabotage3d** [comment] 2017-04-23 00:09
Everything is latest I had a fresh install of Android Studio. It is with NDK 14.1.

**Comment by weitjong** [comment] 2017-04-23 02:29
I see you try to persevere.

For me, the issue is not with the version of the Android NDK. For me, it is more because now we use Android ```Clang``` as the default compiler instead of ```GCC```. And for ```Clang``` it needs to be invoked with the extra ```target triple``` flag so it knows which target to use because ```Clang``` inherently could target multiple target architectures/ABIs.

If you now look at [these lines of code](https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/CheckCompilerToolchain.cmake#L155-L162), I believe the cause becomes clearer why it failed in your case. When you call our script from CLI then our Android.cmake toolchain file is used and it set the target triple in the CMAKE_CXX_FLAGS. So, the above regex works. Now when you use Android Studio with Gradle to invoke the CMake for the initial build tree generation, what happens there? Does it use our Android.cmake or does it use the NDK own android.toolchain.cmake (forked from now defunct taka-no-me repo)? I haven't got time to study what has changed between the old taka-no-me version and the new one from Google team. BTW, our Android.cmake is totally a different beast written from scratch here! Mind you that this is just only my guess. You should ask yourself other questions that could be the root cause of your issue besides this too, but I would start from here if I were you. Good luck.

**Comment by sabotage3d** [comment] 2017-05-04 12:43
You have a good point I need to check which tool-chain is invoked. Compiling with gradle have the benefits of easier compiling of multiple ABIs and easier debugging of the code with Android Studio. At the moment I am still using the old way of compiling Urho3d as library for Android and having a separate Android Studio project for my application. If it still causing issues I think we can add flag ANDROID_STUDIO to CMake if it is enabled to skip this check.

**Comment by weitjong** [comment] 2018-06-21 15:14
This issue is fixed in my local branch after adapting the `CheckCompilerToolchain.cmake` module to work with the `android.toolchain.cmake` file. I am closing this issue, all the related updates will be done in #743.

**Closed by weitjong** 2018-06-21 15:14 UTC
Labels: bug, build system
