### ISSUE TITLE
Incorrect perspective transformation on First Project from wiki

### ISSUE THREAD

**Issue by hundinui** [urho3d/Urho3D#2426] opened 2019-03-10 12:27 UTC
Building the First Project from the wiki and running it the viewport appears to be upside down, and when rotating the camera using the mouse, the whole scene gets deformed incorrectly.
Same issue occurs in the Urho3D Editor viewport.
Is this a configuration error on my system or a Urho3D bug?

Using Urho3D 1.7-1 built from source.
Running on GNU/Linux 5.0.
GPU: Intel HD Graphics 3000, using i915 driver
Mesa version 18.3.4-1

Screenshots:
![urho3d-0](https://user-images.githubusercontent.com/42813493/54084928-4b314980-4340-11e9-8ec7-8568399de43f.jpg)
![urho3d-1](https://user-images.githubusercontent.com/42813493/54084931-51bfc100-4340-11e9-8dd2-17da65f0fb91.jpg)

**Comment by weitjong** [comment] 2019-03-10 12:58
Duplicate of #2388.

**Closed by weitjong** 2019-03-10 12:58 UTC
